/**
 * Curated sentences for Level 4 (Advanced) words not already covered.
 */
const ADVANCED_SENTENCES: Record<string, string> = {
  aberration: "The strange weather was an aberration from the usual pattern.",
  abhor: "She seemed to abhor any form of dishonesty.",
  abominable: "The abominable conditions made the journey very difficult.",
  abrasion: "She cleaned the small abrasion on her elbow.",
  absolutism: "Absolutism concentrated all power in the hands of the ruler.",
  absolve: "The judge decided to absolve the defendant of all charges.",
  abstemious: "His abstemious habits kept him in excellent health.",
  abstinence: "The doctor recommended abstinence from sugary foods.",
  abundantly: "The garden was abundantly filled with ripe tomatoes.",
  abyssal: "The abyssal depths of the ocean remain largely unexplored.",
  accentuate: "The bright scarf helped accentuate her outfit.",
  accolade: "Winning the award was the highest accolade of her career.",
  accompanist: "The accompanist played the piano beautifully during the recital.",
  acquiescence: "His quiet acquiescence surprised everyone in the room.",
  acrimonious: "The acrimonious debate lasted well into the evening.",
  acumen: "Her business acumen helped the company grow rapidly.",
  adamant: "She was adamant that the project be completed on time.",
  admonish: "The teacher had to admonish the student for talking in class.",
  adversity: "She showed great courage in the face of adversity.",
  aesthetic: "The building's aesthetic design won several architecture awards.",
  affidavit: "The witness signed an affidavit confirming the facts.",
  affluent: "The affluent neighborhood had large homes and manicured lawns.",
  aforementioned: "The aforementioned rules apply to all participants.",
  afterthought: "The dessert was added to the menu as an afterthought.",
  aggravate: "Scratching the rash will only aggravate the problem.",
  aggregate: "The aggregate score determined the final standings.",
  agile: "The agile gymnast performed a flawless routine.",
  agnosticism: "Agnosticism holds that ultimate truth is unknowable.",
  alchemy: "Medieval alchemy attempted to transform lead into gold.",
  algorithm: "The computer uses an algorithm to sort the data efficiently.",
  alienate: "Being rude to classmates can quickly alienate your friends.",
  allegory: "The novel was an allegory about the dangers of greed.",
  alleviate: "The medicine helped alleviate the pain in her shoulder.",
  altercation: "A brief altercation broke out between the two players.",
  amalgamate: "The two schools decided to amalgamate into one.",
  ambidextrous: "The ambidextrous pitcher could throw with either hand.",
  ambivalent: "She felt ambivalent about accepting the job offer.",
  amenable: "He was amenable to the suggestion of a compromise.",
  amiable: "The amiable host made everyone feel welcome.",
  amicable: "The dispute was resolved in an amicable manner.",
  amnesty: "The government granted amnesty to political prisoners.",
  anachronistic: "Using a typewriter today feels anachronistic.",
  analogous: "The heart is analogous to a pump in its function.",
  anarchy: "Without leadership, the group descended into anarchy.",
  ancestral: "They visited their ancestral homeland overseas.",
  anecdote: "She told a funny anecdote about her first day at work.",
  anguish: "The family felt deep anguish over the tragic news.",
  animosity: "Despite past animosity, the two rivals shook hands.",
  anomaly: "The warm day in January was a weather anomaly.",
  antagonism: "The antagonism between the two groups slowly faded.",
  anthology: "The anthology contained poems from around the world.",
  anticlimactic: "After all the buildup, the ending felt anticlimactic.",
  antiquity: "Artifacts from antiquity filled the museum hall.",
  apathy: "Voter apathy led to a very low turnout at the election.",
  apocalyptic: "The novel painted an apocalyptic vision of the future.",
  apologetic: "She was truly apologetic for arriving late.",
  appease: "He offered a compromise to appease both sides.",
  apprehend: "The officers were able to apprehend the suspect quickly.",
  apprehension: "She felt some apprehension before the big exam.",
  apprenticeship: "He completed a four-year apprenticeship with a master carpenter.",
  arbitrary: "The rules seemed arbitrary and unfair to the students.",
  archipelago: "The archipelago consisted of hundreds of small islands.",
  arduous: "The arduous climb to the summit took over eight hours.",
  aristocracy: "The aristocracy held great power in medieval society.",
  articulate: "She was able to articulate her ideas very clearly.",
  ascertain: "The detective worked to ascertain the truth.",
  assimilate: "New students often need time to assimilate into school life.",
  astonishment: "She stared in astonishment at the unexpected gift.",
  astronomical: "The cost of the renovation was astronomical.",
  asymmetrical: "The artist chose an asymmetrical design for the sculpture.",
  atmospheric: "The candlelit room had a warm and atmospheric glow.",
  atonement: "He sought atonement for the mistakes of his past.",
  atrocity: "The history book documented every atrocity of the conflict.",
  audacious: "The audacious rescue plan saved everyone's life.",
  auspicious: "The sunny weather was an auspicious start to the event.",
  austere: "The monk lived an austere and simple life.",
  authoritative: "The textbook is considered the authoritative guide on the topic.",
  autobiographical: "The film was autobiographical, based on the director's life.",
  autonomous: "The autonomous vehicle navigated the road without a driver.",
  avarice: "The villain's avarice led to his ultimate downfall.",
  avaricious: "The avaricious landlord raised the rent every year.",
  aversion: "She had a strong aversion to public speaking.",
  backsliding: "The coach warned against backsliding on training goals.",
  battleground: "The field became a historic battleground during the war.",
  beautification: "The city invested in the beautification of its downtown area.",
  bedevil: "Technical problems continued to bedevil the project.",
  belligerent: "The belligerent tone of the argument upset everyone.",
  bemusement: "She watched the juggler with a look of bemusement.",
  benediction: "The ceremony concluded with a benediction.",
  benevolence: "Her benevolence was evident in the many charities she supported.",
  bequest: "The generous bequest funded a new wing of the library.",
  bewilderment: "He looked around the unfamiliar city in bewilderment.",
  biographical: "The biographical film told the story of the inventor's life.",
  blemish: "The single blemish on the fruit made it unsellable.",
  bloodthirsty: "The villain in the story was bloodthirsty and cruel.",
  bombardment: "The city endured a heavy bombardment during the siege.",
  bountiful: "The harvest this year was particularly bountiful.",
  breathtaking: "The view from the mountaintop was absolutely breathtaking.",
  brevity: "The brevity of his speech was refreshing.",
  brinkmanship: "Political brinkmanship brought the negotiations to the edge.",
  broaden: "Travel can broaden your understanding of the world.",
  brotherhood: "The spirit of brotherhood united the community.",
  businesslike: "She conducted the meeting in a brisk and businesslike manner.",
  calamitous: "The calamitous flood destroyed the entire village.",
  calamity: "The earthquake was a calamity of enormous proportions.",
  calibrate: "The technician needed to calibrate the instrument carefully.",
  callous: "His callous remarks hurt the feelings of his classmates.",
  camaraderie: "The camaraderie among teammates made the season enjoyable.",
  candid: "She gave a candid interview about her experiences.",
  cantankerous: "The cantankerous old man complained about everything.",
  capitulate: "The army was forced to capitulate after the long siege.",
  capricious: "The capricious weather changed from sunny to stormy in minutes.",
  captivate: "The storyteller's voice seemed to captivate the entire audience.",
  carcinogen: "Tobacco smoke is a known carcinogen.",
  catalyst: "The discovery served as a catalyst for further research.",
  categorically: "She categorically denied any involvement in the incident.",
  caustic: "The caustic chemical burned a hole through the cloth.",
  censorship: "The author spoke out against censorship of the press.",
  centrifugal: "The centrifugal force pushed the riders outward on the spin.",
  cerebral: "The film was a cerebral thriller that made you think.",
  charisma: "The leader's charisma inspired millions of followers.",
  chronology: "The historian arranged the events in careful chronology.",
  circumscribe: "The rules circumscribe what students may do during recess.",
  circumstantial: "The evidence against the suspect was only circumstantial.",
  circumvent: "She found a clever way to circumvent the problem.",
  clandestine: "The spies conducted a clandestine operation at midnight.",
  claustrophobia: "Her claustrophobia made it difficult to ride the elevator.",
  coalesce: "The small groups began to coalesce into one large movement.",
  coerce: "It is wrong to coerce someone into making a decision.",
  cognition: "The study explored the effects of sleep on cognition.",
  coherent: "She wrote a clear and coherent essay.",
  collaboratively: "The students worked collaboratively on the science project.",
  collateral: "The bank required collateral for the large loan.",
  colloquial: "The expression is colloquial and used mostly in casual speech.",
  commensurate: "The salary was commensurate with her level of experience.",
  commissary: "The troops bought supplies at the base commissary.",
  commodious: "The commodious living room could seat twenty guests.",
  communal: "The apartment building had a large communal garden.",
  compassionately: "She spoke compassionately to the grieving family.",
  compendium: "The book was a compendium of recipes from around the world.",
  compensatory: "The court awarded compensatory damages to the plaintiff.",
  complacent: "Don't become complacent after one success; keep working hard.",
  compliant: "The factory was fully compliant with safety regulations.",
  comprehensible: "The instructions were clear and easily comprehensible.",
  concede: "After counting the votes, he had to concede the election.",
  conceivable: "Every conceivable option was explored before the decision.",
  conceptualize: "The architect began to conceptualize the new building design.",
  concession: "Both sides made a concession to reach an agreement.",
  conciliatory: "His conciliatory tone helped ease the tension in the room.",
  concurrent: "The two events ran concurrent with each other.",
  condescend: "She would never condescend to someone less experienced.",
  condescension: "His condescension was evident in the way he spoke to others.",
  confiscate: "The teacher had to confiscate the phone during the exam.",
  congregational: "The congregational meeting discussed plans for the new hall.",
  conjecture: "Without evidence, the theory remains mere conjecture.",
  connoisseur: "She is a connoisseur of fine Italian wines.",
  conspicuous: "The bright red hat made her conspicuous in the crowd.",
  conspiratorial: "They exchanged conspiratorial glances across the room.",
  constituency: "The politician listened to concerns from her constituency.",
  contemplate: "She sat quietly to contemplate her next move.",
  contemptuous: "He gave a contemptuous look at the suggestion.",
  contentious: "The proposal was highly contentious among committee members.",
  contingency: "The team prepared a contingency plan in case of rain.",
  contraband: "The border agents seized the contraband goods.",
  contradictory: "The two reports offered contradictory information.",
  convergence: "The convergence of the two rivers created a wide delta.",
  convincingly: "She argued convincingly in favor of the new policy.",
  convoluted: "The convoluted instructions were hard to follow.",
  cooperatively: "The children played cooperatively during the group activity.",
  copious: "She took copious notes during the lecture.",
  corroborate: "The witness testimony helped corroborate the evidence.",
  cosmopolitan: "The cosmopolitan city attracted visitors from around the globe.",
  counterbalance: "The weight on one side served to counterbalance the other.",
  counterfeit: "The police uncovered a counterfeit money operation.",
  counterintuitive: "The correct answer seemed counterintuitive at first.",
  counterproductive: "Working without breaks is actually counterproductive.",
  courageously: "She courageously spoke up against the unfair treatment.",
  covenant: "The community signed a covenant to protect the wetlands.",
  covert: "The covert operation was kept secret from the public.",
  craftsmanship: "The quality of craftsmanship in the furniture was exceptional.",
  credibility: "Lying would destroy her credibility as a witness.",
  crescendo: "The music built to a powerful crescendo at the finale.",
  crystallize: "Her thoughts began to crystallize into a clear plan.",
  culminate: "Years of training will culminate in the final competition.",
  culpable: "The investigation found the company culpable for the spill.",
  cumulative: "The cumulative effect of the changes was significant.",
  dearth: "There was a dearth of experienced candidates for the position.",
  debilitate: "The illness continued to debilitate his strength.",
  decadence: "The decadence of the wealthy court shocked the common people.",
  decorum: "Students are expected to show proper decorum at assemblies.",
  defamation: "The article was considered defamation of the politician's character.",
  deference: "She spoke with deference to the senior members of the team.",
  deficiency: "A vitamin deficiency can affect your overall health.",
  degradation: "Soil degradation threatened the region's farmland.",
  deliberation: "After careful deliberation, the jury reached a verdict.",
  delinquent: "The delinquent payment resulted in a late fee.",
  demagogue: "The demagogue stirred up fear to gain political support.",
  demeanor: "Her calm demeanor put everyone at ease.",
  demography: "Demography studies the characteristics of human populations.",
  denounce: "Several leaders rushed to denounce the act of violence.",
  depict: "The mural was designed to depict the town's rich history.",
  deploy: "The company will deploy the new software next month.",
  derelict: "The derelict building had been abandoned for decades.",
  derogatory: "Derogatory comments about others are never acceptable.",
  designate: "The park was designated as a national historic landmark.",
  desolate: "The desolate landscape stretched for miles without a tree.",
  despicable: "Bullying others is a despicable form of behavior.",
  destitute: "The charity provides meals for destitute families.",
  deterministic: "A deterministic model always produces the same result.",
  detrimental: "Lack of sleep can be detrimental to your performance.",
  dexterous: "The dexterous surgeon performed the delicate operation flawlessly.",
  diametrically: "Their opinions were diametrically opposed.",
  dichotomy: "The dichotomy between rich and poor was very apparent.",
  diffident: "The diffident student hesitated before raising her hand.",
  dilapidated: "The dilapidated house needed extensive repairs.",
  dilettante: "He was a dilettante who dabbled in many hobbies.",
  diminish: "The fog began to diminish as the sun rose higher.",
  diplomacy: "Diplomacy helped prevent the conflict from escalating.",
  disadvantageous: "The wet field conditions were disadvantageous for the visiting team.",
  discern: "She could discern the subtle differences between the paintings.",
  disciplinarian: "The strict principal was known as a firm disciplinarian.",
  discrepancy: "There was a discrepancy between the two financial reports.",
  discretion: "Use your own discretion when choosing a topic for the essay.",
  discriminatory: "Discriminatory practices are against the law.",
  disdain: "She looked at the messy room with obvious disdain.",
  disillusioned: "The fans were disillusioned after the team's losing streak.",
  disinterested: "A good judge must remain disinterested and impartial.",
  dismantle: "Workers began to dismantle the old scaffolding.",
  disparage: "It is wrong to disparage someone's hard work.",
  disparity: "The disparity in wages between the two jobs was significant.",
  disposition: "Her sunny disposition made her popular with everyone.",
  disseminate: "The website helped disseminate the information quickly.",
  dissent: "Several members voiced their dissent at the meeting.",
  dissolution: "The dissolution of the partnership was handled amicably.",
  distinguished: "The distinguished professor received a lifetime achievement award.",
  docile: "The docile pony was perfect for young riders.",
  dogmatic: "His dogmatic approach left no room for new ideas.",
  dormant: "The volcano has been dormant for thousands of years.",
  draconian: "The draconian rules were considered too harsh by many.",
  dubious: "The claim sounded dubious and lacked supporting evidence.",
  duplicity: "His duplicity was revealed when the truth came out.",
  dysfunctional: "The dysfunctional system needed a complete overhaul.",
  eccentric: "The eccentric inventor had a laboratory full of odd gadgets.",
  edifice: "The grand edifice of the cathedral towered over the city.",
  efficacy: "The study tested the efficacy of the new treatment.",
  egalitarian: "The community was built on egalitarian principles.",
  elicit: "The comedian's joke was designed to elicit laughter.",
  elucidate: "The professor tried to elucidate the complex theory.",
  elusive: "The elusive butterfly evaded capture all afternoon.",
  emancipate: "The declaration was intended to emancipate the enslaved.",
  embargo: "The trade embargo restricted imports from the country.",
  embellish: "She liked to embellish her stories with vivid details.",
  embezzle: "The manager was arrested for attempting to embezzle company funds.",
  empirical: "The conclusion was supported by empirical data.",
  emulate: "The young artist tried to emulate the style of the masters.",
  encapsulate: "The poem manages to encapsulate the spirit of the season.",
  encompass: "The curriculum will encompass a wide range of subjects.",
  endeavor: "Learning a new language is a worthy endeavor.",
  endowment: "The generous endowment funded scholarships for students.",
  enigma: "The disappearance of the ship remains an enigma.",
  enlighten: "The documentary aims to enlighten viewers about climate change.",
  enmity: "Years of enmity between the two families finally ended.",
  enumerate: "She began to enumerate the reasons for the decision.",
  ephemeral: "The beauty of the cherry blossoms is ephemeral.",
  epitome: "She was the epitome of grace and elegance.",
  equanimity: "He faced every challenge with remarkable equanimity.",
  equilibrium: "The balance beam tests your sense of equilibrium.",
  equitable: "The goal is to create an equitable distribution of resources.",
  eradicate: "Vaccines helped eradicate smallpox from the world.",
  erratic: "His erratic driving alarmed the other motorists.",
  erroneous: "The newspaper published an erroneous report.",
  eschew: "She chose to eschew fast food in favor of healthy meals.",
  esoteric: "The lecture covered esoteric topics few people understood.",
  espionage: "The spy novel was about international espionage.",
  ethereal: "The ethereal music created a dreamlike atmosphere.",
  euphemism: "Saying someone passed away is a euphemism for dying.",
  exacerbate: "The dry weather could exacerbate the wildfire risk.",
  exemplary: "Her exemplary behavior earned her a citizenship award.",
  exemplify: "Her dedication to the team seemed to exemplify true sportsmanship.",
  exonerate: "New evidence was found to exonerate the innocent man.",
  expatriate: "The expatriate community gathered at the embassy for the holiday.",
  expedient: "The quickest route seemed the most expedient option.",
  expedite: "We hired extra staff to expedite the order processing.",
  explicit: "The instructions were explicit and easy to follow.",
  exponentially: "The population of the city grew exponentially.",
  exquisite: "The chef prepared an exquisite five-course meal.",
  extemporaneous: "She gave an impressive extemporaneous speech at the event.",
  extenuating: "The judge considered the extenuating circumstances of the case.",
  extravagant: "The extravagant wedding had a thousand guests.",
  extricate: "He managed to extricate himself from the difficult situation.",
  fabricate: "She was caught trying to fabricate an excuse for being late.",
  facetious: "His facetious comment brought laughter to the tense meeting.",
  fallacy: "The argument was based on a common logical fallacy.",
  fanatical: "The fanatical fans cheered throughout the entire game.",
  fastidious: "She was fastidious about keeping her workspace tidy.",
  feasible: "The committee determined that the plan was feasible.",
  fervent: "She was a fervent supporter of environmental conservation.",
  fiasco: "The poorly planned event turned into a complete fiasco.",
  fidelity: "The recording captured the music with remarkable fidelity.",
  figurative: "The poet used figurative language to convey emotion.",
  flagrant: "The flagrant violation of the rules resulted in a penalty.",
  flamboyant: "The dancer wore a flamboyant costume covered in sequins.",
  fluctuation: "The fluctuation in temperature made it hard to dress properly.",
  forbearance: "She showed great forbearance in dealing with the rude customer.",
  foreclose: "The bank threatened to foreclose on the property.",
  forensic: "The forensic team analyzed the evidence at the crime scene.",
  formidable: "The opposing team was a formidable challenger.",
  fortitude: "She displayed remarkable fortitude during the long illness.",
  franchise: "He bought a fast-food franchise in the new shopping center.",
  frivolous: "The judge dismissed the frivolous lawsuit immediately.",
  frugal: "Being frugal helped them save enough for a vacation.",
  futile: "Their attempts to stop the flooding proved futile.",
  galvanize: "The speech was designed to galvanize the community into action.",
  garnish: "She added a sprig of parsley to garnish the dish.",
  garrison: "The soldiers stationed at the garrison defended the border.",
  genealogy: "She traced her family genealogy back five generations.",
  genesis: "The genesis of the project began with a simple idea.",
  genocide: "The world must work to prevent genocide wherever it occurs.",
  genteel: "The genteel lady hosted an elegant afternoon tea.",
  germane: "Only germane information should be included in the report.",
  gestation: "The gestation period for elephants is nearly two years.",
  grandiose: "The grandiose plan called for a massive new stadium.",
  gratuitous: "The movie contained gratuitous violence that seemed unnecessary.",
  gregarious: "The gregarious student made friends with everyone.",
  grievance: "She filed a formal grievance with the human resources department.",
  grotesque: "The grotesque mask frightened the children at Halloween.",
  guile: "He used guile rather than force to achieve his goals.",
  habitual: "His habitual tardiness frustrated his coworkers.",
  hallmark: "Attention to detail is the hallmark of quality craftsmanship.",
  haphazard: "The papers were arranged in a haphazard pile on the desk.",
  harbinger: "The first robin is often seen as a harbinger of spring.",
  haughty: "Her haughty attitude made it hard to get along with her.",
  hedonism: "The philosophy of hedonism prioritizes the pursuit of pleasure.",
  heresy: "Questioning the established theory was considered heresy.",
  hermit: "The hermit lived alone in a cabin deep in the woods.",
  heterogeneous: "The class was a heterogeneous mix of students from many backgrounds.",
  hindrance: "The bad weather was a hindrance to our travel plans.",
  homogeneous: "The mixture should be smooth and homogeneous.",
  humanitarian: "The humanitarian organization provided aid after the earthquake.",
  hypothetical: "The professor posed a hypothetical question for discussion.",
  iconoclast: "The iconoclast challenged every traditional belief.",
  idiosyncratic: "Her idiosyncratic cooking style produced unique and delicious dishes.",
  ignominious: "The team suffered an ignominious defeat in the first round.",
  illicit: "The police cracked down on illicit activities in the area.",
  illuminate: "The candles helped illuminate the dark hallway.",
  illustrious: "The school has an illustrious history of academic excellence.",
  immaculate: "The house was kept in immaculate condition.",
  imminent: "The dark clouds signaled that rain was imminent.",
  immunity: "The vaccine provides immunity against the disease.",
  impair: "Loud noise over time can impair your hearing.",
  impartial: "The referee must remain impartial throughout the game.",
  impeach: "Congress has the power to impeach the president.",
  impeccable: "Her manners at the formal dinner were impeccable.",
  impediment: "The lack of funding was a major impediment to the project.",
  imperative: "It is imperative that we finish the report by Friday.",
  impervious: "The waterproof jacket was impervious to rain.",
  implausible: "The alibi seemed implausible to the detective.",
  implicit: "There was an implicit understanding between the two friends.",
  impromptu: "She delivered an impromptu speech at the gathering.",
  impudent: "The impudent remark earned the student a trip to the office.",
  inadvertent: "The typo was an inadvertent mistake in the final report.",
  incandescent: "The incandescent bulb cast a warm glow in the room.",
  incarcerate: "The court decided to incarcerate the convicted criminal.",
  incendiary: "The incendiary device was safely defused by the bomb squad.",
  incessant: "The incessant barking of the dog kept everyone awake.",
  incite: "It is against the law to incite a riot.",
  inclination: "She has a natural inclination toward the arts.",
  incoherent: "His speech was so rapid it became almost incoherent.",
  incomprehensible: "The ancient script was nearly incomprehensible.",
  inconclusive: "The test results were inconclusive and needed further study.",
  inconspicuous: "He tried to remain inconspicuous at the back of the room.",
  incorrigible: "The incorrigible troublemaker was sent to the office again.",
  increment: "Salaries increase by a small increment each year.",
  incriminate: "The evidence found at the scene could incriminate the suspect.",
  indemnity: "The insurance policy includes indemnity for property damage.",
  indescribable: "The beauty of the sunset was truly indescribable.",
  indictment: "The grand jury issued an indictment against the suspect.",
  indigenous: "The indigenous plants thrived in the local climate.",
  indignant: "She was indignant at the unfair accusation.",
  indiscriminate: "The storm caused indiscriminate damage across the region.",
  indispensable: "The dictionary is an indispensable tool for any writer.",
  individualistic: "Her individualistic style set her apart from the crowd.",
  induce: "The warm milk was supposed to induce sleep.",
  inept: "The inept performance drew criticism from the reviewers.",
  inertia: "The heavy object's inertia made it difficult to push.",
  infallible: "No system of measurement is completely infallible.",
  infatuate: "He was infatuated with the idea of traveling the world.",
  infiltrate: "The spy managed to infiltrate the enemy organization.",
  inflammatory: "The inflammatory remarks added fuel to the argument.",
  ingenious: "The inventor came up with an ingenious solution.",
  ingenuity: "Her ingenuity impressed the judges at the science fair.",
  ingratiate: "He tried to ingratiate himself with the new boss.",
  inherent: "There are inherent risks in any outdoor adventure.",
  inhibit: "Fear can inhibit a person from trying new things.",
  iniquity: "The reformers fought against the iniquity of the old system.",
  innate: "She has an innate ability to connect with people.",
  innocuous: "The innocuous comment was taken out of context.",
  innumerable: "There are innumerable stars in the galaxy.",
  insatiable: "Her insatiable curiosity drove her to explore every topic.",
  insidious: "The insidious disease spread silently through the population.",
  insinuate: "She didn't mean to insinuate that he was lying.",
  instigate: "One student tried to instigate a food fight in the cafeteria.",
  insufferable: "The insufferable heat wave lasted for over a week.",
  insurgent: "The insurgent forces clashed with the national army.",
  insurmountable: "What seemed like an insurmountable obstacle was eventually overcome.",
  intangible: "Trust is an intangible but essential part of teamwork.",
  integral: "Practice is an integral part of learning any instrument.",
  intercede: "The counselor was asked to intercede in the dispute.",
  interdependent: "The two species are interdependent for survival.",
  intermittent: "The intermittent rain showers lasted all day.",
  interpersonal: "Good interpersonal skills are valued in the workplace.",
  intersperse: "She liked to intersperse jokes throughout her presentations.",
  intricate: "The intricate design on the vase was done by hand.",
  intrinsic: "Hard work has an intrinsic value beyond any reward.",
  intuitive: "The software has an intuitive design that is easy to learn.",
  inundate: "The office was inundated with phone calls after the announcement.",
  invariably: "She invariably arrives five minutes before everyone else.",
  invoke: "The lawyer tried to invoke a rarely used clause.",
  irascible: "The irascible coach yelled from the sidelines.",
  ironic: "It was ironic that the fire station itself caught fire.",
  irreconcilable: "Their irreconcilable differences ended the partnership.",
  irrelevant: "The comment was completely irrelevant to the discussion.",
  irrevocable: "Once submitted, the decision is final and irrevocable.",
  itinerary: "She planned a detailed itinerary for the vacation.",
  jeopardize: "A poor decision could jeopardize the entire project.",
  judicious: "A judicious use of resources will make the budget last.",
  jurisprudence: "The scholar specialized in constitutional jurisprudence.",
  juxtapose: "The artist chose to juxtapose light and dark in the painting.",
  kinetic: "The kinetic energy of the ball increased as it rolled downhill.",
  knowledgeable: "The guide was very knowledgeable about local history.",
  labyrinth: "The garden was designed as a labyrinth of hedges.",
  lackluster: "The team gave a lackluster performance in the first half.",
  lament: "She wrote a lament for the loss of the old building.",
  languid: "The languid summer afternoon was perfect for a nap.",
  latent: "The student had a latent talent for music.",
  laudable: "Volunteering at the shelter is a laudable effort.",
  lethargy: "The hot weather caused a general sense of lethargy.",
  leverage: "She used her experience to leverage a better position.",
  liaison: "The teacher served as a liaison between the school and parents.",
  lighthearted: "The lighthearted comedy was perfect for a family movie night.",
  linger: "The aroma of fresh bread seemed to linger in the kitchen.",
  liquidate: "The company was forced to liquidate its remaining assets.",
  litigate: "They decided to litigate the matter in court.",
  livelihood: "Farming is the main source of livelihood in the village.",
  lucrative: "The investment turned out to be extremely lucrative.",
  luminous: "The luminous moon lit up the entire landscape.",
  magnanimous: "The magnanimous winner congratulated every opponent.",
  malevolent: "The villain in the story had a malevolent grin.",
  malfeasance: "The official was charged with malfeasance in office.",
  malice: "She bore no malice toward those who disagreed with her.",
  malleable: "Gold is a highly malleable metal.",
  mandate: "The new law gave the agency a mandate to act.",
  manifesto: "The group published a manifesto outlining their beliefs.",
  manipulate: "It is wrong to manipulate people for personal gain.",
  maritime: "The coastal city has a rich maritime heritage.",
  meander: "The river began to meander slowly through the valley.",
  mediocre: "The food at the restaurant was mediocre at best.",
  melancholy: "The grey skies cast a feeling of melancholy over the town.",
  melodramatic: "Her melodramatic reaction to the small problem seemed excessive.",
  metamorphosis: "The caterpillar undergoes a metamorphosis to become a butterfly.",
  meticulous: "She kept meticulous records of every expense.",
  milieu: "The novel captured the cultural milieu of the 1920s.",
  mitigate: "Planting trees can help mitigate the effects of climate change.",
  modicum: "Even a modicum of effort would have made a difference.",
  momentous: "The signing of the treaty was a momentous occasion.",
  monopolize: "She tried not to monopolize the conversation.",
  morale: "The victory boosted the team's morale considerably.",
  moratorium: "The city placed a moratorium on new construction.",
  mundane: "She found the mundane chores of daily life boring.",
  munificent: "The munificent patron donated millions to the arts.",
  nefarious: "The detective uncovered the criminal's nefarious plan.",
  negligent: "The company was found negligent in maintaining safety standards.",
  nonchalant: "He tried to appear nonchalant despite being nervous.",
  noncommittal: "She gave a noncommittal shrug when asked about her plans.",
  nostalgia: "The old photographs filled her with warm nostalgia.",
  notoriety: "The scandal brought unwanted notoriety to the company.",
  novice: "The novice skier stayed on the beginner slopes.",
  nuance: "The poem's subtle nuance revealed deeper meaning upon rereading.",
  nullify: "The error could nullify the results of the experiment.",
  oblivious: "He was oblivious to the noise around him while reading.",
  obnoxious: "The obnoxious behavior of the rude guest ruined dinner.",
  obsolete: "The old technology became obsolete within a few years.",
  obstinate: "The obstinate child refused to eat his vegetables.",
  opaque: "The opaque curtains blocked all sunlight from the room.",
  opportunist: "The opportunist seized the chance to invest early.",
  optimism: "Her optimism helped the team believe they could win.",
  opulent: "The opulent ballroom was decorated with gold and crystal.",
  orchestrate: "She helped orchestrate the entire fundraising event.",
  ornamental: "The ornamental fountain was the centerpiece of the garden.",
  orthodox: "He followed orthodox methods of teaching mathematics.",
  ostensible: "The ostensible reason for the visit was to deliver a gift.",
  ostentatious: "The ostentatious display of wealth made some guests uncomfortable.",
  overhaul: "The old car needed a complete engine overhaul.",
  oversight: "The error was an unfortunate oversight in the report.",
  pacifist: "The pacifist believed that all conflicts should be resolved peacefully.",
  palatable: "The chef made even the simplest vegetables palatable.",
  palpable: "The excitement in the stadium was almost palpable.",
  paradigm: "The discovery led to a shift in the scientific paradigm.",
  paradox: "It is a paradox that we often learn the most from our failures.",
  paramount: "Student safety is of paramount importance.",
  parody: "The comedian performed a hilarious parody of the famous song.",
  partisan: "The debate became heated and deeply partisan.",
  patriarch: "The patriarch of the family led the holiday gathering.",
  patronize: "She refused to patronize a store with poor customer service.",
  pedigree: "The champion dog had an impressive pedigree.",
  penchant: "She has a penchant for collecting vintage records.",
  penitent: "The penitent student apologized sincerely for the disruption.",
  perennial: "The perennial flower comes back every spring without replanting.",
  perfunctory: "He gave a perfunctory nod without really paying attention.",
  peripheral: "She noticed movement in her peripheral vision.",
  perjury: "Lying under oath in court is the crime of perjury.",
  permeate: "The smell of coffee seemed to permeate the entire building.",
  perpetuate: "We must not perpetuate harmful stereotypes.",
  perseverance: "Her perseverance through difficulties led to success.",
  pertinent: "Please include only pertinent details in the summary.",
  pervasive: "The influence of technology is pervasive in modern life.",
  philanthropist: "The philanthropist donated millions to education.",
  photosynthesis: "Plants use photosynthesis to convert sunlight into energy.",
  placate: "She offered a compromise to placate the angry customer.",
  platitude: "His speech was full of empty platitudes and no substance.",
  plight: "The documentary highlighted the plight of the refugees.",
  polarize: "The controversial topic tended to polarize the audience.",
  posthumous: "The artist received a posthumous award for her contributions.",
  pragmatic: "She took a pragmatic approach to solving the problem.",
  precarious: "The vase sat in a precarious position on the edge of the shelf.",
  precedent: "The court ruling set a precedent for future cases.",
  precipitate: "Heavy rain can precipitate landslides on steep hills.",
  precocious: "The precocious child began reading at the age of three.",
  precursor: "Dark clouds are often a precursor to a thunderstorm.",
  predatory: "The predatory hawk circled high above the field.",
  predicament: "She found herself in a difficult predicament.",
  predominant: "Blue was the predominant color in the painting.",
  preeminent: "She is the preeminent expert in her field of study.",
  preempt: "The special news broadcast will preempt the regular show.",
  prelude: "The short musical piece served as a prelude to the symphony.",
  premeditate: "The crime appeared to be carefully premeditated.",
  prerogative: "It is the manager's prerogative to approve the schedule.",
  prevalent: "Allergies are more prevalent during the spring season.",
  procrastinate: "Try not to procrastinate on important assignments.",
  prodigal: "The prodigal son returned home after many years away.",
  prodigy: "The young prodigy performed piano concertos at age seven.",
  proficient: "She became proficient in Spanish after living abroad.",
  prognosis: "The doctor gave an optimistic prognosis for her recovery.",
  proliferate: "Wildflowers proliferate in the meadow every spring.",
  prolific: "The prolific author published twenty novels in ten years.",
  propensity: "He has a propensity for arriving early to every meeting.",
  proponent: "She is a strong proponent of renewable energy.",
  proprietary: "The company developed proprietary software for the project.",
  prosperity: "Years of hard work brought prosperity to the community.",
  protagonist: "The protagonist of the novel faced many challenges.",
  protract: "The dispute threatened to protract the negotiations for months.",
  provincial: "The provincial town offered a quiet escape from city life.",
  provocative: "The article raised several provocative questions.",
  proximity: "The school is in close proximity to the library.",
  prudent: "It is prudent to save money for unexpected expenses.",
  pugnacious: "The pugnacious boxer was ready for every round.",
  punctilious: "She was punctilious about following every rule.",
  punitive: "The committee imposed punitive measures for the violation.",
  quandary: "She was in a quandary about which college to attend.",
  quintessential: "Apple pie is the quintessential American dessert.",
  ramification: "The ramification of the decision affected the entire school.",
  rampant: "Rumors were rampant after the surprise announcement.",
  rationale: "She explained the rationale behind her decision clearly.",
  rebuke: "The coach issued a sharp rebuke to the late player.",
  recalcitrant: "The recalcitrant student refused to follow directions.",
  reciprocal: "The agreement was based on reciprocal respect.",
  recluse: "The recluse lived alone in a cabin in the mountains.",
  reconnaissance: "The scouts conducted reconnaissance of the area.",
  redundant: "The additional check made the first one redundant.",
  referendum: "The citizens voted in a referendum on the issue.",
  refurbish: "They plan to refurbish the old theater downtown.",
  reimburse: "The company will reimburse you for travel expenses.",
  reiterate: "Let me reiterate the importance of arriving on time.",
  relegate: "The losing team was relegated to a lower division.",
  relinquish: "She was reluctant to relinquish control of the project.",
  reminiscent: "The melody was reminiscent of a song from her childhood.",
  remorse: "He felt deep remorse for his careless words.",
  renovate: "They hired a contractor to renovate the kitchen.",
  repercussion: "The decision had a serious repercussion for the team.",
  replenish: "She went to the store to replenish the household supplies.",
  reprehensible: "Cheating on an exam is reprehensible behavior.",
  reprimand: "The employee received a formal reprimand for misconduct.",
  reproach: "His behavior was beyond reproach.",
  repudiate: "She chose to repudiate the false accusations publicly.",
  requisite: "Hard work is a requisite for success.",
  resilience: "The community showed incredible resilience after the storm.",
  resonate: "Her words seemed to resonate with the entire audience.",
  restitution: "The court ordered the company to pay restitution.",
  resurgence: "There has been a resurgence of interest in handmade crafts.",
  retaliate: "The team vowed not to retaliate after the rough play.",
  retribution: "The villain faced swift retribution for his crimes.",
  retrospect: "In retrospect, the decision turned out to be the right one.",
  rigorous: "The training program is extremely rigorous.",
  rudimentary: "She had only a rudimentary understanding of the topic.",
  ruthless: "The ruthless competition pushed each team to their limits.",
  sacrosanct: "The right to free speech is considered sacrosanct.",
  sagacious: "The sagacious leader made wise decisions under pressure.",
  sanction: "The committee voted to sanction the new program.",
  sanctuary: "The wildlife sanctuary protects endangered animals.",
  scrupulous: "She was scrupulous about checking every detail.",
  scrutinize: "The inspector will scrutinize every part of the building.",
  seclusion: "She enjoyed the seclusion of the quiet mountain cabin.",
  sedentary: "A sedentary lifestyle can lead to health problems.",
  sentiment: "The card expressed a beautiful sentiment of gratitude.",
  serendipity: "Finding the rare book at the garage sale was pure serendipity.",
  servitude: "The law abolished involuntary servitude.",
  skepticism: "Her claims were met with healthy skepticism.",
  solicit: "Volunteers went door to door to solicit donations.",
  solidarity: "The workers showed solidarity by walking out together.",
  solitude: "She found peace in the solitude of the forest.",
  speculate: "Experts began to speculate about the cause of the event.",
  sporadic: "Sporadic showers are expected throughout the afternoon.",
  stagnant: "The stagnant water in the pond attracted mosquitoes.",
  staunch: "He was a staunch supporter of environmental protection.",
  steadfast: "She remained steadfast in her commitment to the cause.",
  stigmatize: "We must not stigmatize people for seeking help.",
  stipulate: "The contract will stipulate the terms of the agreement.",
  stoic: "He remained stoic despite the painful news.",
  straightforward: "The instructions were straightforward and easy to follow.",
  stringent: "The factory follows stringent safety guidelines.",
  subjective: "Art appreciation is often subjective and personal.",
  subsidize: "The government will subsidize the cost of public transit.",
  substantiate: "She needed evidence to substantiate her claim.",
  subversive: "The banned book was considered subversive by the regime.",
  succinct: "Her succinct summary captured all the key points.",
  succumb: "He did not succumb to the temptation of cheating.",
  superficial: "The wound was superficial and required no stitches.",
  superfluous: "The extra decorations seemed superfluous and unnecessary.",
  suppress: "She tried to suppress a yawn during the long meeting.",
  surpass: "Her test score managed to surpass the class average.",
  susceptible: "Young children are more susceptible to colds in winter.",
  sycophant: "The sycophant always agreed with the boss to gain favor.",
  synonymous: "The city's name is synonymous with great music.",
  synthesis: "The research paper required a synthesis of multiple sources.",
  tangible: "The new park was a tangible benefit for the neighborhood.",
  tantalize: "The aroma from the bakery was designed to tantalize passersby.",
  tedious: "Filling out the long form was a tedious process.",
  temperament: "Her calm temperament made her an excellent mediator.",
  tenacious: "The tenacious climber refused to give up on the summit.",
  tentative: "They made tentative plans for the weekend.",
  terminate: "The airline had to terminate the flight due to weather.",
  testament: "The beautiful garden was a testament to years of hard work.",
  therapeutic: "The soothing music had a therapeutic effect on patients.",
  totalitarian: "The totalitarian government controlled every aspect of life.",
  transcend: "Great art has the power to transcend cultural boundaries.",
  transformative: "The experience was truly transformative for the students.",
  transgression: "He apologized for his transgression and sought forgiveness.",
  transient: "The population of the resort town is largely transient.",
  travesty: "The unfair verdict was considered a travesty of justice.",
  treacherous: "The treacherous mountain pass was covered in ice.",
  tumultuous: "The rally became tumultuous as the crowd grew larger.",
  tyranny: "The people rose up to overthrow the tyranny.",
  ubiquitous: "Smartphones have become ubiquitous in modern life.",
  ultimatum: "She gave him an ultimatum to finish by the deadline.",
  unanimous: "The decision was unanimous among all the members.",
  unconscionable: "The price increase was considered unconscionable.",
  undermine: "Gossip can undermine trust among friends.",
  underscore: "The incident serves to underscore the need for better safety.",
  unilateral: "The country made a unilateral decision without consulting allies.",
  unscrupulous: "The unscrupulous dealer sold counterfeit goods.",
  uphold: "The court voted to uphold the original ruling.",
  usurp: "The general attempted to usurp power from the government.",
  utilitarian: "The design was utilitarian, focusing on function over beauty.",
  validate: "The study aimed to validate the results of the previous experiment.",
  vanquish: "The hero set out to vanquish the dragon.",
  venerable: "The venerable institution has been around for over a century.",
  verbose: "His verbose explanations made the simple topic confusing.",
  vernacular: "She spoke in the local vernacular of the region.",
  versatile: "A versatile chef can cook any type of cuisine.",
  vindicate: "The new evidence was enough to vindicate the suspect.",
  volatile: "The volatile market made investors nervous.",
  voracious: "She was a voracious reader who finished a book every week.",
  waive: "The school decided to waive the entrance fee for the event.",
  wholeheartedly: "She wholeheartedly supported the new community project.",
  wholesome: "The family enjoyed a wholesome meal of fresh vegetables.",
  wield: "The knight learned to wield a sword with great skill.",
  zealous: "The zealous volunteer worked tirelessly for the cause.",
};

export default ADVANCED_SENTENCES;
