/**
 * Curated sentences for common words (level 1).
 * Each sentence uses the word in a clear, meaningful context so
 * the listener can identify the word even when TTS is unclear.
 */
const COMMON_SENTENCES: Record<string, string> = {
  the: "The dog ran across the yard.",
  and: "She likes cats and dogs.",
  is: "The sky is clear today.",
  it: "Give it to me, please.",
  to: "She went to the store.",
  in: "The cat is hiding in the box.",
  that: "I believe that you are correct.",
  was: "She was happy to see her friend.",
  for: "This gift is for you.",
  on: "The book is on the table.",
  are: "The children are playing outside.",
  with: "I went to the park with my sister.",
  they: "They are coming to visit us tomorrow.",
  be: "Try to be kind to everyone you meet.",
  at: "We will meet at the library after school.",
  one: "I only need one more chance.",
  have: "I have a new bicycle.",
  this: "This is the best day of my life.",
  from: "The letter came from my grandmother.",
  or: "Would you like tea or coffee?",
  had: "She had a wonderful time at the party.",
  by: "The book was written by a famous author.",
  not: "I am not going to the party.",
  but: "I wanted to go, but it started raining.",
  what: "What time does the movie start?",
  all: "All the students passed the test.",
  were: "The flowers were blooming in the garden.",
  we: "We decided to walk to the park.",
  when: "Tell me when you are ready to leave.",
  your: "Is this your backpack?",
  can: "She can run faster than anyone in class.",
  said: "He said hello to his neighbor.",
  there: "Put the book over there on the table.",
  each: "Each student received a gold star.",
  which: "Which color do you prefer?",
  do: "What do you want for dinner tonight?",
  how: "How did you solve that difficult puzzle?",
  if: "Let me know if you need any help.",
  will: "I will finish my homework after dinner.",
  up: "The balloon floated up into the sky.",
  other: "The other team scored the winning goal.",
  about: "Tell me about your favorite vacation.",
  out: "The children went out to play after lunch.",
  many: "There are many stars in the night sky.",
  then: "First eat your dinner, then have dessert.",
  them: "Please give them their homework assignments.",
  these: "These cookies taste absolutely delicious.",
  so: "I was tired, so I went to bed.",
  some: "Would you like some water?",
  her: "I gave her a birthday present.",
  would: "I would love to help you.",
  make: "Let's make a sandcastle at the beach.",
  like: "I would like a glass of lemonade.",
  him: "Give the book to him.",
  into: "The rabbit hopped into its burrow.",
  time: "What time is it right now?",
  has: "She has a beautiful singing voice.",
  look: "Look at the rainbow in the sky.",
  two: "I have two sisters.",
  more: "May I have some more soup, please?",
  go: "Let's go to the park this afternoon.",
  see: "I can see the mountains from here.",
  no: "There is no milk left.",
  way: "Which way should we go?",
  could: "She could hear the music from outside.",
  my: "This is my favorite song.",
  than: "She runs faster than her brother.",
  first: "She was the first person to arrive.",
  been: "I have been waiting for an hour.",
  call: "Please call me when you get home.",
  who: "The girl who lives next door is friendly.",
  its: "The dog wagged its tail happily.",
  now: "We need to leave right now.",
  find: "I need to find my lost keys.",
  long: "The river is very long and winding.",
  down: "The ball rolled down the hill.",
  day: "It was a beautiful sunny day.",
  did: "She did an amazing job on her project.",
  get: "I need to get a new pair of shoes.",
  come: "Please come to my birthday party.",
  made: "She made a beautiful painting.",
  may: "May I please have another cookie?",
  part: "This is the best part of the story.",
  over: "The plane flew over the mountains.",
  new: "She drove her new car to work.",
  after: "We went for ice cream after the movie.",
  back: "Put the toys back in the box.",
  little: "The little kitten played with a ball of yarn.",
  only: "She is the only person who knows the secret.",
  round: "The Earth is round like a ball.",
  man: "The man walked his dog every morning.",
  year: "This has been a wonderful year.",
  came: "She came home early from school.",
  show: "Can you show me how to tie a knot?",
  every: "She practices the piano every day.",
  good: "You did a really good job today.",
  me: "Can you help me carry these bags?",
  give: "Please give me a glass of water.",
  our: "This is our new house.",
  under: "The cat is hiding under the bed.",
  name: "Please write your name at the top of the page.",
  very: "She was very happy with the results.",
  just: "I just finished reading a great book.",
  know: "I know the answer to that question.",
  take: "Please take your shoes off at the door.",
  people: "Many people came to watch the parade.",
  boy: "The boy climbed the tall oak tree.",
  great: "She did a great job on the project.",
  help: "Can you help me with my homework?",
  through: "The train passed through the tunnel.",
  much: "Thank you very much for your help.",
  line: "Please stand in a straight line.",
  before: "Wash your hands before eating dinner.",
  right: "Turn right at the traffic light.",
  too: "He wanted to come too.",
  mean: "What does that word mean?",
  old: "The old house had a beautiful garden.",
  any: "Do you have any questions about the lesson?",
  same: "We go to the same school.",
  tell: "Please tell me a bedtime story.",
  also: "She plays soccer and also runs track.",
  ask: "Don't be afraid to ask for help.",
  small: "The small bird sat on the branch.",
  end: "We walked to the end of the trail.",
  put: "Please put your coat in the closet.",
  home: "She arrived home just before dark.",
  read: "I read three books last month.",
  hand: "She raised her hand to answer the question.",
  big: "The elephant is the biggest land animal.",
  high: "The eagle flew high above the valley.",
  last: "This is the last piece of cake.",
  never: "I have never been to Europe before.",
  us: "The teacher asked us to open our books.",
  left: "Turn left at the next intersection.",
  live: "We live in a small town near the coast.",
  girl: "The girl scored the winning goal.",
  house: "They painted the house bright yellow.",
  world: "She traveled around the world in a year.",
  run: "He likes to run in the park every morning.",
  own: "She wants to own a bookshop someday.",
  say: "What did you say just now?",
  she: "She is the tallest girl in the class.",
  here: "Come sit over here with me.",
  why: "Tell me why the sky is blue.",
  let: "Let me help you carry that heavy box.",
  use: "You can use my pen if you need one.",
  still: "The lake was perfectly still at dawn.",
  should: "You should always wear your seatbelt.",
  might: "She might arrive late tonight.",
  went: "They went hiking in the mountains.",
  off: "Please turn off the lights when you leave.",
  head: "She nodded her head in agreement.",
  play: "The children love to play in the park.",
  want: "I want to learn how to play guitar.",
  start: "Classes start at eight in the morning.",
  set: "She set the table for dinner.",
  need: "I need a glass of water.",
  keep: "Keep your room clean and tidy.",
  try: "Always try your best on every test.",
  most: "This is the most beautiful sunset I have seen.",
  think: "I think we should leave early tomorrow.",
  kind: "She is a very kind and generous person.",
  must: "You must finish your homework before playing.",
  work: "She goes to work every weekday morning.",
  place: "This park is my favorite place to relax.",
  even: "She didn't even notice the surprise party.",
  such: "It was such a lovely evening.",
  turn: "Please turn to page twenty in your textbook.",
  does: "What does your father do for a living?",
  got: "She got a perfect score on the spelling test.",
  open: "Please open the window for some fresh air.",
  stop: "The bus will stop at the next corner.",
  move: "Help me move this heavy table to the corner.",
  hard: "The math test was really hard.",
  thing: "The first thing I do each morning is stretch.",
  near: "The school is near the library.",
  school: "She walks to school every morning.",
  city: "The city has a beautiful skyline at night.",
  book: "I borrowed a book from the library.",
  between: "The park is between the school and the store.",
  father: "My father taught me how to ride a bicycle.",
  mother: "Her mother baked cookies for the class.",
  tree: "The tall tree provided shade in the summer.",
  land: "The airplane will land in about ten minutes.",
  side: "Please move to the other side of the room.",
  point: "She made an excellent point during the discussion.",
  story: "He told us a funny story about his trip.",
  feet: "She stood on her feet for hours.",
  state: "Texas is the second largest state in America.",
  next: "The next train leaves in twenty minutes.",
  walk: "Let's walk along the beach at sunset.",
  close: "Please close the door when you leave.",
  night: "The stars come out at night.",
  real: "Is that painting real or a forgery?",
  life: "She lived a long and happy life.",
  few: "Only a few tickets are left for the concert.",
  north: "The compass needle always points north.",
  eat: "We eat dinner together as a family every night.",
  food: "The food at the restaurant was delicious.",
  water: "Please drink plenty of water on hot days.",
  once: "Once upon a time there was a brave princess.",
  white: "The white snow covered the whole mountain.",
  black: "She wore a black dress to the concert.",
  red: "She wore a bright red dress.",
  blue: "The sky is a brilliant blue today.",
  green: "The green grass sparkled with morning dew.",
  yes: "She said yes when he asked her to dance.",
  again: "Can you please say that again?",
  three: "I have three pencils in my backpack.",
  four: "There are four seasons in a year.",
  five: "She counted five ducks in the pond.",
  six: "The store closes at six in the evening.",
  seven: "There are seven days in a week.",
  eight: "There are eight planets in our solar system.",
  nine: "The baby is nine months old today.",
  ten: "She counted to ten before opening her eyes.",
  best: "This is the best pizza I have ever tasted.",
  both: "Both children received a prize.",
  car: "She drives her car to work every day.",
  dog: "The dog chased the ball across the yard.",
  cat: "The cat slept peacefully on the windowsill.",
  fish: "We caught a big fish at the lake.",
  bird: "A bird built a nest in our apple tree.",
  door: "Someone is knocking at the front door.",
  room: "Her room was decorated with colorful posters.",
  cold: "The winter air was cold and crisp.",
  hot: "Be careful, the stove is very hot.",
  sun: "The sun rises in the east.",
  moon: "The full moon lit up the night sky.",
  light: "Turn on the light so we can see better.",
  dark: "The forest was dark and mysterious at night.",
  eye: "She has a beautiful blue eye color.",
  face: "His face lit up with a huge smile.",
  cut: "Be careful not to cut your finger with the knife.",
  paper: "Write your answer on a piece of paper.",
  map: "Use the map to find the treasure.",
  top: "The cat climbed to the top of the tree.",
  hold: "Please hold the door open for me.",
  fast: "The cheetah is the fastest animal on land.",
  far: "How far is it to the nearest gas station?",
  full: "The glass is full of orange juice.",
  hear: "I can hear the birds singing.",
  sing: "She loves to sing in the school choir.",
  sit: "Please sit down in your chair.",
  stand: "Stand up straight when the teacher enters.",
  fly: "Birds fly south for the winter.",
  sleep: "I need to get more sleep tonight.",
  bring: "Please bring a pencil to class tomorrow.",
  draw: "She likes to draw pictures of animals.",
  fall: "Be careful not to fall on the slippery ice.",
  pull: "Pull the door handle to open it.",
  push: "Push the button to start the machine.",
  grow: "Plants grow toward the sunlight.",
  jump: "The frog can jump very high.",
  laugh: "The funny movie made everyone laugh.",
  pick: "Pick your favorite color from the choices.",
  ride: "She loves to ride her bicycle in the park.",
  write: "Please write your name on the form.",
  buy: "I need to buy some groceries.",
  clean: "Please clean your room before dinner.",
  drink: "Drink plenty of water during exercise.",
  carry: "Help me carry these heavy bags upstairs.",
  done: "Are you done with your homework yet?",
  warm: "The warm sunshine felt wonderful.",
  wish: "I wish I could visit the ocean.",
  upon: "Once upon a time there lived a wise king.",
  today: "Today is a perfect day for a picnic.",
  together: "Let's work together to solve this problem.",
  please: "Please pass the salt and pepper.",
  thank: "I want to thank you for your kindness.",
  funny: "The clown told a very funny joke.",
  happy: "The children were happy to see the snow.",
  love: "I love spending time with my family.",
  friend: "My best friend lives next door to me.",
  rain: "The rain fell steadily all afternoon.",
  snow: "The snow covered the entire playground.",
  wind: "The strong wind blew the leaves everywhere.",
  baby: "The baby smiled and waved her tiny hands.",
  ball: "Throw the ball to the first baseman.",
  bed: "She made her bed neatly every morning.",
  boat: "The boat sailed smoothly across the lake.",
  box: "Put the toys in the big cardboard box.",
  bus: "The school bus arrives at seven thirty.",
  cake: "She baked a chocolate cake for his birthday.",
  cup: "Would you like a cup of hot tea?",
  farm: "The farm has chickens, cows, and horses.",
  fire: "The fire crackled warmly in the fireplace.",
  game: "We played a fun board game after dinner.",
  hat: "She wore a straw hat to block the sun.",
  hill: "They rolled down the grassy hill laughing.",
  leg: "He hurt his leg while playing soccer.",
  milk: "Pour some cold milk into the glass.",
  pet: "She has a pet rabbit named Clover.",
  ring: "She wore a diamond ring on her finger.",
  road: "The road stretched for miles ahead.",
  rock: "He skipped a flat rock across the pond.",
  sea: "The ship sailed across the sea.",
  seed: "Plant the seed in the soil and water it daily.",
  star: "The brightest star in the sky is beautiful.",
  table: "Set the dishes on the kitchen table.",
  train: "The train arrived at the station on time.",
  toy: "The child played with a favorite toy.",
  wall: "She hung a painting on the wall.",
  window: "Open the window to let in some fresh air.",
  yard: "The children played tag in the backyard.",
  add: "Please add your name to the sign-up sheet.",
  age: "What age were you when you learned to swim?",
  air: "The morning air was fresh and cool.",
  am: "I am going to the store this afternoon.",
  an: "She ate an apple for a snack.",
  art: "The museum has a wonderful art collection.",
  bad: "The bad weather forced us to stay inside.",
  bag: "She packed her bag for the school trip.",
  bit: "May I have a little bit of sugar?",
  brown: "The brown bear searched for food by the river.",
  child: "Every child deserves a good education.",
  class: "The whole class went on a field trip.",
  cover: "Use a blanket to cover yourself at night.",
  cross: "Look both ways before you cross the street.",
  cry: "The baby began to cry when he was hungry.",
  deep: "The swimming pool has a very deep end.",
  dry: "Use the towel to dry your hands.",
  ear: "She whispered a secret in my ear.",
  east: "The sun rises in the east every morning.",
  else: "Is there anything else you would like?",
  ever: "Have you ever visited a national park?",
  feel: "I feel much better after a good sleep.",
  fill: "Please fill the glass with water.",
  fine: "The weather today is just fine.",
  flower: "She picked a beautiful flower from the garden.",
  follow: "Follow the path through the woods to the lake.",
  free: "The puppies are free to a good home.",
  front: "Wait for me at the front of the building.",
  garden: "She planted tomatoes in her garden.",
  glass: "He poured water into a tall glass.",
  gold: "The pirates were searching for buried gold.",
  grass: "The children played on the soft green grass.",
  ground: "The ball hit the ground and bounced.",
  group: "A group of friends went to the movies.",
  half: "She ate half of the sandwich for lunch.",
  happen: "What would happen if it rained tomorrow?",
  heavy: "The suitcase was too heavy to carry alone.",
  hope: "I hope the weather is nice for the picnic.",
  horse: "She learned to ride a horse at camp.",
  hour: "The meeting lasted an hour.",
  hundred: "There are one hundred cents in a dollar.",
  idea: "She had a brilliant idea for the science fair.",
  king: "The king ruled the land with great wisdom.",
  knew: "He knew the answer immediately.",
  late: "She was late for school this morning.",
  learn: "You are never too old to learn something new.",
  letter: "She wrote a letter to her pen pal.",
  list: "Make a list of things you need from the store.",
  listen: "Please listen carefully to the instructions.",
  low: "The airplane flew low over the trees.",
  mark: "Put a mark next to the correct answer.",
  miss: "I will miss you while you are on vacation.",
  morning: "I exercise every morning before work.",
  mouth: "She opened her mouth to sing the song.",
  music: "The music at the concert was wonderful.",
  nice: "What a nice day for a walk in the park.",
  notice: "Did you notice the new painting on the wall?",
  number: "Write your phone number on the form.",
  order: "She placed an order for a new computer.",
  page: "Please turn to page twenty-five.",
  pay: "She had to pay for the groceries.",
  picture: "She drew a beautiful picture of a sunset.",
  piece: "May I have a piece of cake?",
  plan: "We need to plan our vacation soon.",
  plant: "She decided to plant flowers in the garden.",
  poor: "The poor man had nothing to eat.",
  power: "The storm knocked out the power for hours.",
  pretty: "The garden was full of pretty flowers.",
  problem: "She solved the math problem in seconds.",
  quick: "The quick brown fox jumped over the lazy dog.",
  quite: "The restaurant was quite busy on Friday night.",
  reach: "She stood on her toes to reach the top shelf.",
  rest: "After a long hike, we sat down to rest.",
  river: "The river flows gently through the valley.",
  save: "Try to save some money every month.",
  second: "She finished the race in second place.",
  seem: "Things are not always what they seem.",
  ship: "The cargo ship sailed across the Atlantic Ocean.",
  short: "The days grow short as winter approaches.",
  simple: "The recipe is simple and easy to follow.",
  slow: "The turtle moved at a very slow pace.",
  south: "Birds fly south for the winter.",
  spring: "The flowers bloom beautifully in the spring.",
  step: "Watch your step on the icy sidewalk.",
  strong: "The strong wind nearly blew off my hat.",
  study: "She went to the library to study for her exam.",
  sure: "Are you sure you locked the front door?",
  swim: "She learned to swim at a young age.",
  talk: "Let's sit down and talk about our plans.",
  teach: "She wants to teach math at a high school.",
  thought: "She thought carefully before answering.",
  true: "Is it true that you won the contest?",
  until: "Wait here until the bus arrives.",
  voice: "She has a lovely singing voice.",
  watch: "He looked at his watch to check the time.",
  week: "The project is due next week.",
  west: "The sun sets in the west every evening.",
  wide: "The river was too wide to swim across.",
  winter: "We enjoy building snowmen in the winter.",
  word: "Can you spell that word for me?",
  young: "The young puppy chased its own tail.",
  alone: "She likes to read alone in the quiet library.",
  along: "We walked along the beach at sunset.",
  already: "She has already finished her homework.",
  animal: "The zoo had every animal you could imagine.",
  answer: "She raised her hand to give the answer.",
  began: "The concert began exactly at seven o'clock.",
  below: "The temperature dropped below freezing last night.",
  body: "Exercise is important for a healthy body.",
  brother: "My brother is two years older than me.",
  certain: "I am certain that I left my keys here.",
  change: "The seasons change four times a year.",
  colour: "What colour is your new bicycle?",
  color: "Her favorite color is bright purple.",
  complete: "Please complete the worksheet by tomorrow.",
  country: "She traveled to a different country for vacation.",
  different: "Each snowflake has a different shape.",
  earth: "The earth travels around the sun once a year.",
  enough: "Do we have enough food for the whole party?",
  example: "The teacher gave an example to explain the rule.",
  family: "Our family gathers for dinner every Sunday.",
  field: "The farmer planted corn in the large field.",
  hands: "Wash your hands before you eat.",
  inside: "Come inside before the storm arrives.",
  large: "The large elephant drank from the river.",
  later: "I will call you back later this evening.",
  leave: "What time do we need to leave for the airport?",
  less: "She asked for less sugar in her tea.",
  money: "He saved enough money to buy a new bicycle.",
  nothing: "There is nothing to worry about.",
  often: "She often reads before going to bed.",
  outside: "The children played outside all afternoon.",
  pass: "Please pass the salt across the table.",
  ready: "Are you ready to go to school?",
  remember: "Do you remember the first day of school?",
  soon: "The movie will start very soon.",
  sound: "I heard a strange sound coming from the attic.",
  those: "Please hand me those books on the shelf.",
  town: "Our small town has only one traffic light.",
  above: "The eagle soared above the mountain tops.",
  almost: "She almost missed the school bus this morning.",
  become: "She wants to become a doctor when she grows up.",
  better: "Practice makes you better at any skill.",
  build: "They plan to build a new playground.",
  care: "She takes good care of her pet hamster.",
  cause: "Heavy rain can cause flooding in low areas.",
  clear: "The instructions were clear and easy to follow.",
  drive: "She learned to drive when she was sixteen.",
  easy: "The first question on the test was easy.",
  fact: "It is a fact that water freezes at zero degrees.",
  form: "Please fill out this form with your information.",
  gave: "She gave her friend a warm hug.",
  gone: "The cookies are all gone already.",
  himself: "He built the birdhouse all by himself.",
  however: "The hike was long; however, the view was worth it.",
  important: "Breakfast is the most important meal of the day.",
  kept: "She kept her promise to visit every weekend.",
  known: "He has known her since they were children.",
  matter: "No matter what happens, I believe in you.",
  mind: "She changed her mind about the movie.",
  taken: "The last piece of pie has been taken.",
  though: "Even though it rained, we still had fun.",
  toward: "She walked toward the school with a smile.",
  whole: "She ate the whole pizza by herself.",
  across: "She walked across the bridge over the river.",
  afternoon: "We spent the whole afternoon at the beach.",
  against: "She leaned against the wall to rest.",
  ago: "That movie came out three years ago.",
  always: "She always arrives five minutes early.",
  among: "She was among the top students in her class.",
  another: "Would you like another glass of lemonade?",
  anyone: "Does anyone know the answer to this question?",
  anything: "Is there anything I can do to help?",
  apple: "She packed a red apple in her lunch bag.",
  arm: "He broke his arm while skateboarding.",
  around: "The children ran around the playground.",
  as: "She is as tall as her mother now.",
  away: "The bird flew away when we got too close.",
  bank: "She deposited her paycheck at the bank.",
  barn: "The red barn sits on top of the hill.",
  basket: "She filled the basket with fresh strawberries.",
  beautiful: "The sunset over the ocean was absolutely beautiful.",
  became: "She practiced every day and became a great pianist.",
  because: "We stayed inside because of the thunderstorm.",
  behind: "The garden is behind the house.",
  being: "She enjoyed being outdoors on a sunny day.",
  believe: "I believe you can accomplish anything.",
  beside: "She sat beside her best friend at lunch.",
  birthday: "She received many gifts on her birthday.",
  bottom: "The treasure was at the bottom of the ocean.",
  bread: "Fresh bread smells wonderful.",
  breakfast: "She always eats a healthy breakfast.",
  bright: "The bright sun made her squint.",
  brought: "She brought cupcakes to share with the class.",
  built: "The house was built over a hundred years ago.",
  busy: "The store was very busy during the holiday sale.",
  called: "She called her friend to make plans.",
  camp: "The children went to summer camp in July.",
  cannot: "You cannot enter without a ticket.",
  catch: "Try to catch the ball with both hands.",
  caught: "The outfielder caught the fly ball easily.",
  center: "The fountain is in the center of the park.",
  chair: "Please take a seat in the blue chair.",
  check: "Let me check if the store is open.",
  chief: "The fire chief gave a talk at our school.",
  children: "The children played happily in the playground.",
  church: "The church has a beautiful stained glass window.",
  circle: "The students sat in a circle on the floor.",
  clay: "She made a bowl out of red clay.",
  clock: "The clock on the wall says it is noon.",
  cloud: "A fluffy white cloud drifted across the sky.",
  coat: "Put on your coat before you go outside.",
  common: "It is common to see deer in this area.",
  company: "She started her own company last year.",
  cook: "He learned to cook from his grandmother.",
  cool: "The cool breeze felt nice on a warm day.",
  corner: "The coffee shop is on the corner of Main Street.",
  course: "She signed up for a cooking course.",
  cow: "The cow grazed peacefully in the meadow.",
  crowd: "A large crowd gathered for the fireworks show.",
  dance: "She loves to dance at every school party.",
  dear: "She began the letter with Dear friend.",
  deer: "A deer stood at the edge of the woods.",
  dig: "The dog tried to dig a hole in the backyard.",
  dinner: "We had pasta and salad for dinner.",
  doctor: "The doctor said she was in perfect health.",
  dream: "Her dream is to travel the world someday.",
  dress: "She wore her favorite dress to the party.",
  drop: "Be careful not to drop the glass.",
  during: "Please remain quiet during the performance.",
  early: "She woke up early to watch the sunrise.",
  energy: "Solar panels convert sunlight into energy.",
  engine: "The car engine started on the first try.",
  enjoy: "I really enjoy reading mystery novels.",
  evening: "We took a peaceful walk in the evening.",
  everyone: "Everyone in the class passed the test.",
  everything: "She packed everything she needed for the trip.",
  except: "Everyone finished the race except one runner.",
  excited: "The children were excited about the field trip.",
  exercise: "Daily exercise helps keep your body healthy.",
  expect: "We expect the package to arrive tomorrow.",
  explain: "Can you explain how this machine works?",
  fat: "The cat grew fat from eating too many treats.",
  favorite: "Chocolate is my favorite flavor of ice cream.",
  felt: "She felt proud after finishing the marathon.",
  fence: "The white fence surrounds the entire garden.",
  fight: "The two teams will fight for the championship.",
  finally: "She finally finished the one-thousand-piece puzzle.",
  finger: "She pointed her finger at the correct answer.",
  finish: "Make sure to finish your work before leaving.",
  floor: "The wooden floor creaked when she walked on it.",
  foot: "She hurt her foot while hiking in the mountains.",
  force: "The force of the wind knocked over the sign.",
  forest: "They went hiking through the dense forest.",
  forgot: "She forgot to bring her umbrella to school.",
  found: "He found a four-leaf clover in the yard.",
  fresh: "The bakery sells fresh bread every morning.",
  fun: "We had so much fun at the amusement park.",
  gift: "She received a lovely gift from her aunt.",
  glad: "I am glad you could come to the party.",
  going: "Where are you going after school today?",
  grade: "She got the highest grade in science class.",
  grand: "They had a grand celebration for the anniversary.",
  grandmother: "My grandmother tells the best stories.",
  grandfather: "My grandfather taught me to play chess.",
  gray: "The gray clouds signaled that rain was coming.",
  grew: "The sunflower grew taller than the fence.",
  guess: "Can you guess how many marbles are in the jar?",
  gun: "The starter fired a gun to begin the race.",
  guy: "That guy over there is my next-door neighbor.",
  hair: "She brushed her long hair every morning.",
  hall: "The students walked through the hall.",
  hang: "Please hang your coat on the hook by the door.",
  he: "He is the fastest runner on the team.",
  heart: "She drew a red heart on the Valentine card.",
  heat: "The heat from the sun warmed the sand.",
  held: "She held the kitten gently in her arms.",
  hello: "She said hello to everyone as she walked in.",
  herself: "She taught herself to play the guitar.",
  his: "He forgot his lunch at home today.",
  hit: "She hit the ball over the fence.",
  hole: "The rabbit disappeared into the hole.",
  holiday: "We are planning a holiday trip to the mountains.",
  huge: "The huge whale surfaced beside the boat.",
  human: "Every human being deserves respect.",
  hungry: "After the long hike, everyone was very hungry.",
  hunt: "The owl went out to hunt at night.",
  hurry: "Hurry up or we will miss the bus.",
  hurt: "She hurt her knee when she fell down.",
  ice: "She put ice in her glass of lemonade.",
  imagine: "Can you imagine living on another planet?",
  inch: "The snail moved forward one inch at a time.",
  include: "The price does not include the tax.",
  indeed: "She is indeed the best player on the team.",
  instead: "She chose juice instead of soda.",
  interest: "The book captured her interest immediately.",
  iron: "She used an iron to press her shirt.",
  island: "They spent their vacation on a tropical island.",
  job: "She got her first job at the age of sixteen.",
  join: "Would you like to join us for dinner?",
  joke: "He told a joke that made everyone laugh.",
  joy: "The puppy brought great joy to the family.",
  key: "She used a key to unlock the front door.",
  kid: "Every kid in the neighborhood came to the party.",
  kill: "The frost can kill the plants in the garden.",
  kitchen: "She helped her mom cook in the kitchen.",
  knee: "He scraped his knee falling off the skateboard.",
  knife: "Use a sharp knife to cut the vegetables.",
  lake: "They went fishing at the lake on Saturday.",
  lay: "Please lay the blanket on the grass.",
  lead: "She will lead the team to victory.",
  leader: "A good leader listens to everyone on the team.",
  least: "At least ten people came to the meeting.",
  led: "He led the group through the forest.",
  lesson: "The piano lesson lasted thirty minutes.",
  lie: "Never tell a lie; always be honest.",
  lift: "Can you help me lift this heavy box?",
  lion: "The lion roared loudly in the savanna.",
  lost: "She lost her favorite bracelet at the park.",
  lot: "There were a lot of people at the concert.",
  loud: "The music was so loud I could barely hear.",
  luck: "Good luck on your test tomorrow.",
  lunch: "We ate lunch under the shade of a big tree.",
  machine: "The washing machine broke down last night.",
  magic: "The magician performed an amazing magic trick.",
  mail: "Did you check the mail today?",
  main: "The main entrance is around the corner.",
  market: "She bought fresh fruit at the farmer's market.",
  master: "He is a master at solving difficult puzzles.",
  match: "The soccer match ended in a tie.",
  maybe: "Maybe we should go to the park tomorrow.",
  measure: "Use a ruler to measure the length of the desk.",
  meat: "We grilled meat for the barbecue.",
  meet: "I will meet you at the coffee shop.",
  member: "She became a member of the science club.",
  men: "The men worked together to build the bridge.",
  mile: "She runs one mile every morning before breakfast.",
  mine: "That red bicycle over there is mine.",
  minute: "Wait just one minute while I grab my jacket.",
  mix: "Mix the flour and sugar together in a bowl.",
  model: "She built a model airplane from a kit.",
  moment: "She paused for a moment to think.",
  month: "We are going on vacation next month.",
  mountain: "They climbed to the top of the mountain.",
  movie: "We watched a funny movie last night.",
  museum: "The museum had dinosaur bones on display.",
  myself: "I made this birthday card all by myself.",
  nation: "The entire nation celebrated the holiday.",
  natural: "The waterfall is a beautiful natural wonder.",
  nearly: "She nearly tripped on the uneven sidewalk.",
  necessary: "A good breakfast is necessary for a productive day.",
  neck: "She wore a silver chain around her neck.",
  neighbor: "Our neighbor has a friendly golden retriever.",
  news: "She read the news on her phone every morning.",
  newspaper: "He reads the newspaper with his morning coffee.",
  nobody: "Nobody knew the answer to the riddle.",
  noise: "The loud noise woke up the sleeping baby.",
  none: "None of the students were absent.",
  nor: "She likes neither cats nor dogs.",
  nose: "She has a freckle on her nose.",
  note: "She wrote a thank-you note to her teacher.",
  ocean: "The ocean stretches as far as the eye can see.",
  of: "The color of the sky changes at sunset.",
  offer: "She made a generous offer to help.",
  office: "Her office has a wonderful view of the park.",
  oh: "Oh, I didn't realize you were already here.",
  oil: "Add a little oil to the pan before cooking.",
  onto: "The cat jumped onto the kitchen counter.",
  orange: "She peeled an orange for a snack.",
  paid: "She paid for the tickets in advance.",
  pair: "She bought a new pair of shoes.",
  pan: "Heat the pan before adding the butter.",
  park: "We took the dog to the park for a walk.",
  particular: "She is very particular about how her coffee is made.",
  party: "Everyone had a wonderful time at the party.",
  past: "In the past, people traveled by horse.",
  path: "Follow the path through the woods to the lake.",
  pattern: "The quilt has a beautiful flower pattern.",
  peace: "The country finally found peace after the war.",
  pen: "She signed the document with a blue pen.",
  penny: "She found a shiny penny on the ground.",
  perfect: "The weather was perfect for a day at the beach.",
  perhaps: "Perhaps we should try a different approach.",
  period: "The class period lasts forty-five minutes.",
  person: "She is the kindest person I have ever met.",
  phone: "She left her phone at home by mistake.",
  pig: "The pig rolled happily in the mud.",
  plain: "The dress was plain but elegant.",
  plane: "The plane landed safely on the runway.",
  plate: "She put the sandwich on a clean plate.",
  player: "She is the best player on the basketball team.",
  pocket: "He put the coins in his pocket.",
  popular: "That book is very popular with young readers.",
  possible: "Is it possible to finish this by Friday?",
  pound: "The bag weighs about one pound.",
  practice: "Daily practice is the key to improvement.",
  prepare: "She helped prepare dinner for the whole family.",
  president: "The president gave a speech to the nation.",
  press: "Press the green button to start the machine.",
  price: "The price of gas went up this week.",
  print: "Please print your name clearly on the form.",
  probably: "It will probably rain tomorrow afternoon.",
  produce: "The farm produces fresh vegetables every summer.",
  program: "She watched her favorite program on television.",
  promise: "She made a promise to always do her best.",
  proper: "Please use proper grammar in your essays.",
  protect: "Sunscreen helps protect your skin from sunburn.",
  provide: "The school will provide all the materials needed.",
  public: "The public library is open every day.",
  purpose: "The purpose of the meeting is to plan the event.",
  quarter: "She found a quarter under the couch cushion.",
  queen: "The queen wore a magnificent golden crown.",
  question: "She asked a very interesting question.",
  quiet: "Please be quiet during the exam.",
  race: "She trained hard and won the race.",
  radio: "We listened to music on the radio.",
  raise: "They plan to raise money for charity.",
  ran: "She ran as fast as she could to catch the bus.",
  ranch: "The family owns a cattle ranch in the country.",
  range: "The mountain range stretched across the horizon.",
  rather: "I would rather stay home than go out tonight.",
  reason: "She had a good reason for being late.",
  receive: "She was happy to receive a letter from her friend.",
  record: "She broke the school record in the high jump.",
  repeat: "Please repeat the instructions one more time.",
  report: "She wrote a detailed report about the experiment.",
  result: "Hard work led to a wonderful result.",
  return: "Please return the library books by Friday.",
  rich: "The soil in the valley is very rich and fertile.",
  rise: "The sun will rise early tomorrow morning.",
  roll: "Please roll the dice to start the game.",
  roof: "The bird sat on the roof of the house.",
  rope: "She climbed the rope all the way to the top.",
  row: "The students sat in a neat row.",
  rule: "The first rule is to always be respectful.",
  safe: "Keep your important documents in a safe place.",
  sail: "The boat set sail at dawn.",
  salt: "Please pass the salt for my soup.",
  sand: "The children built a castle out of sand.",
  sat: "She sat in her favorite chair by the window.",
  saw: "I saw a shooting star last night.",
  scared: "The loud thunder made the puppy very scared.",
  scene: "The opening scene was dramatic.",
  science: "She loves her science class the most.",
  search: "They organized a search for the missing dog.",
  season: "Autumn is my favorite season of the year.",
  seat: "Please take a seat at the front of the room.",
  secret: "She whispered a secret into her friend's ear.",
  section: "Turn to the vocabulary section of your textbook.",
  self: "She has a strong sense of self.",
  sell: "They plan to sell their house.",
  send: "Please send me a message when you arrive.",
  sense: "Her answer makes a lot of sense.",
  sent: "She sent a letter to her friend.",
  sentence: "Write a complete sentence for each vocabulary word.",
  serious: "She had a very serious look on her face.",
  serve: "The restaurant will serve dinner at six.",
  service: "The customer service was excellent at that store.",
  settle: "They decided to settle the argument peacefully.",
  several: "She read several books during summer break.",
  shall: "Shall we go for a walk after lunch?",
  shape: "The cookie cutter is in the shape of a star.",
  share: "Please share the crayons with your neighbor.",
  sheep: "The farmer counted the sheep in the meadow.",
  shell: "She found a beautiful shell on the beach.",
  shine: "The stars shine brightly on a clear night.",
  shoe: "She tied her shoe before starting the race.",
  shoot: "The photographer went outside to shoot pictures.",
  shop: "We went to the shop to buy new school supplies.",
  shore: "The waves crashed gently on the shore.",
  shot: "The basketball player made the winning shot.",
  shoulder: "She carried the bag on her shoulder.",
  shout: "She had to shout to be heard over the wind.",
  shut: "Please shut the gate behind you.",
  sick: "He stayed home from school because he was sick.",
  sight: "The sunset was a beautiful sight.",
  sign: "Follow the sign to the parking lot.",
  silence: "The library was filled with complete silence.",
  silver: "She wore a beautiful silver necklace.",
  similar: "The two sisters look very similar to each other.",
  since: "She has played the violin since she was five.",
  sir: "May I take your order, sir?",
  sister: "Her sister is three years younger than her.",
  situation: "She handled the difficult situation with grace.",
  size: "What size shoes do you wear?",
  skill: "Learning a new skill takes time and practice.",
  skin: "The sun can damage your skin without sunscreen.",
  sky: "The sky turned pink and orange at sunset.",
  slip: "Be careful not to slip on the wet floor.",
  smell: "The smell of fresh cookies filled the house.",
  smile: "Her warm smile brightened everyone's day.",
  smoke: "We could see smoke rising from the campfire.",
  soft: "The kitten's fur was incredibly soft.",
  soil: "The garden has rich, dark soil.",
  soldier: "The soldier marched proudly in the parade.",
  somebody: "Somebody left their umbrella in the hallway.",
  someone: "She waited for someone to answer the door.",
  sometimes: "Sometimes it rains on the sunniest days.",
  son: "Their son just started school.",
  song: "She sang a beautiful song at the talent show.",
  sorry: "I am sorry for stepping on your foot.",
  sort: "Please sort the books by the author's last name.",
  space: "The astronaut traveled into outer space.",
  speak: "She can speak three languages fluently.",
  special: "Today is a very special occasion.",
  speech: "She gave an inspiring speech at the ceremony.",
  speed: "The speed limit on this road is forty miles per hour.",
  spend: "She likes to spend weekends at the beach.",
  spoke: "He spoke clearly so everyone could understand.",
  spot: "She found the perfect spot for a picnic.",
  spread: "She spread butter on her warm toast.",
  square: "The town square has a beautiful fountain.",
  stage: "The actors performed on the large stage.",
  standard: "The school has high standards for all students.",
  station: "We arrived at the train station on time.",
  stay: "Please stay here while I get the car.",
  stick: "The dog fetched the stick from the river.",
  stock: "The store is out of stock on that item.",
  stone: "She skipped a smooth stone across the lake.",
  stood: "She stood at the front of the class to present.",
  store: "We went to the store to buy groceries.",
  storm: "The storm brought heavy rain and strong winds.",
  straight: "Drive straight ahead for two more miles.",
  strange: "She heard a strange noise in the attic.",
  stream: "A clear stream flowed through the meadow.",
  street: "She lives on a quiet tree-lined street.",
  student: "Every student received a certificate of achievement.",
  stuff: "She packed all her stuff into a backpack.",
  subject: "Science is her favorite subject at school.",
  sudden: "The sudden thunderclap startled everyone.",
  sugar: "She added a spoonful of sugar to her tea.",
  suggest: "May I suggest we try the Italian restaurant?",
  summer: "They spent the summer at their grandmother's house.",
  supper: "Supper will be ready in about thirty minutes.",
  surprise: "The birthday party was a complete surprise.",
  sweet: "The chocolate cake was very sweet.",
  system: "The solar system has eight planets.",
  tall: "The tall giraffe reached the highest leaves.",
  taste: "The homemade soup had a wonderful taste.",
  teacher: "The teacher helped the student with the problem.",
  team: "The team won the championship game.",
  test: "She studied hard and did well on the test.",
  their: "Their car is parked outside.",
  themselves: "The children cleaned up the mess themselves.",
  thick: "The thick fog made it hard to see the road.",
  thin: "She sliced the bread into thin pieces.",
  third: "He finished in third place in the race.",
  thousand: "A thousand fans cheered at the game.",
  throw: "Throw the ball to me and I will catch it.",
  tie: "He learned how to tie his shoes by himself.",
  till: "We waited till the rain stopped before going out.",
  tiny: "The tiny hummingbird hovered near the flower.",
  tired: "She was tired after running five miles.",
  told: "She told me a secret about the surprise party.",
  tomorrow: "We have a field trip planned for tomorrow.",
  tonight: "We are going out for dinner tonight.",
  took: "She took her umbrella just in case it rained.",
  tool: "A hammer is a useful tool for building things.",
  total: "The total cost of the groceries was fifty dollars.",
  touch: "Be careful not to touch the hot stove.",
  track: "The runners warmed up on the track.",
  trade: "They decided to trade baseball cards.",
  trail: "The hiking trail winds through the forest.",
  travel: "She loves to travel to new places.",
  tried: "She tried her best and won the spelling bee.",
  trip: "Our family trip to the beach was wonderful.",
  truck: "The delivery truck arrived right on time.",
  trust: "You can always trust a true friend.",
  truth: "She always tells the truth.",
  twelve: "There are twelve months in a year.",
  twenty: "She blew out twenty candles on her birthday cake.",
  twice: "She checked her work twice before turning it in.",
  type: "She can type fifty words per minute.",
  uncle: "My uncle lives in a cabin in the woods.",
  understand: "Do you understand the homework assignment?",
  unit: "We are starting a new unit in math class.",
  usual: "She took her usual seat by the window.",
  valley: "The river runs through the green valley.",
  value: "She learned the value of hard work.",
  visit: "We plan to visit our grandparents this weekend.",
  vote: "Every citizen should vote in the election.",
  wait: "Please wait here for a moment.",
  war: "The war lasted for several years.",
  wash: "Please wash your hands before eating.",
  wave: "She gave a friendly wave as she left.",
  wear: "What should I wear to the party?",
  weather: "The weather is beautiful today.",
  weight: "The weight of the package was ten pounds.",
  welcome: "The host gave us a warm welcome.",
  well: "She played the piano very well at the recital.",
  western: "They watched a classic western movie together.",
  wheel: "The front wheel of the bicycle needs air.",
  where: "Where did you put my keys?",
  whether: "I don't know whether to go or stay.",
  while: "She read a book while waiting for the bus.",
  whom: "The student to whom the prize was given was thrilled.",
  whose: "Whose jacket is hanging on the back of the chair?",
  wife: "His wife surprised him with a birthday cake.",
  wild: "We saw wild horses running through the meadow.",
  win: "She practiced hard so her team could win.",
  wire: "The electrician connected the wire to the outlet.",
  within: "The package should arrive within three days.",
  without: "She went outside without her coat.",
  woman: "The woman donated books to the library.",
  women: "The women organized a charity fundraiser.",
  won: "She won the race by three seconds.",
  wonder: "I wonder what the weather will be like tomorrow.",
  wood: "The cabin was built from wood.",
  wore: "She wore a beautiful gown to the gala.",
  worker: "The construction worker wore a hard hat.",
  worry: "There is no need to worry about the test.",
  worse: "The weather today is worse than yesterday.",
  worst: "That was the worst storm we have had all year.",
  worth: "The antique vase was worth a great deal.",
  written: "She has written three letters this week.",
  wrong: "She realized she had the wrong answer.",
  wrote: "He wrote a poem for his mother on her birthday.",
  yellow: "The bright yellow sunflower stood tall in the garden.",
  yet: "She hasn't finished her homework yet.",
  you: "I saved a seat for you at the table.",
  yourself: "Please help yourself to some food.",
  zero: "The temperature dropped to zero last night.",
  area: "The picnic area is next to the lake.",
  God: "Many people pray to God for guidance.",
  I: "I am going to the library after school.",
  "doesn't": "She doesn't like to eat broccoli.",
};

export default COMMON_SENTENCES;
