/**
 * Curated sentences for Level 2 (Common) words not already covered by Level 1.
 */
const COMMON2_SENTENCES: Record<string, string> = {
  able: "She was able to finish the project on time.",
  abolish: "The movement fought to abolish unfair laws.",
  absorb: "A sponge can absorb a large amount of water.",
  abstract: "The abstract painting used bold colors and shapes.",
  abundance: "The garden produced an abundance of fresh tomatoes.",
  academic: "She received an academic scholarship to the university.",
  accent: "She spoke English with a French accent.",
  accept: "She was happy to accept the award.",
  acceptable: "His behavior in class was not acceptable.",
  accessible: "The building is accessible to wheelchair users.",
  accident: "Luckily, no one was hurt in the car accident.",
  accomplish: "She can accomplish anything she puts her mind to.",
  accountable: "Every student is accountable for their own work.",
  accumulate: "Dust can accumulate quickly under the furniture.",
  accuracy: "The accuracy of her measurements was impressive.",
  accustom: "It took time to accustom himself to the new schedule.",
  achieve: "Hard work will help you achieve your goals.",
  achievement: "Winning the science fair was a great achievement.",
  acknowledge: "She was quick to acknowledge her mistake.",
  acquaint: "Let me acquaint you with the new classroom rules.",
  act: "She got the lead role in the school act.",
  action: "The firefighters sprang into action immediately.",
  active: "She leads a very active lifestyle.",
  actual: "The actual cost was lower than we expected.",
  actually: "The movie was actually much better than I thought.",
  addition: "In addition to math, she also excels at science.",
  address: "Please write your address on the envelope.",
  adequate: "Make sure you get adequate sleep before the test.",
  adjacent: "The park is adjacent to the school.",
  admirable: "Her dedication to helping others is admirable.",
  admire: "I admire her courage and determination.",
  admission: "The museum offers free admission on Sundays.",
  admit: "He had to admit that he was wrong.",
  adolescence: "Adolescence is a time of many changes.",
  adult: "Every adult in the room stood and applauded.",
  advance: "Technology continues to advance rapidly.",
  advancement: "The advancement of science has changed our lives.",
  adventure: "The camping trip was a real adventure.",
  adversary: "The two chess players were worthy adversaries.",
  advice: "She gave me excellent advice about studying.",
  advocate: "She is a strong advocate for animal rights.",
  affair: "The charity dinner was an elegant affair.",
  affectionate: "The puppy is very affectionate with children.",
  affirmation: "A positive affirmation can boost your confidence.",
  afford: "They worked hard to afford a new home.",
  afraid: "The little boy was afraid of the dark.",
  agency: "The travel agency helped us plan our vacation.",
  agent: "The real estate agent showed us the house.",
  aggressive: "The aggressive dog barked at every passerby.",
  agitate: "Shaking the bottle will agitate the contents.",
  agree: "We all agree that teamwork is important.",
  agreeable: "The weather was warm and agreeable.",
  ahead: "The road ahead was long and winding.",
  aim: "Her aim was to finish the race in first place.",
  aircraft: "The aircraft flew smoothly above the clouds.",
  aisle: "Walk down the aisle to find the cereal.",
  alarm: "The fire alarm rang loudly throughout the building.",
  album: "She put the photos in a new album.",
  alcohol: "The recipe calls for a small amount of cooking alcohol.",
  alive: "The garden came alive with butterflies in spring.",
  allegation: "The allegation was investigated thoroughly.",
  alliance: "The two countries formed a strong alliance.",
  allow: "Please allow enough time to finish the test.",
  allowance: "She saved her weekly allowance to buy a book.",
  ambassador: "The ambassador represented her country overseas.",
  ambiguous: "The instructions were ambiguous and hard to follow.",
  amend: "They voted to amend the school policy.",
  amendment: "The first amendment protects freedom of speech.",
  ammunition: "The soldiers carried extra ammunition.",
  amount: "A small amount of salt improves the flavor.",
  ancestor: "Her ancestor came to this country long ago.",
  ancient: "The ancient temple was thousands of years old.",
  angel: "She played an angel in the holiday pageant.",
  angle: "Measure the angle with a protractor.",
  angry: "She was angry when she found out the truth.",
  animate: "The artist learned to animate cartoon characters.",
  anniversary: "They celebrated their wedding anniversary.",
  announce: "The principal will announce the winners tomorrow.",
  annual: "The annual school fair is always in May.",
  annually: "The festival is held annually in the fall.",
  anonymous: "The generous donation was made by an anonymous person.",
  anticipate: "We anticipate a large crowd at the concert.",
  antique: "The antique clock had been in the family for generations.",
  anxiety: "She felt some anxiety before the big performance.",
  anxious: "He was anxious about his first day at the new school.",
  anybody: "Does anybody want to volunteer for the project?",
  anyway: "It was raining, but we went for a walk anyway.",
  apart: "The two towns are thirty miles apart.",
  apartment: "They moved into a cozy apartment downtown.",
  apparatus: "The science lab had all the necessary apparatus.",
  apparent: "It was apparent that she had practiced for weeks.",
  appeal: "The colorful poster had great visual appeal.",
  appear: "Stars appear in the sky after the sun sets.",
  appetite: "The long hike gave everyone a big appetite.",
  applause: "The audience burst into applause after the song.",
  appliance: "The kitchen has every modern appliance you need.",
  application: "She submitted her college application early.",
  appoint: "The mayor will appoint a new committee chair.",
  appreciate: "I really appreciate all your hard work.",
  apprentice: "The apprentice learned the trade from the master.",
  approach: "We watched the storm approach from the west.",
  appropriate: "Wear appropriate clothing for the weather.",
  approval: "The plan received approval from the committee.",
  approve: "Did your parents approve of the field trip?",
  approximate: "The approximate distance is about ten miles.",
  aquatic: "Dolphins are intelligent aquatic mammals.",
  arch: "The stone arch stood at the entrance to the park.",
  arctic: "The arctic temperatures made it dangerously cold.",
  arena: "The basketball arena was packed with fans.",
  argue: "The siblings would argue about who got the window seat.",
  arise: "Problems may arise if we don't plan carefully.",
  aristocrat: "The aristocrat lived in a grand mansion.",
  army: "The army marched in formation across the field.",
  aromatic: "The aromatic herbs filled the kitchen with scent.",
  arrange: "She helped arrange the flowers in the vase.",
  arrest: "The police made an arrest after the investigation.",
  arrive: "The train should arrive at noon.",
  arrogant: "Nobody likes an arrogant person.",
  article: "She read an interesting article about space travel.",
  artillery: "The museum displayed artillery from the war.",
  ascend: "The hikers began to ascend the steep mountain trail.",
  aside: "She set aside time every evening to read.",
  aspire: "She aspires to become a marine biologist.",
  assemble: "Please assemble in the auditorium for the meeting.",
  assertion: "His assertion was supported by strong evidence.",
  assessment: "The teacher gave a quick assessment of each student.",
  assistance: "Thank you for your kind assistance.",
  associate: "People often associate spring with new beginnings.",
  assume: "Don't assume anything without checking the facts.",
  assumption: "His assumption turned out to be incorrect.",
  assurance: "She gave her assurance that the work would be done.",
  astonish: "The magic trick was sure to astonish the audience.",
  astronomy: "She studied astronomy and learned about the planets.",
  atmosphere: "The restaurant had a warm and friendly atmosphere.",
  attach: "Please attach the file to your email.",
  attachment: "She felt a strong attachment to her childhood home.",
  attack: "The lioness prepared to attack her prey.",
  attain: "She worked hard to attain her diploma.",
  attempt: "On his second attempt, he climbed the wall successfully.",
  attend: "All students must attend the assembly.",
  attendance: "Perfect attendance earned her a special certificate.",
  attention: "Please pay attention during the lesson.",
  attitude: "A positive attitude makes a big difference.",
  attract: "Bright flowers attract bees and butterflies.",
  attribute: "Patience is an important attribute for a teacher.",
  auction: "The painting sold for a high price at the auction.",
  audible: "Her voice was barely audible in the noisy room.",
  audience: "The audience clapped loudly after the performance.",
  aunt: "My aunt is visiting from California.",
  authentic: "The restaurant serves authentic Italian food.",
  authorize: "Only the principal can authorize a field trip.",
  automatic: "The doors open automatically when you approach.",
  autumn: "The leaves turn red and gold in autumn.",
  avalanche: "The avalanche covered the road with snow.",
  avenue: "They walked down the tree-lined avenue.",
  average: "The average temperature in July is very warm.",
  avoid: "Wear sunscreen to avoid getting a sunburn.",
  awake: "She was awake long before the alarm went off.",
  award: "She received an award for her science project.",
  awful: "The weather this weekend was absolutely awful.",
  awkward: "There was an awkward silence after his joke.",
  bachelor: "He earned a bachelor's degree in engineering.",
  bake: "She loves to bake cookies on rainy days.",
  balance: "She practiced standing on one foot to improve her balance.",
  balcony: "They watched the sunset from the balcony.",
  bamboo: "The panda eats bamboo shoots every day.",
  bandage: "The nurse wrapped a bandage around his injured wrist.",
  banquet: "The banquet was held in the grand ballroom.",
  bar: "She grabbed a granola bar for a quick snack.",
  barbecue: "We had a barbecue in the backyard on Saturday.",
  barely: "She barely made it to class before the bell rang.",
  bargain: "The jacket was a great bargain at half price.",
  barrel: "The barrel was filled with fresh rainwater.",
  barrier: "The language barrier made communication difficult.",
  basement: "The kids set up a playroom in the basement.",
  basic: "Learning the basic rules is the first step.",
  bat: "The bat flew out of the cave at dusk.",
  bath: "The warm bath helped her relax after a long day.",
  baton: "The conductor raised the baton to begin the symphony.",
  battalion: "The battalion was deployed to the border.",
  battle: "The two teams prepared for the championship battle.",
  bay: "The sailboats anchored in the calm bay.",
  beach: "We spent the afternoon building sandcastles at the beach.",
  beacon: "The lighthouse served as a beacon for passing ships.",
  beam: "A beam of sunlight shone through the window.",
  bean: "She planted a bean seed in the garden pot.",
  bearing: "The compass helped us find our bearing in the woods.",
  beat: "The drummer kept a steady beat throughout the song.",
  beauty: "The beauty of the mountain scenery was breathtaking.",
  bedroom: "She painted her bedroom a soft shade of blue.",
  beef: "The stew was made with tender chunks of beef.",
  beer: "He ordered a cold beer with his dinner.",
  beforehand: "She prepared all the materials beforehand.",
  begin: "Classes begin at eight in the morning.",
  behalf: "She accepted the award on behalf of her team.",
  bell: "The school bell rang at three o'clock.",
  belong: "These books belong on the top shelf.",
  belt: "He tightened his belt after losing some weight.",
  bend: "Be careful driving around the sharp bend in the road.",
  beneficial: "Exercise is beneficial for both body and mind.",
  benefit: "Good health is a great benefit of regular exercise.",
  benevolent: "The benevolent donor funded the new playground.",
  beverage: "Would you like a hot or cold beverage?",
  bewilder: "The complex puzzle would bewilder most people.",
  beyond: "The view extended far beyond the horizon.",
  bill: "She paid the electricity bill online.",
  bind: "Use string to bind the newspapers together.",
  biography: "She read a biography of her favorite scientist.",
  birth: "The birth of the baby brought great joy.",
  biscuit: "She spread butter on a warm biscuit.",
  bite: "The mosquito bite left a red bump on her arm.",
  bitter: "The medicine had a bitter taste.",
  blade: "The blade of the knife was very sharp.",
  blame: "Don't blame others for your own mistakes.",
  blank: "She stared at the blank page, unsure what to write.",
  blanket: "She wrapped herself in a warm blanket.",
  blaze: "The campfire burned with a bright blaze.",
  bleed: "A small cut on her finger started to bleed.",
  blend: "Blend the fruit and yogurt together in a blender.",
  bless: "The kind old woman would bless everyone she met.",
  blind: "The bright light was nearly blind to look at.",
  block: "The child stacked one block on top of another.",
  blood: "The doctor took a small sample of her blood.",
  bloom: "The roses bloom beautifully in June.",
  blossom: "The cherry blossom trees are stunning in spring.",
  blow: "The strong wind began to blow the papers away.",
  blueprint: "The architect reviewed the blueprint of the building.",
  blur: "Without glasses, everything appears as a blur.",
  boast: "She doesn't boast about her accomplishments.",
  bolt: "He tightened the bolt with a wrench.",
  bomb: "The old bomb was safely removed by the experts.",
  bone: "The dog buried a bone in the backyard.",
  bonfire: "They roasted marshmallows over the bonfire.",
  bonus: "Finishing early was a nice bonus.",
  booklet: "The travel booklet had maps and helpful tips.",
  border: "The river forms a natural border between the two states.",
  borrow: "May I borrow your pencil for a moment?",
  bother: "Don't bother her while she's studying.",
  bottle: "She filled the bottle with cold water.",
  boulder: "A large boulder blocked the hiking trail.",
  boulevard: "They walked along the grand boulevard.",
  bounce: "The ball began to bounce down the stairs.",
  bouquet: "He gave her a bouquet of fresh flowers.",
  bow: "The performer took a bow after the standing ovation.",
  bowl: "She poured cereal into a bowl for breakfast.",
  bracelet: "She wore a silver bracelet on her wrist.",
  braille: "The sign was written in braille for the visually impaired.",
  brain: "The brain controls everything the body does.",
  branch: "A bird landed on the highest branch of the tree.",
  brand: "She always buys the same brand of cereal.",
  brave: "The brave firefighter rescued the family.",
  breakthrough: "The discovery was a major scientific breakthrough.",
  breast: "The robin puffed out its red breast proudly.",
  breath: "She took a deep breath before diving in.",
  breathe: "It is important to breathe deeply when you exercise.",
  breed: "The golden retriever is a popular dog breed.",
  brewery: "The old brewery was turned into a restaurant.",
  brick: "The house was made of red brick.",
  bridge: "The stone bridge crosses the river in the park.",
  brief: "The meeting was brief and to the point.",
  brigade: "The fire brigade arrived within minutes.",
  brilliance: "The brilliance of the sunset took our breath away.",
  broad: "The broad river flowed gently through the town.",
  broadcast: "The news was broadcast live on television.",
  brochure: "The travel brochure described many exciting destinations.",
  broken: "The broken window needed to be replaced.",
  brow: "She wiped the sweat from her brow.",
  bruise: "She got a small bruise on her knee from falling.",
  brush: "She used a brush to paint the canvas.",
  brutal: "The winter storm was absolutely brutal.",
  bubble: "The child blew a big soap bubble.",
  bucket: "She filled a bucket with soapy water.",
  buckle: "Please buckle your seatbelt before takeoff.",
  budget: "They created a budget to manage their spending.",
  buffet: "The hotel offered a delicious breakfast buffet.",
  bug: "A tiny bug landed on her hand.",
  building: "The tall building has fifty floors.",
  bullet: "The sheriff found the bullet lodged in the wall.",
  bulletin: "Check the bulletin board for upcoming events.",
  bully: "No one should be allowed to bully others.",
  bunch: "She picked a bunch of grapes from the vine.",
  bundle: "She carried a bundle of firewood to the cabin.",
  buoyant: "The cork was buoyant and floated on the water.",
  burden: "He didn't want to be a burden on his family.",
  bureau: "The weather bureau issued a storm warning.",
  burglary: "The police investigated the burglary at the store.",
  burn: "Be careful not to burn yourself on the hot pan.",
  burst: "The balloon burst with a loud pop.",
  bury: "The dog tried to bury its bone in the yard.",
  butter: "She spread butter on her warm toast.",
  button: "Press the button to call the elevator.",
  cab: "She took a cab to the airport.",
  cabin: "The log cabin sat beside a quiet lake.",
  cable: "The cable car traveled up the steep mountain.",
  calcium: "Milk is a good source of calcium for strong bones.",
  calculate: "Use the calculator to calculate the total cost.",
  calendar: "She marked the date on the calendar.",
  calligraphy: "She practiced calligraphy with a special pen.",
  calm: "The lake was perfectly calm on that windless morning.",
  camera: "She took a photo with her new camera.",
  camouflage: "The chameleon uses camouflage to hide from predators.",
  campfire: "They told stories around the campfire at night.",
  canal: "The boats traveled slowly down the narrow canal.",
  cancel: "They had to cancel the picnic because of rain.",
  canopy: "The forest canopy blocked most of the sunlight.",
  capability: "The new computer has impressive capability.",
  capable: "She is capable of solving any math problem.",
  capacity: "The stadium has a capacity of fifty thousand seats.",
  capital: "Washington is the capital of the United States.",
  capsule: "The time capsule was buried in the schoolyard.",
  captain: "The captain steered the ship through the storm.",
  captive: "The rescued bird was no longer held captive.",
  capture: "The photographer tried to capture the perfect sunset.",
  caravan: "A caravan of camels crossed the sandy desert.",
  carbon: "Trees absorb carbon dioxide from the air.",
  card: "She wrote a thank-you card for her teacher.",
  cardinal: "A bright red cardinal sat on the fence.",
  career: "She chose a career in medicine.",
  careful: "Be careful crossing the busy street.",
  caretaker: "The caretaker maintained the school grounds beautifully.",
  carnival: "The carnival had rides, games, and cotton candy.",
  carpet: "The soft carpet felt warm under her feet.",
  cartridge: "She replaced the ink cartridge in the printer.",
  cascade: "Water tumbled down the rocks in a beautiful cascade.",
  casualty: "Fortunately, there was no casualty in the minor accident.",
  catalog: "She ordered new books from the library catalog.",
  catastrophe: "The earthquake was a terrible catastrophe.",
  category: "The books are organized by category on the shelves.",
  cathedral: "The ancient cathedral had stunning stained glass windows.",
  cattle: "The cattle grazed peacefully in the pasture.",
  caution: "Use caution when crossing the icy bridge.",
  cavalry: "The cavalry charged across the open battlefield.",
  ceiling: "The ceiling in the old church was painted.",
  celebrate: "Let's celebrate your birthday with a big party.",
  celebration: "The town held a celebration for the holiday.",
  celestial: "Stars are celestial objects visible in the night sky.",
  census: "The census counts every person in the country.",
  centennial: "The town held a centennial celebration for its anniversary.",
  ceramic: "She made a ceramic bowl in her pottery class.",
  ceremony: "The graduation ceremony was held in the auditorium.",
  certificate: "She earned a certificate for completing the course.",
  chain: "The bicycle chain came off while she was riding.",
  challenge: "Climbing the mountain was a real challenge.",
  champion: "She became the national spelling champion.",
  chancellor: "The chancellor addressed the university students.",
  channel: "She changed the channel to watch the news.",
  chapter: "Read the next chapter of the book for homework.",
  character: "The main character in the story was very brave.",
  characteristic: "Honesty is an important characteristic of a leader.",
  charge: "There is no charge for children under five.",
  chariot: "The ancient chariot was pulled by two horses.",
  charitable: "The charitable organization helps families in need.",
  charity: "She donated money to a local charity.",
  charm: "The small town had a certain old-fashioned charm.",
  chart: "The doctor checked the patient's medical chart.",
  charter: "The company charter outlined the rules for members.",
  chase: "The dog loved to chase squirrels in the park.",
  cheap: "The notebook was cheap but good quality.",
  cheese: "She added extra cheese to the pizza.",
  chemical: "The scientist studied the chemical reaction carefully.",
  cherish: "She will always cherish the memories of that summer.",
  chest: "He kept old photographs in a wooden chest.",
  chicken: "She roasted a chicken for Sunday dinner.",
  childhood: "Her childhood was filled with happy memories.",
  chimney: "Smoke rose from the chimney on the cold morning.",
  chip: "She ate a chip with salsa as a snack.",
  choice: "You have a choice between two desserts.",
  choose: "It was hard to choose between the two flavors.",
  chronicle: "The book was a chronicle of the town's history.",
  circulation: "The library has thousands of books in circulation.",
  circumstance: "Under the circumstance, she did the best she could.",
  citation: "The officer issued a citation for the traffic violation.",
  citizen: "Every citizen has the right to vote.",
  civil: "The civil rights movement changed the nation.",
  civilian: "The civilian population was kept safe during the storm.",
  civilization: "Ancient Egyptian civilization built the great pyramids.",
  claim: "She went to claim her lost luggage at the airport.",
  clarity: "She spoke with clarity and confidence.",
  classic: "That novel is considered a classic of literature.",
  classify: "Scientists classify animals into different groups.",
  cleanse: "Use warm water to cleanse the wound.",
  clever: "The clever student solved the riddle in seconds.",
  client: "The lawyer met with her client to discuss the case.",
  climate: "The tropical climate is warm and humid year-round.",
  climb: "She decided to climb the tallest mountain in the region.",
  clinic: "The health clinic offers free checkups for children.",
  cloth: "She wiped the table with a damp cloth.",
  cluster: "A cluster of grapes hung from the vine.",
  coach: "The soccer coach taught the team a new strategy.",
  coal: "In the old days, trains were powered by coal.",
  coalition: "The coalition of groups worked together for change.",
  coast: "They drove along the scenic coast for hours.",
  coastal: "The coastal town was known for its beautiful beaches.",
  coin: "She found an old coin buried in the garden.",
  collaborate: "The students learned to collaborate on group projects.",
  collapse: "The old bridge began to collapse under the weight.",
  collar: "The dog wore a bright red collar.",
  colleague: "She invited her colleague to lunch.",
  collect: "He likes to collect stamps from different countries.",
  collision: "The collision between the two cars blocked the road.",
  colonel: "The colonel commanded the regiment.",
  colonial: "The town has many beautiful colonial buildings.",
  colony: "The ant colony was hidden beneath the large rock.",
  colossal: "The colossal statue was visible from miles away.",
  column: "The column of numbers was neatly written.",
  combine: "Combine the ingredients in a large mixing bowl.",
  combustion: "The engine works by internal combustion.",
  comedy: "We watched a hilarious comedy at the theater.",
  comfort: "The soft blanket provided comfort on the cold night.",
  command: "The captain gave the command to set sail.",
  commemorate: "The monument was built to commemorate the heroes.",
  comment: "She left a positive comment on the blog post.",
  commentary: "The sports commentary made the game more exciting.",
  commissioner: "The commissioner approved the new city plan.",
  commit: "She decided to commit to practicing every day.",
  commitment: "Running a marathon requires a serious commitment.",
  commodity: "Clean water is a precious commodity.",
  commonwealth: "The commonwealth of nations held a summit.",
  communicate: "It is important to communicate clearly with others.",
  community: "The community came together to clean up the park.",
  companion: "The loyal dog was her constant companion.",
  comparable: "The two houses are comparable in size and price.",
  compare: "Let's compare the two options before deciding.",
  comparison: "In comparison, the second plan is more affordable.",
  compassion: "She showed great compassion for those in need.",
  compatible: "The two devices are compatible with each other.",
  compel: "The exciting story will compel you to keep reading.",
  compensate: "The company will compensate you for the extra hours.",
  compete: "The best athletes compete in the national championship.",
  competent: "She is a very competent and skilled engineer.",
  compile: "He helped compile all the data into one report.",
  complain: "She never complains, even when things are difficult.",
  complex: "The math problem was very complex.",
  complexity: "The complexity of the project surprised everyone.",
  compliance: "The factory was in full compliance with safety rules.",
  complicate: "Adding more people will only complicate the plan.",
  compose: "She learned to compose music at a young age.",
  compound: "The scientist created a new chemical compound.",
  comprehend: "It is difficult to comprehend the size of the universe.",
  comprehensive: "The study was thorough and comprehensive.",
  compromise: "They reached a compromise that satisfied both sides.",
  compulsory: "Wearing a helmet while biking is compulsory.",
  conceal: "She tried to conceal her surprise at the news.",
  concentrate: "Please concentrate on your work during class.",
  concept: "The concept of gravity was explained by Newton.",
  concern: "Her main concern was the safety of the children.",
  conclude: "Based on the evidence, we can conclude that the theory is correct.",
  concrete: "The sidewalk is made of concrete.",
  condemn: "The council voted to condemn the unsafe building.",
  condense: "The steam will condense into water on the cold glass.",
  condition: "The old book was still in excellent condition.",
  conference: "She presented her research at the conference.",
  confess: "He had to confess that he ate the last cookie.",
  confession: "Her honest confession earned everyone's respect.",
  confidence: "She spoke with great confidence in front of the crowd.",
  confidential: "The patient's records are strictly confidential.",
  confine: "The snow forced us to confine ourselves indoors.",
  confirm: "Please confirm your reservation before arriving.",
  confirmation: "She received a confirmation email for her order.",
  conflict: "They resolved the conflict through open discussion.",
  conform: "All students must conform to the dress code.",
  confront: "She decided to confront the problem directly.",
  confuse: "The similar words can confuse new learners.",
  congratulate: "We congratulate the winners of the contest.",
  congress: "The congress debated the new education bill.",
  conjunction: "Use a conjunction to connect two sentences.",
  connect: "The bridge will connect the two sides of the river.",
  conscience: "Her conscience told her to return the lost wallet.",
  conscious: "He made a conscious effort to be more punctual.",
  consecutive: "She won the contest three consecutive years.",
  consensus: "The group reached a consensus on the best approach.",
  consequence: "Every action has a consequence.",
  conservation: "Conservation helps protect our natural resources.",
  consider: "Please consider all the options before deciding.",
  considerable: "The project required a considerable amount of time.",
  consist: "The team will consist of twelve players.",
  consistent: "Her grades have been consistently excellent.",
  consolidate: "They plan to consolidate all the reports into one.",
  conspiracy: "The novel was about an international conspiracy.",
  constant: "The constant noise from the construction was annoying.",
  constitute: "These students constitute the majority of the class.",
  constitution: "The constitution protects the rights of all citizens.",
  construct: "They plan to construct a new school building.",
  consult: "She went to consult a doctor about her symptoms.",
  consultant: "The business hired a consultant for advice.",
  consumer: "The consumer has many choices at the grocery store.",
  consumption: "Water consumption increases during the summer.",
  contact: "Please contact us if you have any questions.",
  contain: "The box can contain up to twenty items.",
  contaminate: "Chemicals can contaminate the water supply.",
  contemplation: "She sat in quiet contemplation by the lake.",
  contemporary: "The museum features contemporary art from local artists.",
  contempt: "He showed contempt for the unfair rules.",
  contend: "The two teams will contend for the championship.",
  content: "She was content with her simple life in the country.",
  contest: "She entered the spelling contest and won first place.",
  continent: "Africa is the second largest continent.",
  continual: "The continual rain flooded the streets.",
  continue: "Please continue reading from where you stopped.",
  contract: "Both parties signed the contract.",
  contradict: "His actions seemed to contradict his words.",
  contrary: "Contrary to popular belief, bats are not blind.",
  contrast: "The contrast between the two paintings was striking.",
  contribute: "Every team member should contribute to the project.",
  control: "She maintained control of the situation calmly.",
  controversial: "The decision was highly controversial.",
  controversy: "The new rule caused a great deal of controversy.",
  convenience: "The store is open late for your convenience.",
  convenient: "The bus stop is in a very convenient location.",
  convention: "The annual convention attracted thousands of visitors.",
  conversation: "They had a long conversation about their plans.",
  conversion: "The conversion of the old barn into a house was amazing.",
  convey: "Her smile was enough to convey her happiness.",
  conviction: "She spoke with deep conviction about her beliefs.",
  convince: "She tried to convince her parents to get a puppy.",
  cooperate: "The students learned to cooperate during group work.",
  coordinate: "She helped coordinate the school fundraiser.",
  copy: "Please make a copy of this document.",
  copyright: "The author holds the copyright to the novel.",
  coral: "The coral reef was teeming with colorful fish.",
  core: "The core of the apple contains the seeds.",
  corporate: "The corporate office is located downtown.",
  correct: "Her answer on the test was correct.",
  correspond: "The numbers on the map correspond to the locations.",
  corridor: "The students walked quietly through the corridor.",
  corrode: "Salt water can corrode metal over time.",
  corrupt: "The investigation uncovered corrupt officials.",
  cost: "The cost of the meal was very reasonable.",
  cottage: "They spent the summer in a cozy cottage by the sea.",
  cotton: "The shirt is made of soft cotton.",
  council: "The city council voted to build a new park.",
  counsel: "The teacher offered wise counsel to her students.",
  count: "Can you count all the stars in the sky?",
  counter: "She placed the groceries on the kitchen counter.",
  counterpart: "The mayor met with her counterpart from the other city.",
  county: "The county fair is held every August.",
  couple: "The couple celebrated their anniversary at a nice restaurant.",
  courage: "It takes courage to stand up for what is right.",
  courageous: "The courageous firefighter saved the family.",
  court: "The basketball court was freshly painted.",
  courtyard: "The fountain in the courtyard was beautiful.",
  cousin: "My cousin is coming to visit this weekend.",
  coverage: "The news coverage of the event was extensive.",
  crack: "A crack appeared in the old concrete wall.",
  cradle: "The baby slept peacefully in the cradle.",
  craft: "She enjoys the craft of making pottery.",
  crash: "The loud crash of thunder startled everyone.",
  crazy: "The roller coaster ride was absolutely crazy.",
  cream: "She added cream and sugar to her coffee.",
  create: "The students were asked to create a poster.",
  creature: "A strange creature emerged from the forest.",
  credential: "She presented her credential at the entrance.",
  credit: "She received credit for her hard work on the project.",
  crew: "The film crew set up cameras in the park.",
  crime: "The detective was determined to solve the crime.",
  criminal: "The criminal was caught by the police.",
  cripple: "The heavy snowfall could cripple the transportation system.",
  crisis: "The community came together during the crisis.",
  criterion: "The main criterion for the job is experience.",
  critic: "The movie critic gave the film a positive review.",
  critical: "It is critical to follow the safety instructions.",
  crop: "The farmer planted a new crop of wheat.",
  crown: "The queen placed the crown upon her head.",
  cruel: "It is cruel to mistreat animals.",
  crush: "Be careful not to crush the delicate flowers.",
  cultivate: "She learned to cultivate herbs in her small garden.",
  culture: "Traveling helps you learn about different cultures.",
  cupboard: "The cups are in the kitchen cupboard.",
  curator: "The museum curator organized a new exhibit.",
  cure: "Scientists are searching for a cure for the disease.",
  curious: "The curious child asked questions about everything.",
  currency: "The currency used in Japan is the yen.",
  current: "The current of the river was very strong.",
  curriculum: "The school updated its curriculum this year.",
  curtain: "She opened the curtain to let in the morning light.",
  curve: "The road has a sharp curve ahead.",
  custody: "The court granted custody to the mother.",
  custom: "It is a custom to shake hands when you meet someone.",
  customer: "The customer ordered a large coffee.",
  cycle: "The water cycle is an important part of nature.",
  cylinder: "The engine has a four-cylinder design.",
  damage: "The storm caused significant damage to the roof.",
  danger: "Stay away from the cliff edge to avoid danger.",
  dare: "She didn't dare to open the mysterious door.",
  database: "The information is stored in a secure database.",
  daughter: "Their daughter won the school spelling bee.",
  dead: "The battery in my phone is completely dead.",
  deadline: "She finished the project before the deadline.",
  deal: "They made a deal to share the chores equally.",
  death: "The death of the old oak tree saddened the neighborhood.",
  debate: "The students had a lively debate about the topic.",
  debris: "Workers cleared the debris after the storm.",
  decade: "A decade is a period of ten years.",
  decay: "The fallen leaves slowly decay on the forest floor.",
  deceive: "Appearances can sometimes deceive you.",
  decent: "She found a decent apartment near the university.",
  decide: "She couldn't decide which book to read next.",
  declaration: "The declaration of independence was a historic document.",
  decline: "The number of students in the class began to decline.",
  decorate: "They helped decorate the classroom for the party.",
  decree: "The king issued a decree for a national holiday.",
  dedicate: "She decided to dedicate her time to volunteering.",
  deduction: "The detective made a brilliant deduction.",
  default: "The default settings work well for most users.",
  defeat: "The team suffered a surprising defeat in the finals.",
  defect: "The factory recalled the product due to a defect.",
  defendant: "The defendant pleaded not guilty in court.",
  defensive: "The team played a strong defensive game.",
  deficit: "The budget had a significant deficit this year.",
  definite: "We need a definite answer by tomorrow.",
  deflect: "The shield was able to deflect the blow.",
  degrade: "Littering can degrade the natural environment.",
  deity: "The ancient temple was built to honor a deity.",
  deliberate: "The committee made a deliberate decision after much thought.",
  delicate: "The delicate flower needs gentle care.",
  delightful: "The garden party was absolutely delightful.",
  deliver: "The mail carrier will deliver the package today.",
  demand: "There is a high demand for skilled workers.",
  democracy: "Democracy gives citizens the power to vote.",
  demolish: "They plan to demolish the old warehouse.",
  demonstration: "The science demonstration amazed the students.",
  dense: "The dense fog made driving very difficult.",
  deny: "He could not deny that the cake was delicious.",
  departure: "The departure time for the flight is six o'clock.",
  depend: "You can always depend on a true friend.",
  dependable: "She is a very dependable member of the team.",
  deposit: "She made a deposit at the bank this morning.",
  depression: "The Great Depression was a difficult period in history.",
  deprive: "No one should deprive a child of an education.",
  deputy: "The deputy filled in while the sheriff was away.",
  derive: "Many English words derive from Latin roots.",
  descendant: "She is a descendant of a famous explorer.",
  describe: "Can you describe what the building looks like?",
  design: "The architect created a beautiful building design.",
  desk: "She organized all her papers neatly on her desk.",
  desperate: "The stranded hikers were desperate for water.",
  destination: "Our vacation destination is a tropical island.",
  destroy: "The storm threatened to destroy the old bridge.",
  destruction: "The hurricane caused widespread destruction.",
  detail: "She paid close attention to every detail.",
  detain: "The security guard had to detain the suspect.",
  detect: "Dogs can detect scents that humans cannot.",
  determination: "Her determination helped her win the race.",
  detour: "Road construction forced us to take a detour.",
  devastate: "The flood could devastate the entire region.",
  develop: "She worked hard to develop her writing skills.",
  deviate: "The bus had to deviate from its usual route.",
  device: "The new electronic device is very easy to use.",
  devotion: "His devotion to his family was inspiring.",
  diabetes: "A healthy diet can help manage diabetes.",
  diagnose: "The doctor was able to diagnose the illness quickly.",
  dialect: "Each region has its own unique dialect.",
  diameter: "The diameter of the circle is ten inches.",
  diamond: "The diamond sparkled brilliantly in the light.",
  dictation: "The teacher gave a dictation exercise to the class.",
  dictator: "The dictator ruled the country with an iron fist.",
  diesel: "The truck runs on diesel fuel.",
  differentiate: "Color helps differentiate the two species of bird.",
  direct: "Can you direct me to the nearest gas station?",
  dirty: "Her shoes were dirty after playing in the mud.",
  discover: "Scientists hope to discover new species in the ocean.",
  dish: "She washed every dish after dinner.",
  distance: "The distance between the two cities is fifty miles.",
  divide: "Please divide the cake into eight equal pieces.",
  double: "She ordered a double scoop of ice cream.",
  doubt: "I have no doubt that you will succeed.",
  dozen: "She bought a dozen eggs at the store.",
  drag: "He had to drag the heavy suitcase up the stairs.",
  drum: "She played the drum in the marching band.",
  dust: "She wiped the dust off the bookshelf.",
  duty: "It is your duty to keep your room clean.",
  edge: "She sat on the edge of the swimming pool.",
  education: "A good education opens many doors in life.",
  either: "You can choose either the red or the blue one.",
  electric: "The electric car runs quietly down the street.",
  empty: "The empty jar needed to be recycled.",
  enemy: "The hero bravely faced the enemy.",
  enter: "Please enter through the front door.",
  entire: "She read the entire book in one sitting.",
  escape: "The rabbit found a way to escape from the pen.",
  event: "The school concert was the biggest event of the year.",
  exact: "Do you know the exact time the train arrives?",
  examine: "The doctor will examine the patient this afternoon.",
  excite: "The announcement seemed to excite everyone in the room.",
  excuse: "There is no excuse for being rude to others.",
  express: "She used a poem to express her feelings.",
  extra: "She packed an extra sweater in case it got cold.",
  eyebrow: "She raised an eyebrow in surprise at the news.",
  factory: "The factory produces thousands of toys each day.",
  fail: "It's okay to fail as long as you try again.",
  faith: "She had great faith in her team's abilities.",
  famous: "The famous artist painted beautiful landscapes.",
  fancy: "She wore a fancy dress to the gala.",
  fashion: "The latest fashion trends change every season.",
  fault: "The car accident was not her fault.",
  favour: "Can you do me a favour and pass the salt?",
  fear: "She overcame her fear of public speaking.",
  feast: "The holiday feast included turkey and all the trimmings.",
  feather: "A soft feather floated down from the sky.",
  fever: "The child stayed home with a high fever.",
  fierce: "The fierce lion guarded its territory.",
  figure: "The figure in the painting looked lifelike.",
  film: "They watched a film about ocean wildlife.",
  final: "The final exam covers everything we learned this year.",
  fit: "She exercises every day to stay fit and healthy.",
  flag: "The national flag flew proudly outside the building.",
  flat: "The tire went flat on the way to school.",
  flesh: "The flesh of the peach was sweet and juicy.",
  flight: "The flight to London takes about seven hours.",
  float: "The leaves float gently on the surface of the pond.",
  flood: "The heavy rain caused a flood in the low areas.",
  flow: "The river continued to flow steadily downstream.",
  fold: "Please fold the napkins for the dinner table.",
  fool: "April first is known as April Fools' Day.",
  forbid: "The rules forbid running in the hallways.",
  forget: "Don't forget to pack your lunch for tomorrow.",
  forgive: "It is important to forgive and move forward.",
  fork: "She picked up her fork and began eating the salad.",
  fortune: "She had the good fortune to find a rare book.",
  forward: "Take two steps forward and one step back.",
  fox: "The clever fox outsmarted the hound.",
  frame: "She put the photograph in a beautiful gold frame.",
  freeze: "The water will freeze if the temperature drops below zero.",
  frighten: "The loud noise was enough to frighten the cat.",
  fruit: "Eating fresh fruit every day is good for you.",
  future: "She has big plans for the future.",
  gain: "Regular practice will help you gain confidence.",
  gather: "The students will gather in the gym for the assembly.",
  gentle: "She was very gentle when holding the newborn kitten.",
  globe: "She has a globe in her room that shows every country.",
  glove: "She put on a glove to protect her hand.",
  goat: "The goat climbed nimbly up the rocky hillside.",
  golden: "The golden sunset painted the sky in warm hues.",
  govern: "Elected officials govern the city.",
  grab: "Grab your jacket before heading outside.",
  grape: "She added a grape to her fruit salad.",
  greet: "She ran to greet her grandmother at the door.",
  guide: "The tour guide showed us the ancient ruins.",
  guilty: "The jury found the defendant guilty.",
  habit: "Reading before bed is a wonderful habit.",
  handle: "She turned the door handle and walked inside.",
  harbour: "The boats were safely moored in the harbour.",
  harm: "The medicine should do more good than harm.",
  harvest: "The farmers celebrated a bountiful harvest this year.",
  hate: "She would never hate anyone for being different.",
  health: "Good health is the most important thing in life.",
  height: "The height of the building is impressive.",
  hero: "The firefighter was a hero to the whole neighborhood.",
  hide: "The children love to play hide and seek.",
  highway: "The highway stretches across the entire state.",
  history: "She loves studying ancient history.",
  hobby: "Painting is her favorite weekend hobby.",
  hollow: "The squirrel hid acorns inside the hollow tree.",
  honest: "An honest person always tells the truth.",
  honey: "She drizzled honey on her warm biscuit.",
  hook: "She hung her coat on the hook by the door.",
  horrible: "The taste of the medicine was horrible.",
  hospital: "The new hospital opened its doors last month.",
  hotel: "They stayed at a charming hotel near the beach.",
  hunger: "Millions of people around the world suffer from hunger.",
  husband: "Her husband surprised her with flowers.",
  ill: "She stayed home from school because she was ill.",
  impossible: "Nothing is impossible if you work hard enough.",
  improve: "She practiced every day to improve her skills.",
  increase: "The company plans to increase production next year.",
  industry: "The technology industry is growing rapidly.",
  inform: "Please inform the teacher if you will be absent.",
  injure: "Be careful not to injure yourself on the playground.",
  insect: "A tiny insect landed on the leaf.",
  introduce: "Let me introduce you to my best friend.",
  invite: "She decided to invite the whole class to her party.",
  issue: "The committee discussed every issue on the agenda.",
  jacket: "He grabbed his jacket before heading into the cold.",
  jewel: "The crown was decorated with every precious jewel.",
  journey: "The journey across the country took five days.",
  judge: "The judge made a fair and thoughtful decision.",
  juice: "She poured a glass of fresh orange juice.",
  keen: "She has a keen eye for detail in her artwork.",
  kick: "He gave the soccer ball a powerful kick.",
  knock: "She heard a knock at the front door.",
  ladder: "He climbed the ladder to reach the top shelf.",
  lady: "The kind lady helped us find the right bus.",
  lamp: "The lamp cast a warm glow across the room.",
  language: "She can speak three different languages.",
  lazy: "The lazy cat slept all day in the sunshine.",
  leaf: "A green leaf fell gently from the tree.",
  leather: "The leather boots were sturdy and comfortable.",
  lend: "Can you lend me a pencil for the test?",
  level: "The water level rose after the heavy rain.",
  library: "She borrowed five books from the library.",
  lid: "Put the lid back on the jar when you are done.",
  lip: "She bit her lip while concentrating on the puzzle.",
  liquid: "The liquid in the beaker turned bright blue.",
  local: "The local bakery makes the best sourdough bread.",
  lock: "Always lock the door when you leave the house.",
  lonely: "She felt lonely on her first day at the new school.",
  loose: "The loose button finally fell off his shirt.",
  lord: "The lord of the manor welcomed his guests.",
  lose: "Don't lose your ticket or you can't get in.",
  major: "She chose biology as her major in college.",
  manage: "She learned to manage her time more effectively.",
  march: "The soldiers began to march in perfect formation.",
  marry: "They plan to marry in the spring.",
  material: "Cotton is a popular material for summer clothing.",
  meal: "Breakfast is the most important meal of the day.",
  medicine: "Take the medicine exactly as the doctor prescribed.",
  memory: "She has a wonderful memory for faces and names.",
  mention: "Did you mention the meeting to the rest of the team?",
  message: "She left a message on his answering machine.",
  metal: "The bridge is constructed from strong metal beams.",
  method: "She discovered a faster method for solving the problem.",
  middle: "The park is in the middle of the town.",
  million: "A million stars sparkled in the night sky.",
  minister: "The minister spoke at the community gathering.",
  mirror: "She checked her reflection in the mirror.",
  mistake: "Everyone makes a mistake from time to time.",
  modern: "The modern kitchen has all the latest appliances.",
  mood: "The sunny weather put everyone in a good mood.",
  mouse: "The small mouse scurried across the kitchen floor.",
  mud: "The children loved splashing through the mud puddles.",
  multiply: "She learned to multiply large numbers in her head.",
  murder: "The detective worked tirelessly to solve the murder.",
  mystery: "The missing necklace remained a complete mystery.",
  nail: "She hammered a nail into the wall to hang the picture.",
  narrow: "The narrow path wound through the dense forest.",
  nature: "She enjoys spending time in nature on weekends.",
  needle: "She threaded the needle to sew the torn button.",
  neither: "Neither answer is correct; try again.",
  nephew: "Her nephew is learning to ride a bicycle.",
  nerve: "Public speaking can be a real test of nerve.",
  nest: "The bird built a nest high up in the tree.",
  net: "The fisherman cast his net into the sea.",
  noble: "The noble knight defended the kingdom.",
  noon: "We eat lunch at noon every day.",
  normal: "The temperature returned to normal after the cold snap.",
  novel: "She read a novel during her vacation.",
  nurse: "The nurse checked her blood pressure.",
  object: "A strange object appeared in the night sky.",
  observe: "The scientist paused to observe the animal's behavior.",
  officer: "The police officer directed traffic at the intersection.",
  operate: "She learned how to operate the new machine.",
  opinion: "Everyone is entitled to their own opinion.",
  opposite: "The bank is on the opposite side of the street.",
  original: "The original painting hangs in a museum.",
  oven: "She preheated the oven to bake the cookies.",
  owner: "The owner of the shop greeted every customer warmly.",
  pack: "She helped pack the boxes for the move.",
  pain: "The pain in her ankle went away after she rested.",
  paint: "She used bright colors to paint the landscape.",
  palace: "The royal palace was surrounded by beautiful gardens.",
  parent: "Every parent wants the best for their children.",
  partner: "She danced with her partner at the school formal.",
  passage: "She read a passage from her favorite book aloud.",
  patient: "The doctor was very patient with the nervous child.",
  pause: "She took a brief pause before answering the question.",
  perform: "The musicians will perform at the festival tonight.",
  permit: "You need a permit to fish in this lake.",
  photograph: "The photograph captured a beautiful moment in time.",
  phrase: "She memorized a useful phrase in the new language.",
  pile: "There was a pile of leaves in the backyard.",
  pin: "She used a pin to fasten the ribbon to her dress.",
  pink: "The sunset turned the clouds a soft shade of pink.",
  pipe: "Water flows through the pipe to the kitchen sink.",
  pity: "It would be a pity to miss such a great opportunity.",
  planet: "Earth is the third planet from the sun.",
  pleasure: "It was a pleasure to meet you at the event.",
  plenty: "There is plenty of food for everyone at the picnic.",
  poem: "She wrote a beautiful poem about the changing seasons.",
  poison: "The berries are bright red but contain poison.",
  police: "The police arrived quickly at the scene.",
  polish: "She used a cloth to polish the silver spoons.",
  polite: "It is important to be polite to everyone you meet.",
  pool: "The children splashed happily in the swimming pool.",
  position: "She earned a leadership position in the club.",
  pot: "She filled the pot with water to boil pasta.",
  potato: "The baked potato was topped with butter and cheese.",
  praise: "The teacher gave praise for the excellent report.",
  pray: "Many families gather to pray together before meals.",
  present: "She opened the present with great excitement.",
  pretend: "The children like to pretend they are pirates.",
  prevent: "Wearing a helmet can prevent serious head injuries.",
  pride: "She felt a deep sense of pride in her work.",
  prince: "The prince lived in a magnificent castle.",
  princess: "The princess wore a beautiful silver gown.",
  prison: "The old fortress was once used as a prison.",
  private: "The garden is on private property.",
  prize: "She won first prize at the science fair.",
  proof: "The detective gathered proof to solve the case.",
  proud: "Her parents were very proud of her accomplishments.",
  pump: "She used a pump to inflate the bicycle tire.",
  punish: "The teacher chose not to punish the honest student.",
  pupil: "Every pupil in the class received a certificate.",
  pure: "The mountain stream had clear, pure water.",
  rabbit: "The white rabbit hopped through the garden.",
  rapid: "The rapid growth of the city surprised everyone.",
  rare: "The rare bird was spotted for the first time in years.",
  rate: "The interest rate dropped to an all-time low.",
  raw: "She prefers to eat raw vegetables in a salad.",
  reduce: "Recycling helps reduce the amount of waste.",
  refuse: "She had to refuse the invitation due to a prior commitment.",
  regret: "She didn't regret her decision to study abroad.",
  regular: "He follows a regular exercise routine.",
  relate: "She could relate to the character in the story.",
  release: "The zoo plans to release the healed eagle back into the wild.",
  religion: "People around the world practice many different religions.",
  remain: "Please remain seated until the bus comes to a stop.",
  remind: "This song always reminds me of summer.",
  remove: "Please remove your shoes before entering the house.",
  rent: "They pay rent for their apartment every month.",
  repair: "The mechanic was able to repair the car quickly.",
  replace: "We need to replace the broken window.",
  reply: "She waited eagerly for a reply to her letter.",
  request: "The teacher approved the student's request.",
  require: "The recipe requires three cups of flour.",
  rescue: "The lifeguard was trained to rescue swimmers in trouble.",
  respect: "Treat everyone with kindness and respect.",
  responsible: "She is responsible for feeding the class pet.",
  reveal: "The magician was about to reveal the secret trick.",
  reward: "Her hard work earned her a well-deserved reward.",
  rice: "She cooked a pot of fluffy white rice for dinner.",
  risk: "Wearing a seatbelt reduces the risk of injury.",
  rob: "The police caught the person who tried to rob the store.",
  rough: "The road surface was rough and bumpy.",
  royal: "The royal family waved to the crowd from the balcony.",
  rub: "She used lotion to rub her dry hands.",
  rude: "It is rude to interrupt someone while they are speaking.",
  ruin: "The rain could ruin the outdoor wedding.",
  rush: "She was in a rush to get to the airport on time.",
  sad: "The sad movie made everyone in the audience cry.",
  sample: "The bakery offered a free sample of their new bread.",
  satisfy: "The delicious meal was enough to satisfy everyone.",
  scale: "She used a scale to weigh the package.",
  seek: "She decided to seek advice from her teacher.",
  select: "Please select one item from the menu.",
  separate: "She put the dark and light clothes in separate piles.",
  severe: "The severe thunderstorm knocked down several trees.",
  shade: "They rested in the shade of the large tree.",
  shadow: "Her shadow grew longer as the sun went down.",
  shake: "She gave the bottle a good shake before opening it.",
  shame: "It would be a shame to waste such a beautiful day.",
  sharp: "The sharp knife cut through the bread easily.",
  sheet: "She changed the sheet on the bed every week.",
  shelf: "Put the books back on the shelf when you are done.",
  shelter: "The hikers found shelter from the rain under a rock.",
  shock: "The surprise announcement came as quite a shock.",
  silk: "The dress was made of smooth, shiny silk.",
  silly: "The silly joke made the whole class laugh.",
  skirt: "She wore a plaid skirt to the school dance.",
  slave: "The abolitionists fought to free every slave.",
  slide: "The children loved going down the slide at the playground.",
  smooth: "The lake's surface was perfectly smooth like glass.",
  snake: "A harmless garden snake slithered through the grass.",
  soap: "She washed her hands with soap and warm water.",
  society: "A healthy society values education for all.",
  sock: "She found a missing sock behind the dryer.",
  solve: "The detective worked hard to solve the mystery.",
  spare: "Do you have a spare pencil I can borrow?",
  spell: "Can you spell the word correctly?",
  spider: "A small spider spun a web in the corner.",
  spirit: "The team showed great spirit during the game.",
  split: "They agreed to split the cost of the gift.",
  sport: "Soccer is her favorite sport to play.",
  stamp: "She put a stamp on the envelope before mailing it.",
  steady: "Keep the camera steady while taking the picture.",
  steam: "Steam rose from the cup of hot cocoa.",
  steep: "The steep hill was difficult to climb.",
  stiff: "The new shoes felt stiff until she broke them in.",
  stomach: "She had a stomach ache from eating too much candy.",
  stranger: "Never accept rides from a stranger.",
  strength: "Lifting weights helps build muscle strength.",
  stretch: "Always stretch before you start exercising.",
  strike: "Lightning can strike the tallest point in the area.",
  string: "She tied the package with a piece of string.",
  strip: "She cut a thin strip of paper for the craft project.",
  struggle: "The baby bird had to struggle to leave the nest.",
  stupid: "It was a stupid mistake that could have been avoided.",
  succeed: "If you work hard, you will succeed.",
  success: "The play was a huge success with the audience.",
  suffer: "No animal should have to suffer unnecessarily.",
  suit: "He wore a dark suit to the job interview.",
  supply: "The store has a large supply of school materials.",
  support: "Her friends gave her great support during the competition.",
  suppose: "I suppose we could try a different approach.",
  surface: "The surface of the lake was perfectly smooth.",
  surround: "Tall mountains surround the quiet valley.",
  suspect: "The police identified a suspect in the case.",
  swallow: "The bird was about to swallow the small insect.",
  swear: "I swear I saw a shooting star last night.",
  sword: "The knight drew his sword from its sheath.",
  sympathy: "She expressed her deepest sympathy to the family.",
  talent: "She has a natural talent for playing the piano.",
  tax: "The sales tax was added to the total bill.",
  tear: "A single tear rolled down her cheek during the movie.",
  telephone: "The telephone rang just as she was leaving.",
  temperature: "The temperature outside dropped below freezing.",
  temple: "The ancient temple was carved into the mountainside.",
  tend: "She tends to arrive early for every appointment.",
  tent: "They set up the tent at the campsite.",
  term: "The school term begins in September.",
  terrible: "The terrible storm damaged many homes in the area.",
  thirst: "After the long run, her thirst was overwhelming.",
  thread: "She pulled a thread from the unraveling sweater.",
  throat: "The cold weather made her throat feel sore.",
  thumb: "She accidentally hit her thumb with the hammer.",
  thunder: "The rumble of thunder warned of the approaching storm.",
  ticket: "She bought a ticket for the evening concert.",
  tight: "The lid was too tight for her to open.",
  tip: "He left a generous tip for the waiter.",
  tire: "The front tire of the car needed to be replaced.",
  title: "The title of the book caught her attention.",
  tongue: "She burned her tongue on the hot soup.",
  tooth: "Her baby lost his first tooth this week.",
  tough: "The steak was a bit tough but still tasty.",
  tower: "The tall tower could be seen from miles away.",
  tradition: "It is a family tradition to eat together on holidays.",
  traffic: "Heavy traffic made the morning commute very slow.",
  trap: "The hunter set a trap for the wild animal.",
  treat: "Ice cream after dinner is a special treat.",
  trial: "The trial lasted three days in the courthouse.",
  trick: "The magician performed an amazing card trick.",
  trouble: "She got in trouble for talking during the test.",
  tube: "Squeeze the tube gently to get the toothpaste out.",
  tunnel: "The train traveled through a long dark tunnel.",
  ugly: "The ugly duckling grew into a beautiful swan.",
  umbrella: "Don't forget your umbrella; it might rain.",
  union: "The workers formed a union to protect their rights.",
  universe: "The universe contains billions of galaxies.",
  unless: "We will go to the park unless it rains.",
  upper: "She reached for the book on the upper shelf.",
  upset: "She was upset when she lost her favorite bracelet.",
  variety: "The garden has a wide variety of colorful flowers.",
  various: "They tried various solutions before finding the right one.",
  vegetable: "Eating a vegetable with every meal is important.",
  vehicle: "A large vehicle blocked the narrow road.",
  victory: "The team celebrated their hard-fought victory.",
  view: "The view from the mountaintop was breathtaking.",
  village: "The small village had only a hundred residents.",
  violent: "The violent storm uprooted several large trees.",
  wage: "The minimum wage was recently increased.",
  wake: "She set an alarm to wake up early for the hike.",
  wealth: "True wealth is not measured by money alone.",
  weapon: "The ancient weapon was displayed in the museum.",
  wedding: "The wedding ceremony was held in a beautiful garden.",
  whisper: "She leaned in to whisper a secret to her friend.",
  whistle: "The referee blew the whistle to start the game.",
  willing: "She is always willing to help others.",
  wing: "The bird spread its wing and took flight.",
  wise: "The wise teacher shared valuable life lessons.",
  wool: "The sweater was knitted from soft wool.",
  wound: "The nurse carefully bandaged the wound.",
  wrist: "She wore a friendship bracelet on her wrist.",
  zone: "The speed limit in the school zone is twenty miles per hour.",
  zoo: "The children loved seeing the animals at the zoo.",
};

export default COMMON2_SENTENCES;
