/**
 * Curated sentences for Level 5 (Rare) words not already covered.
 */
const RARE_SENTENCES: Record<string, string> = {
  abjure: "He chose to abjure his old habits and start fresh.",
  abnegate: "The monk vowed to abnegate all worldly possessions.",
  abnegation: "Her abnegation of personal comfort for others was admirable.",
  abscond: "The thief tried to abscond with the stolen jewels.",
  absquatulate: "He decided to absquatulate before anyone noticed he was gone.",
  abstruse: "The philosopher's writing was so abstruse that few understood it.",
  acciaccatura: "The pianist added an acciaccatura to embellish the melody.",
  acephalous: "The acephalous organization lacked a clear leader.",
  acerbic: "Her acerbic wit could make even the sternest person laugh.",
  acquiescent: "He was acquiescent and agreed without argument.",
  acquisitive: "The acquisitive collector sought rare paintings worldwide.",
  adscititious: "The adscititious details were added later to the manuscript.",
  adulterate: "It is illegal to adulterate food products with harmful substances.",
  adventitious: "The adventitious discovery changed the course of research.",
  affectation: "Her British accent was merely an affectation.",
  agelast: "The agelast sat stone-faced while everyone else laughed.",
  agglutination: "Agglutination is the process of combining word parts.",
  aggrandize: "He sought to aggrandize his reputation at every opportunity.",
  ailurophile: "As a devoted ailurophile, she owned five cats.",
  alacritous: "The alacritous student eagerly volunteered for every task.",
  alacrity: "She accepted the invitation with great alacrity.",
  alcazar: "The ancient alcazar stood proudly atop the hill.",
  aleatory: "The composer used aleatory techniques based on chance.",
  alexipharmic: "The herbalist claimed the potion had alexipharmic properties.",
  alexithymia: "Alexithymia is the inability to identify one's own emotions.",
  altruism: "Her altruism was evident in her tireless volunteer work.",
  amalgam: "The final result was an amalgam of different ideas.",
  amanuensis: "The author dictated the novel to her amanuensis.",
  amaranthine: "The garden was filled with amaranthine beauty that never faded.",
  ambrosia: "The dessert was so delicious it tasted like ambrosia.",
  ambsace: "Rolling ambsace in dice means getting double ones.",
  ameliorate: "New policies were introduced to ameliorate working conditions.",
  amphigory: "The poem was a delightful amphigory of nonsensical verse.",
  amphisbaena: "The amphisbaena is a mythical serpent with a head at each end.",
  anachronism: "A telephone in a medieval movie is an obvious anachronism.",
  anagnorisis: "The protagonist's anagnorisis came in the final chapter.",
  analeptic: "The strong coffee served as an analeptic after the long night.",
  anamorphosis: "The painting used anamorphosis to create a hidden image.",
  anastrophe: "The poet used anastrophe to invert the usual word order.",
  anathema: "Cheating is anathema to anyone who values fair play.",
  anfractuous: "The anfractuous path wound through the dense forest.",
  anguilliform: "The eel has an anguilliform body shaped like a snake.",
  anodyne: "The speech was pleasant but anodyne, lacking real substance.",
  antediluvian: "His antediluvian views on technology were charmingly outdated.",
  anthropomorphism: "Giving human traits to animals is called anthropomorphism.",
  antinomy: "The antinomy between the two laws puzzled the legal scholars.",
  antiphrasis: "Calling a tiny dog Hercules is an example of antiphrasis.",
  antithesis: "Cruelty is the antithesis of kindness.",
  aphorism: "He was fond of quoting the aphorism about early birds.",
  aplomb: "She handled the crisis with remarkable aplomb.",
  aposiopesis: "The speaker's aposiopesis left the audience in suspense.",
  apotheosis: "The final concert was the apotheosis of her career.",
  apotropaic: "The charm was believed to have apotropaic powers against evil.",
  approbation: "The project received the approbation of the entire committee.",
  aquiline: "The eagle's aquiline profile was striking against the sky.",
  arboreal: "Monkeys are arboreal creatures that live in trees.",
  arcane: "The old book contained arcane knowledge of forgotten rituals.",
  archetype: "The wise mentor is a common archetype in literature.",
  ardent: "She was an ardent supporter of the local arts program.",
  arriviste: "The arriviste tried to impress everyone with his new wealth.",
  asperity: "She spoke with unusual asperity when questioned.",
  aspersion: "He cast an aspersion on her character without any proof.",
  asseverate: "She would asseverate her innocence to anyone who would listen.",
  assiduous: "His assiduous study habits earned him the top grade.",
  ataraxia: "The philosopher sought ataraxia through meditation.",
  atavism: "The behavior seemed like an atavism from a distant ancestor.",
  attenuate: "The thick walls helped attenuate the outside noise.",
  audacity: "She had the audacity to challenge the champion to a rematch.",
  augment: "She took a second job to augment her income.",
  auspice: "The festival was held under the auspice of the local council.",
  autodidact: "As an autodidact, she learned to code entirely on her own.",
  avuncular: "The avuncular teacher always had kind advice for his students.",
  axiom: "It is an axiom that practice makes perfect.",
  bacchanalia: "The wild celebration resembled an ancient bacchanalia.",
  bathetic: "The sentimental ending was almost bathetic in its excess.",
  batrachian: "The biologist studied batrachian species in the wetlands.",
  beatific: "A beatific smile spread across the child's face.",
  beguile: "The storyteller could beguile audiences for hours.",
  behemoth: "The ancient behemoth towered over the surrounding buildings.",
  beleaguer: "Problems continued to beleaguer the struggling company.",
  bellicose: "His bellicose attitude made negotiation impossible.",
  bellwether: "The school is considered a bellwether for educational trends.",
  beneficent: "The beneficent ruler improved the lives of all citizens.",
  benign: "The doctor confirmed that the growth was benign.",
  besmirch: "He refused to besmirch the reputation of his colleague.",
  bibliopole: "The bibliopole specialized in rare first editions.",
  bifurcate: "The river began to bifurcate into two smaller streams.",
  bijouterie: "The shop displayed exquisite bijouterie in its window.",
  bilious: "The bumpy boat ride left him feeling bilious.",
  blandishment: "No amount of blandishment could change her mind.",
  blasphemy: "The remark was considered blasphemy by the devout community.",
  blithe: "She went about her day with a blithe disregard for worry.",
  bombastic: "His bombastic speech was full of grand but empty promises.",
  borborygmus: "The quiet room amplified the embarrassing borborygmus from his stomach.",
  bourgeois: "The satirical novel mocked bourgeois attitudes toward art.",
  brummagem: "The jewelry turned out to be brummagem and worthless.",
  bruxism: "The dentist noticed signs of bruxism from grinding teeth.",
  bucolic: "The bucolic landscape of rolling hills was deeply peaceful.",
  bumptious: "The bumptious young man interrupted everyone at the table.",
  byzantine: "The byzantine regulations were nearly impossible to navigate.",
  cabal: "A secretive cabal plotted behind closed doors.",
  cachinnation: "Her uncontrollable cachinnation echoed through the theater.",
  cacoethes: "He had a cacoethes for collecting obscure vocabulary words.",
  cacophony: "The cacophony of horns and sirens filled the busy street.",
  cadence: "The cadence of her voice was soothing and melodic.",
  cajole: "She tried to cajole him into attending the party.",
  callipygian: "The Greek sculpture featured a callipygian figure.",
  calumny: "The politician was the victim of vicious calumny.",
  camisade: "The surprise camisade caught the enemy off guard at night.",
  canard: "The rumor turned out to be nothing more than a canard.",
  canticle: "The choir sang a beautiful canticle during the service.",
  capacious: "The capacious trunk could hold all the luggage.",
  capitulation: "The army's capitulation ended the long siege.",
  capriciousness: "The capriciousness of the weather made planning difficult.",
  captious: "The captious critic found fault with every performance.",
  carouse: "The revelers continued to carouse until the early hours.",
  castigate: "The editorial was written to castigate the corrupt officials.",
  casuistry: "The lawyer's casuistry twisted the facts to suit his case.",
  catachresis: "Using a word in a deliberately wrong way is catachresis.",
  cataclysm: "The volcanic eruption was a cataclysm that reshaped the island.",
  catalepsy: "The patient experienced a brief episode of catalepsy.",
  catenation: "Carbon's ability for catenation allows complex molecules to form.",
  catharsis: "Writing in her journal provided a much-needed emotional catharsis.",
  causality: "The scientist studied the causality between the two events.",
  cavalier: "His cavalier attitude toward deadlines frustrated his teammates.",
  cenacle: "The literary cenacle met weekly to discuss new works.",
  censure: "The committee voted to censure the member for misconduct.",
  cerulean: "The cerulean sky was perfectly clear and cloudless.",
  chagrin: "Much to her chagrin, she forgot the words to the song.",
  charlatan: "The man turned out to be a charlatan with fake credentials.",
  chiaroscuro: "The painting used chiaroscuro to create dramatic shadows.",
  chimera: "The plan for perpetual motion was nothing but a chimera.",
  chrysalis: "The caterpillar transformed inside its chrysalis.",
  churlish: "It would be churlish to refuse such a generous offer.",
  cicatrix: "The old cicatrix on his arm reminded him of the accident.",
  circuitous: "They took a circuitous route to avoid the traffic.",
  clairvoyant: "The clairvoyant claimed to see visions of the future.",
  clemency: "The prisoner petitioned the governor for clemency.",
  clerisy: "The clerisy of scholars debated the new theory.",
  clinquant: "The clinquant decorations sparkled under the ballroom lights.",
  coagulate: "The blood began to coagulate around the wound.",
  cochineal: "The vibrant red dye was made from cochineal insects.",
  coda: "The musical piece ended with a beautiful coda.",
  codify: "The committee worked to codify the new rules into law.",
  cogent: "She presented a cogent argument that convinced the jury.",
  cogitate: "He sat quietly to cogitate on the difficult problem.",
  colloquy: "The scholars engaged in a thoughtful colloquy about ethics.",
  collusion: "The companies were found guilty of collusion to fix prices.",
  colophon: "The publisher's colophon appeared on the last page of the book.",
  comestible: "Every comestible at the banquet was prepared from scratch.",
  comity: "International comity requires nations to respect each other's laws.",
  commencement: "The commencement ceremony celebrated the graduating class.",
  commiserate: "Friends gathered to commiserate after the team's loss.",
  compunction: "She felt no compunction about telling the truth.",
  compurgation: "Compurgation was an old legal practice relying on character witnesses.",
  concatenate: "The programmer needed to concatenate the two strings.",
  concatenation: "The concatenation of events led to an unexpected outcome.",
  concentric: "The target had concentric circles radiating from the center.",
  conciliator: "The skilled conciliator helped resolve the labor dispute.",
  concrescence: "The biologist studied the concrescence of cellular structures.",
  condign: "The punishment was condign and fit the severity of the offense.",
  confabulate: "The old friends would confabulate for hours over tea.",
  conflagration: "The conflagration destroyed an entire block of buildings.",
  congenial: "The congenial atmosphere made everyone feel comfortable.",
  congruence: "There was a clear congruence between the two theories.",
  connivance: "The plan succeeded only through the connivance of insiders.",
  consanguinity: "Their consanguinity was traced back several generations.",
  consternation: "The announcement caused great consternation among the staff.",
  consuetude: "The local consuetude dictated how the festival was celebrated.",
  consummate: "She was a consummate professional in every sense of the word.",
  contravene: "The regulation was found to contravene existing laws.",
  contretemps: "A minor contretemps delayed the start of the meeting.",
  contrite: "He was genuinely contrite after realizing his error.",
  contumacious: "The contumacious witness refused to answer the questions.",
  contumely: "She endured the contumely of her critics with dignity.",
  conundrum: "The math puzzle presented a difficult conundrum.",
  convivial: "The convivial gathering was full of laughter and good food.",
  copacetic: "Everything was copacetic once the misunderstanding was cleared up.",
  corollary: "A natural corollary of exercise is improved health.",
  corporeal: "The artist sought to capture corporeal beauty in marble.",
  corpulent: "The corpulent king was known for his lavish feasts.",
  corrosion: "Salt water accelerates the corrosion of metal surfaces.",
  coruscate: "The diamonds seemed to coruscate under the bright lights.",
  cosset: "She would cosset the puppy with treats and blankets.",
  coterie: "The writer was part of a coterie of artists in the city.",
  countenance: "She maintained a calm countenance throughout the ordeal.",
  crepitate: "The dry leaves crepitate underfoot on the autumn path.",
  crepuscular: "Many animals are crepuscular, active at dawn and dusk.",
  crucible: "The experience was a crucible that tested her resolve.",
  cryptic: "The ancient inscription was cryptic and hard to decipher.",
  cupidity: "His cupidity led him to make unethical business deals.",
  curmudgeon: "The old curmudgeon grumbled about everything under the sun.",
  cynosure: "The lead actress was the cynosure of all eyes at the premiere.",
  dalliance: "The summer dalliance ended when school began again.",
  debacle: "The canceled event was a complete debacle for the organizers.",
  debonair: "The debonair gentleman charmed everyone at the gala.",
  decadent: "The decadent chocolate cake was impossibly rich.",
  declivity: "The ball rolled down the gentle declivity of the hill.",
  decrepitude: "The building's decrepitude made it unsafe to enter.",
  defalcate: "The accountant was caught trying to defalcate company funds.",
  defalcation: "The defalcation of public money led to criminal charges.",
  defenestrate: "Legend says the diplomats were defenestrated from the castle window.",
  deipnosophist: "The witty deipnosophist entertained everyone at the dinner table.",
  deleterious: "Smoking has a deleterious effect on your health.",
  delineate: "The map helped delineate the boundaries of the property.",
  demagogic: "The demagogic speech appealed to fear rather than reason.",
  demijohn: "The old demijohn was used to store homemade wine.",
  demurral: "His demurral was noted but the plan went ahead anyway.",
  denouement: "The novel's denouement tied up all the loose ends.",
  deontology: "Deontology is an ethical theory based on duty and rules.",
  deprecate: "She did not mean to deprecate his efforts.",
  deride: "It is unkind to deride someone for their mistakes.",
  descant: "The soprano sang a lovely descant above the main melody.",
  desideratum: "Clean air is a desideratum for public health.",
  desultory: "The conversation was desultory, jumping from topic to topic.",
  diablerie: "The novel was full of supernatural diablerie.",
  diacritical: "The diacritical mark changed the pronunciation of the letter.",
  diapason: "The organ's deep diapason filled the entire cathedral.",
  diaphanous: "She wore a diaphanous scarf that floated in the breeze.",
  diaspora: "The diaspora spread the culture across many countries.",
  diatribe: "He launched into a bitter diatribe against the new policy.",
  didactic: "The fable had a didactic purpose, teaching a moral lesson.",
  diktat: "The unpopular diktat was imposed without any discussion.",
  dilatory: "His dilatory response to the invitation came too late.",
  dirigisme: "The government practiced economic dirigisme to control industry.",
  disabuse: "She tried to disabuse him of the false notion.",
  discomfit: "The tough question was enough to discomfit the panelist.",
  disconsolate: "The disconsolate child cried after losing her toy.",
  discursive: "His discursive essay wandered from one topic to the next.",
  dishabille: "She answered the door in a state of casual dishabille.",
  disingenuous: "His apology seemed disingenuous and insincere.",
  disparate: "The committee members had disparate views on the issue.",
  disquisition: "The professor delivered a lengthy disquisition on ancient Rome.",
  dissemble: "He tried to dissemble his true feelings with a forced smile.",
  dissonance: "The dissonance of the chords created an unsettling mood.",
  doctrinaire: "His doctrinaire approach left no room for flexibility.",
  dolorous: "The dolorous melody brought tears to the audience's eyes.",
  donnybrook: "The debate devolved into a verbal donnybrook.",
  doppelganger: "She met her doppelganger at the conference and did a double take.",
  doughty: "The doughty explorer braved the harshest conditions.",
  dulcimer: "She played a hauntingly beautiful tune on the dulcimer.",
  ebullience: "Her ebullience was infectious and lifted everyone's spirits.",
  ebullient: "The ebullient crowd cheered wildly when the team scored.",
  ecclesiastical: "The ecclesiastical architecture of the church was stunning.",
  echolalia: "Echolalia involves the repetition of words just spoken by another.",
  ecumenical: "The ecumenical service brought together people of many faiths.",
  edification: "The lecture was presented for the edification of the audience.",
  effervescent: "Her effervescent personality brightened every room she entered.",
  effete: "The once-powerful empire had become effete and weak.",
  effigy: "They burned an effigy during the traditional festival.",
  effrontery: "She had the effrontery to complain about the free meal.",
  effulgent: "The effulgent sunrise painted the sky in brilliant colors.",
  egregious: "The egregious error in the report needed immediate correction.",
  eidetic: "His eidetic memory allowed him to recall every detail perfectly.",
  eleemosynary: "The eleemosynary institution provided shelter for the homeless.",
  elegy: "The poet wrote a moving elegy for a departed friend.",
  elide: "Speakers often elide vowel sounds in rapid conversation.",
  elocution: "She took elocution lessons to improve her public speaking.",
  emaciate: "The long illness began to emaciate the once robust man.",
  emissary: "The king sent an emissary to negotiate the peace treaty.",
  emollient: "She applied an emollient cream to soothe her dry skin.",
  emolument: "The position included a generous emolument and benefits.",
  encomium: "The retiring teacher received a heartfelt encomium from the principal.",
  ennui: "A feeling of ennui settled over her during the long afternoon.",
  ensconce: "She ensconced herself in the comfortable armchair with a book.",
  ensorcell: "The witch's spell was meant to ensorcell the entire kingdom.",
  entelechy: "The philosopher spoke of entelechy as the realization of potential.",
  entropy: "Entropy causes all systems to tend toward disorder over time.",
  epaulet: "The military officer's uniform had gold braid on each epaulet.",
  epicurean: "The epicurean feast featured rare delicacies from around the world.",
  epigram: "Oscar Wilde was famous for his clever epigrams.",
  epistolary: "The novel was written in an epistolary form using letters.",
  equivocate: "The politician tried to equivocate when asked a direct question.",
  erudite: "The erudite scholar had read thousands of books.",
  escheat: "Unclaimed property may escheat to the state after many years.",
  etiolate: "Plants kept in the dark will etiolate and lose their color.",
  etiology: "The etiology of the disease was traced to a viral infection.",
  etude: "She practiced a difficult piano etude by Chopin.",
  eulogize: "Friends gathered to eulogize the beloved community leader.",
  euphonious: "The euphonious melody filled the concert hall with beauty.",
  euphoria: "She felt a wave of euphoria after crossing the finish line.",
  evanescence: "The evanescence of the morning mist gave the scene a dreamlike quality.",
  evanescent: "The evanescent rainbow faded within moments.",
  excoriate: "The critic proceeded to excoriate the poorly written novel.",
  exculpate: "The new evidence was enough to exculpate the suspect.",
  execrable: "The food at the roadside stand was truly execrable.",
  execrate: "The townspeople would execrate the villain in the old play.",
  exegesis: "The scholar provided a detailed exegesis of the ancient text.",
  exigency: "The exigency of the situation required immediate action.",
  exiguous: "The exiguous budget barely covered the essential expenses.",
  existential: "The novel explored deep existential questions about meaning.",
  expatiate: "The professor liked to expatiate on topics he found fascinating.",
  expiate: "He sought to expiate his guilt by doing community service.",
  expunge: "The court ordered that the record be expunged.",
  expurgate: "The publisher chose to expurgate offensive passages from the book.",
  extant: "Very few extant copies of the original manuscript survive.",
  extemporize: "She had to extemporize when her notes went missing.",
  extrapolate: "From the data, scientists can extrapolate future trends.",
  facile: "The facile explanation glossed over the real complexity.",
  farinaceous: "Bread and pasta are farinaceous foods made from flour.",
  fatuous: "His fatuous remarks added nothing to the discussion.",
  febrile: "The child's febrile condition required immediate medical attention.",
  feckless: "The feckless manager failed to address any of the complaints.",
  felicitous: "Her felicitous choice of words made the toast memorable.",
  feuilleton: "The newspaper published a literary feuilleton every Sunday.",
  fibula: "She fractured her fibula while skiing down the mountain.",
  filigree: "The silver necklace featured delicate filigree work.",
  flagitious: "The flagitious crime shocked the entire community.",
  flippant: "His flippant remark was inappropriate given the seriousness of the situation.",
  floccinaucinihilipilification: "Floccinaucinihilipilification is the act of estimating something as worthless.",
  flocculate: "The chemical caused the particles in the water to flocculate.",
  foofaraw: "The whole foofaraw over the seating arrangement seemed silly.",
  fortuitous: "Their meeting was entirely fortuitous and unplanned.",
  frangible: "The frangible vase shattered when it fell from the shelf.",
  fugacious: "The fugacious beauty of the cherry blossoms lasted only days.",
  fulcrum: "The seesaw pivots on its fulcrum in the middle.",
  fulminate: "The senator began to fulminate against the proposed legislation.",
  fusillade: "A fusillade of questions greeted the spokesperson.",
  gallivant: "She spent the summer gallivanting across Europe.",
  garrulous: "The garrulous neighbor could talk for hours without stopping.",
  gasconade: "His gasconade about his accomplishments bored everyone at dinner.",
  genuflect: "The worshippers genuflect before entering the pew.",
  gerrymander: "Politicians sometimes gerrymander districts to gain advantage.",
  glossolalia: "The phenomenon of speaking in tongues is called glossolalia.",
  gnomic: "The philosopher's gnomic utterances were difficult to interpret.",
  gnosis: "The ancient sect claimed to possess secret spiritual gnosis.",
  grandiloquent: "His grandiloquent speech was impressive but ultimately hollow.",
  gravamen: "The gravamen of the complaint was the breach of contract.",
  gubernatorial: "The gubernatorial race attracted national attention.",
  guerdon: "The knight received a guerdon for his valiant service.",
  gustatory: "The meal provided a delightful gustatory experience.",
  hagiographer: "The hagiographer wrote detailed accounts of the saints' lives.",
  hagiography: "The book read more like hagiography than objective biography.",
  halcyon: "She often reminisced about the halcyon days of her youth.",
  hamartia: "The hero's hamartia was his excessive pride.",
  hapax: "The word appeared only once in the entire text, making it a hapax.",
  hegemony: "The empire maintained hegemony over the entire region.",
  heliotrope: "The heliotrope flowers turned to follow the path of the sun.",
  hendiadys: "The phrase nice and warm is an example of hendiadys.",
  hermeneutic: "A hermeneutic approach was used to interpret the ancient texts.",
  heterodox: "Her heterodox views challenged the established consensus.",
  heuristic: "The teacher used a heuristic method to guide student discovery.",
  hieroglyphic: "The wall was covered in ancient hieroglyphic writing.",
  histrionic: "Her histrionic reaction to the minor setback was unnecessary.",
  hobbledehoy: "The gangly hobbledehoy tripped over his own feet.",
  holistic: "The clinic takes a holistic approach to patient wellness.",
  homily: "The pastor delivered a thoughtful homily about compassion.",
  homologous: "The wing of a bat and the arm of a human are homologous structures.",
  hortatory: "The coach gave a hortatory speech to motivate the team.",
  hubris: "The villain's hubris led to his spectacular downfall.",
  hypostatize: "Philosophers warn against the tendency to hypostatize abstract concepts.",
  iamb: "An iamb is a metrical foot with an unstressed then stressed syllable.",
  ichor: "In mythology, ichor flowed through the veins of the gods.",
  iconoclastic: "Her iconoclastic approach to art challenged every convention.",
  idiosyncratic: "His idiosyncratic teaching style made every class unique.",
  ignominy: "The scandal brought ignominy upon the entire organization.",
  imbroglio: "The diplomatic imbroglio took months to resolve.",
  immolate: "The ancient ceremony was said to immolate offerings to the gods.",
  immutable: "The laws of physics are considered immutable.",
  impassive: "She remained impassive despite the provocation.",
  impecunious: "The impecunious student worked two jobs to pay tuition.",
  impenetrable: "The dense forest formed an almost impenetrable barrier.",
  imperious: "The imperious queen demanded absolute obedience.",
  implacable: "The implacable opponent refused to back down.",
  imprecation: "The angry crowd hurled imprecations at the departing officials.",
  impregnable: "The medieval fortress was considered impregnable.",
  imprimatur: "The project received the imprimatur of the board of directors.",
  improvident: "His improvident spending left him with no savings.",
  impugn: "She refused to impugn the integrity of her colleague.",
  impunity: "The criminals acted with impunity, believing they would not be caught.",
  inchoate: "The plan was still inchoate and needed much more development.",
  incipient: "The doctor detected the incipient signs of the illness early.",
  incognito: "The celebrity traveled incognito to avoid being recognized.",
  incorruptible: "The incorruptible judge was admired by everyone.",
  incredulous: "She was incredulous when she heard the unbelievable news.",
  incunabulum: "The rare incunabulum was printed before the year 1501.",
  indefatigable: "The indefatigable volunteer worked from dawn until dusk.",
  indelible: "The trip left an indelible impression on her memory.",
  indite: "The poet was inspired to indite a sonnet about the sunset.",
  indolent: "The indolent cat lay in the sunbeam all day long.",
  ineffable: "The beauty of the aurora borealis was truly ineffable.",
  ineluctable: "The ineluctable passage of time changes everything.",
  inexorable: "The inexorable march of progress cannot be stopped.",
  infernal: "The infernal noise from the construction site lasted all day.",
  ingeminate: "The preacher would ingeminate the key themes of his sermon.",
  inimitable: "Her inimitable style of painting was instantly recognizable.",
  inscrutable: "The sphinx wore an inscrutable expression on its face.",
  insouciant: "He walked through the chaos with an insouciant air.",
  inspissate: "Heat was used to inspissate the liquid into a thick syrup.",
  interloper: "The interloper was quickly escorted from the private event.",
  internecine: "The internecine conflict weakened the organization from within.",
  interregnum: "The interregnum between rulers was a period of uncertainty.",
  intractable: "The intractable problem defied every proposed solution.",
  intransigent: "The intransigent negotiator refused to compromise.",
  inveterate: "He was an inveterate reader who devoured books daily.",
  invidious: "Making invidious comparisons between students is harmful.",
  irredentism: "Irredentism seeks to reclaim territory based on historical claims.",
  jactitation: "His constant jactitation about his wealth annoyed everyone.",
  janissary: "The janissary was an elite soldier in the Ottoman army.",
  jejune: "The jejune argument failed to persuade anyone in the audience.",
  jeremiad: "The editorial read like a long jeremiad about modern society.",
  jocund: "The jocund host kept everyone laughing throughout the evening.",
  juxtaposition: "The juxtaposition of old and new buildings was striking.",
  keelhaul: "In the old navy, they would keelhaul disobedient sailors.",
  kenosis: "Kenosis refers to the self-emptying of one's own will.",
  kinesthesia: "Athletes rely on kinesthesia to coordinate their movements.",
  kismet: "Meeting her best friend that day felt like kismet.",
  kvetch: "He tends to kvetch about the weather every winter.",
  labefaction: "The labefaction of the old foundation threatened the building.",
  lachrymose: "The lachrymose film left the entire audience in tears.",
  laconic: "The laconic reply consisted of just one word: no.",
  lacustrine: "The lacustrine ecosystem supported many species of fish.",
  lambent: "The lambent flame of the candle flickered in the darkness.",
  languor: "The tropical heat filled her with a pleasant languor.",
  lascivious: "The novel was criticized for its lascivious content.",
  latitudinarian: "His latitudinarian views welcomed many different perspectives.",
  legerdemain: "The magician's legerdemain amazed the children.",
  lenitive: "The ointment had a lenitive effect on the irritated skin.",
  lexicography: "She devoted her career to lexicography and dictionary-making.",
  licentious: "The satirical play mocked licentious behavior at court.",
  liminal: "The hallway felt like a liminal space between two worlds.",
  limpid: "The limpid water of the mountain spring was crystal clear.",
  lineament: "Every lineament of her face expressed determination.",
  lissome: "The lissome dancer moved with effortless grace.",
  logorrhea: "His tendency toward logorrhea made his speeches interminable.",
  loquacious: "The loquacious guest dominated every conversation.",
  louche: "The louche character lurked in the shadows of the alley.",
  lucubration: "Her late-night lucubration produced a brilliant thesis.",
  lugubrious: "The lugubrious music matched the somber mood of the ceremony.",
  lyceum: "The philosopher taught at the local lyceum.",
  macaronic: "The macaronic poem mixed English with Latin phrases.",
  machination: "The villain's machination was eventually uncovered.",
  magisterial: "The professor delivered a magisterial lecture on Renaissance art.",
  maieutic: "The teacher used a maieutic approach, guiding students with questions.",
  malapropism: "Saying pacific when you mean specific is a common malapropism.",
  malediction: "The witch uttered a terrifying malediction against the kingdom.",
  maleficent: "The maleficent sorcerer cast a dark spell over the land.",
  malinger: "The soldier was accused of trying to malinger to avoid duty.",
  malversation: "The official was charged with malversation of public funds.",
  manumission: "The document granted manumission and freedom to the enslaved.",
  martinet: "The strict martinet demanded perfect obedience from the troops.",
  maudlin: "After a few songs, the evening became somewhat maudlin.",
  megalomania: "The dictator's megalomania led to increasingly irrational decisions.",
  mellifluous: "Her mellifluous voice enchanted the entire audience.",
  mendacious: "The mendacious witness was caught lying under oath.",
  mendicant: "The mendicant monk relied on the charity of strangers.",
  mercurial: "Her mercurial temperament made her reactions unpredictable.",
  meretricious: "The meretricious decorations were flashy but tasteless.",
  militate: "Several factors militate against the success of the plan.",
  mimesis: "Art as mimesis seeks to imitate nature.",
  misanthrope: "The misanthrope preferred solitude to the company of others.",
  miscreant: "The miscreant was caught vandalizing the park bench.",
  mnemonic: "She created a mnemonic device to remember the order of the planets.",
  mollify: "He tried to mollify the upset customer with a sincere apology.",
  moribund: "The moribund industry was in desperate need of innovation.",
  multifarious: "The festival offered multifarious activities for all ages.",
  nacreous: "The nacreous interior of the shell shimmered with iridescence.",
  nadir: "The company's stock reached its nadir before recovering.",
  nascent: "The nascent technology showed tremendous promise.",
  nebulous: "Her plans for the future were still rather nebulous.",
  necromancy: "The sorcerer was said to practice necromancy.",
  nemesis: "The detective finally confronted her long-time nemesis.",
  neologism: "The tech industry constantly produces new neologisms.",
  nihilism: "The philosopher discussed the implications of nihilism.",
  nomenclature: "Scientific nomenclature uses Latin names for species.",
  nonpareil: "Her skills as a surgeon were absolutely nonpareil.",
  nonplussed: "She was completely nonplussed by the unexpected question.",
  noumenon: "Kant distinguished between the phenomenon and the noumenon.",
  noxious: "The noxious fumes from the factory polluted the air.",
  numinous: "Standing in the ancient temple, she felt a numinous presence.",
  obdurate: "The obdurate negotiator refused every compromise.",
  obeisance: "The courtiers made a deep obeisance before the queen.",
  obfuscate: "Complex jargon can obfuscate rather than clarify the meaning.",
  oblique: "She gave an oblique reference to the scandal without naming it.",
  obsequious: "The obsequious assistant agreed with everything the boss said.",
  obstreperous: "The obstreperous crowd was difficult for the police to control.",
  obtuse: "He was being deliberately obtuse about the obvious problem.",
  oleaginous: "The oleaginous surface of the fish glistened in the light.",
  oligarchy: "Power was concentrated in the hands of a small oligarchy.",
  omnipotent: "The mythical deity was believed to be omnipotent.",
  omniscient: "The narrator of the novel was omniscient, knowing every character's thoughts.",
  onerous: "The onerous tax burden fell heavily on small businesses.",
  operose: "The operose task of cataloging the entire library took months.",
  opprobrium: "The scandal brought universal opprobrium upon the company.",
  oscillate: "The pendulum continued to oscillate back and forth steadily.",
  ossify: "Without new ideas, the organization will ossify and stagnate.",
  otiose: "The otiose regulations served no practical purpose.",
  overweening: "His overweening pride prevented him from admitting his mistake.",
  oxymoron: "The phrase deafening silence is a well-known oxymoron.",
  pabulum: "The bland pabulum of the speech put the audience to sleep.",
  paean: "The poem was a paean to the beauty of the natural world.",
  palimpsest: "The ancient palimpsest revealed text hidden beneath newer writing.",
  palliate: "The treatment helped palliate the patient's symptoms.",
  panacea: "There is no single panacea for all of society's problems.",
  panache: "She delivered the performance with flair and panache.",
  panegyric: "The speech was a panegyric honoring the retiring professor.",
  panoply: "A panoply of colors filled the autumn forest.",
  paragon: "She is a paragon of dedication and hard work.",
  pariah: "After the scandal, he became a pariah in the community.",
  parlance: "In legal parlance, the term means something quite specific.",
  parlous: "The company's finances were in a parlous state.",
  parochial: "His parochial views prevented him from seeing the bigger picture.",
  paroxysm: "A sudden paroxysm of coughing interrupted the meeting.",
  parsimony: "His extreme parsimony extended even to turning off all the lights.",
  pastiche: "The film was a clever pastiche of classic detective stories.",
  pathological: "His pathological fear of heights prevented him from flying.",
  paucity: "The paucity of evidence made it hard to draw conclusions.",
  pecuniary: "The lawsuit sought pecuniary damages for the losses.",
  pedagogy: "Effective pedagogy engages students in active learning.",
  pedantic: "His pedantic insistence on minor rules annoyed his colleagues.",
  pejorative: "The word was used in a pejorative sense to insult someone.",
  pellucid: "Her pellucid writing style made complex ideas easy to understand.",
  penurious: "The penurious miser refused to spend a single penny.",
  peregrinate: "The monks would peregrinate from village to village.",
  perfidious: "The perfidious ally betrayed them at the worst possible moment.",
  peripatetic: "The peripatetic lecturer traveled from campus to campus.",
  pernicious: "The pernicious rumor spread quickly through the school.",
  perspicacious: "The perspicacious detective noticed every small clue.",
  pertinacious: "The pertinacious researcher refused to abandon the experiment.",
  pestilence: "The medieval pestilence devastated entire populations.",
  petrichor: "After the rain, the petrichor filled the air with earthy scent.",
  pettifogger: "The pettifogger focused on trivial legal technicalities.",
  petulant: "The petulant child whined about everything.",
  phantasmagoria: "The carnival was a phantasmagoria of lights and sounds.",
  philistine: "The philistine dismissed all modern art as meaningless.",
  philology: "She studied philology to understand the history of language.",
  phlegmatic: "His phlegmatic demeanor remained unchanged even in a crisis.",
  physiognomy: "The artist captured every detail of the subject's physiognomy.",
  picaresque: "The picaresque novel followed the rogue on his many adventures.",
  picayune: "Don't waste time on such picayune matters.",
  plangent: "The plangent sound of the bell echoed across the valley.",
  platonic: "Their relationship was strictly platonic.",
  plebeian: "The aristocrat looked down on what she called plebeian tastes.",
  pleonasm: "Saying free gift is a common pleonasm.",
  plethora: "The store offered a plethora of choices for every shopper.",
  plutocracy: "Critics accused the government of being a plutocracy.",
  polemic: "The article was a fiery polemic against corporate greed.",
  polity: "The polity of the ancient city-state was a direct democracy.",
  polyglot: "The polyglot ambassador spoke six languages fluently.",
  polyphony: "The choir performed a piece of intricate polyphony.",
  pontificate: "He liked to pontificate at length about subjects he barely understood.",
  portentous: "The dark clouds were a portentous sign of the coming storm.",
  portmanteau: "The word brunch is a portmanteau of breakfast and lunch.",
  postulate: "The scientist had to postulate a new theory to explain the data.",
  potentate: "The potentate ruled the kingdom with absolute authority.",
  prandial: "The prandial conversation at dinner covered many topics.",
  preamble: "The preamble to the constitution sets out its guiding principles.",
  precept: "The moral precept guided her decisions throughout life.",
  precipitous: "The precipitous cliff dropped hundreds of feet to the ocean.",
  preponderate: "Evidence seemed to preponderate in favor of the defendant.",
  prescient: "Her prescient warning about the storm saved many lives.",
  prevaricate: "When asked directly, he tried to prevaricate rather than answer.",
  primogeniture: "Under primogeniture, the eldest son inherited the estate.",
  primordial: "Scientists study primordial conditions of the early universe.",
  probity: "Her probity as a judge was never questioned.",
  proclivity: "He has a proclivity for telling long, meandering stories.",
  procrustean: "The procrustean policy forced everyone into the same mold.",
  profligate: "The profligate spender quickly exhausted his inheritance.",
  prolegomenon: "The book opened with a scholarly prolegomenon.",
  promulgate: "The government plans to promulgate the new regulations next month.",
  propinquity: "The propinquity of the two houses meant the neighbors saw each other often.",
  propitiate: "Offerings were made to propitiate the angry deity.",
  propriety: "She always conducted herself with the utmost propriety.",
  proscribe: "The authorities moved to proscribe the dangerous substance.",
  proselytize: "He would proselytize about the benefits of a vegetarian diet.",
  prosody: "The professor taught a course on the prosody of English poetry.",
  protean: "The protean actor convincingly played many different roles.",
  provenance: "The museum verified the provenance of the ancient artifact.",
  psephology: "Psephology is the study of elections and voting patterns.",
  pulchritude: "The pulchritude of the landscape left visitors speechless.",
  purloin: "The cat managed to purloin a piece of fish from the counter.",
  pusillanimous: "The pusillanimous leader avoided every difficult decision.",
  putative: "The putative author of the anonymous letter was never confirmed.",
  pyrrhic: "The battle was won but at such cost it was a pyrrhic victory.",
  quaff: "He raised the goblet to quaff the celebratory drink.",
  quagmire: "The project became a quagmire of delays and budget overruns.",
  querulous: "The querulous patient complained about every aspect of the hospital.",
  quiddity: "The philosopher debated the quiddity of human consciousness.",
  quiescent: "The volcano had been quiescent for hundreds of years.",
  quixotic: "His quixotic quest to reform the entire system was admirable but unrealistic.",
  quotidian: "She found beauty in the quotidian routines of everyday life.",
  raconteur: "The raconteur captivated the dinner guests with his tales.",
  raffish: "The raffish adventurer lived by his own unconventional rules.",
  rapacious: "The rapacious corporation consumed every competitor in the market.",
  rarefied: "The rarefied air at high altitude made breathing difficult.",
  ratiocination: "Sherlock Holmes was famous for his powers of ratiocination.",
  recalcitrance: "The student's recalcitrance made the teacher's job more difficult.",
  recapitulate: "Let me recapitulate the main points of today's lesson.",
  recidivism: "The program aimed to reduce recidivism among released prisoners.",
  recondite: "The recondite subject matter required years of specialized study.",
  recrimination: "The meeting descended into mutual recrimination.",
  recrudescence: "There was a recrudescence of interest in classical music.",
  rectitude: "She was known for her moral rectitude and integrity.",
  redolent: "The kitchen was redolent with the aroma of baking bread.",
  redoubtable: "The redoubtable champion had never lost a single match.",
  refulgent: "The refulgent jewels sparkled under the bright lights.",
  regicide: "The act of regicide shocked the entire kingdom.",
  reification: "Reification treats abstract concepts as if they were physical things.",
  remonstrate: "She felt compelled to remonstrate against the unfair decision.",
  replete: "The library was replete with rare and valuable books.",
  reprobate: "The old reprobate was known for his mischievous pranks.",
  requiem: "The choir performed a beautiful requiem in the cathedral.",
  resplendent: "The queen looked resplendent in her ceremonial robes.",
  restive: "The restive horse stamped its hooves nervously.",
  reticent: "She was reticent about discussing her personal life.",
  retrograde: "The planet appeared to move in a retrograde direction.",
  revenant: "The ghost story featured a revenant returning from beyond.",
  ribald: "The ribald comedy had the audience roaring with laughter.",
  rodomontade: "His boastful rodomontade impressed no one.",
  rogue: "The rogue elephant was spotted far from the herd.",
  rubric: "Follow the rubric carefully when grading the assignments.",
  ruminate: "She liked to ruminate on life's big questions during long walks.",
  sacerdotal: "The sacerdotal vestments were worn during the ceremony.",
  sacrilege: "Vandalizing the ancient temple was considered sacrilege.",
  sagacity: "The elder was respected for her sagacity and wisdom.",
  salient: "The most salient feature of the proposal was its simplicity.",
  salutary: "The experience proved to be a salutary lesson in humility.",
  sanctimonious: "His sanctimonious lectures about morality rang hollow.",
  sanguine: "Despite the setbacks, she remained sanguine about the outcome.",
  sardonic: "His sardonic smile suggested he knew more than he was saying.",
  saturnine: "The saturnine expression on his face revealed his unhappiness.",
  scintillate: "The diamonds seemed to scintillate under the chandelier.",
  scion: "The scion of the wealthy family entered the family business.",
  scurrilous: "The scurrilous article made baseless accusations.",
  sedulous: "Her sedulous preparation for the exam paid off handsomely.",
  sententious: "The sententious speaker peppered his talk with proverbs.",
  sepulchral: "The sepulchral silence of the old church was eerie.",
  sesquipedalian: "The professor's sesquipedalian vocabulary baffled the freshmen.",
  sibylline: "The oracle delivered a sibylline prophecy open to interpretation.",
  simulacrum: "The wax figure was a perfect simulacrum of the celebrity.",
  sinecure: "The position was nothing more than a comfortable sinecure.",
  solecism: "Using whom incorrectly is a common grammatical solecism.",
  solipsism: "Solipsism holds that only one's own mind is sure to exist.",
  somnolent: "The warm afternoon made everyone feel somnolent.",
  sonorous: "The sonorous voice of the narrator filled the auditorium.",
  sophistry: "His clever sophistry almost disguised the weakness of his argument.",
  soporific: "The lecturer's monotone voice had a soporific effect.",
  sordid: "The investigation uncovered the sordid details of the fraud.",
  specious: "The argument seemed plausible but was actually specious.",
  splenetic: "His splenetic outburst surprised everyone at the meeting.",
  squalid: "The squalid living conditions were reported to the authorities.",
  staid: "The staid banker was known for his conservative style.",
  stochastic: "The model used stochastic processes to simulate random events.",
  strident: "Her strident voice could be heard above the crowd.",
  stridulate: "Crickets stridulate by rubbing their wings together.",
  sublimate: "She learned to sublimate her frustration into creative energy.",
  subterfuge: "The spy used subterfuge to gain access to the secret files.",
  supercilious: "The supercilious waiter looked down on the casually dressed diners.",
  supernumerary: "The theater hired several supernumerary actors for the crowd scene.",
  supplant: "New technology may supplant the old manufacturing methods.",
  supplicant: "The supplicant knelt before the altar and prayed.",
  surreptitious: "She cast a surreptitious glance at the answer sheet.",
  susurrus: "The gentle susurrus of the wind through the trees was calming.",
  sybarite: "The sybarite indulged in every luxury money could buy.",
  sycophantic: "His sycophantic behavior toward the boss was obvious to everyone.",
  syllogism: "A syllogism is a form of logical reasoning with two premises.",
  symbiosis: "The relationship between the two species is a perfect symbiosis.",
  synecdoche: "Using wheels to mean car is an example of synecdoche.",
  syzygy: "The alignment of the sun, earth, and moon is called syzygy.",
  taciturn: "The taciturn farmer rarely spoke more than a few words.",
  tautology: "Saying it is what it is is a simple tautology.",
  tempestuous: "The tempestuous seas tossed the ship violently.",
  tendentious: "The tendentious report clearly favored one side of the debate.",
  tergiversation: "His tergiversation on the issue frustrated both sides.",
  termagant: "The termagant berated everyone within earshot.",
  terpsichorean: "The terpsichorean display at the ballet was breathtaking.",
  tessellation: "The floor featured an intricate tessellation of geometric tiles.",
  thalassic: "The thalassic environment supported a rich variety of marine life.",
  thaumaturgy: "The audience marveled at the magician's apparent thaumaturgy.",
  theocracy: "The country was governed as a theocracy under religious law.",
  threnody: "The poet composed a threnody mourning the loss of her friend.",
  timorous: "The timorous kitten hid behind the sofa.",
  tmesis: "Inserting a word into another, as in abso-blooming-lutely, is tmesis.",
  tocsin: "The tocsin sounded from the bell tower to warn of danger.",
  torpid: "The torpid snake lay motionless in the cool shade.",
  torturous: "The long wait in the heat was absolutely torturous.",
  transmogrify: "The fairy tale witch could transmogrify people into animals.",
  treacle: "The dessert was drizzled with sweet golden treacle.",
  tremulous: "Her tremulous voice betrayed her nervousness.",
  trenchant: "The critic delivered a trenchant review of the performance.",
  trepidation: "She approached the exam with a sense of trepidation.",
  triskaidekaphobia: "His triskaidekaphobia made him avoid the thirteenth floor.",
  truculence: "The truculence of his tone put everyone on edge.",
  truculent: "The truculent customer demanded to speak with the manager.",
  tumescence: "The swelling and tumescence indicated an allergic reaction.",
  turgid: "The turgid prose of the novel made it difficult to read.",
  turpitude: "The act of moral turpitude resulted in his dismissal.",
  ubiquity: "The ubiquity of mobile phones has transformed daily life.",
  ululation: "The ululation of the mourners echoed through the valley.",
  umami: "The rich broth had a deep and satisfying umami flavor.",
  umbrage: "She took umbrage at the dismissive remark.",
  unctuous: "The unctuous salesman's flattery was transparent.",
  undulate: "The wheat fields seemed to undulate in the gentle breeze.",
  unguent: "She applied a soothing unguent to the rash on her arm.",
  untenable: "The position became untenable after the evidence was revealed.",
  urbane: "The urbane host conversed effortlessly with every guest.",
  usufruct: "The agreement granted usufruct of the land for twenty years.",
  usurious: "The loan had usurious interest rates that trapped borrowers.",
  vacillate: "She continued to vacillate between the two job offers.",
  vainglorious: "The vainglorious general boasted endlessly about his victories.",
  valediction: "The class president delivered a moving valediction at graduation.",
  vapid: "The vapid conversation failed to hold anyone's interest.",
  variegated: "The variegated leaves displayed shades of green and gold.",
  varlet: "In medieval tales, the varlet served the noble knight.",
  venal: "The venal official accepted bribes from anyone who offered.",
  veridical: "The witness gave a veridical account of the events.",
  verisimilitude: "The historical novel achieved remarkable verisimilitude.",
  vermicular: "The tunnels followed a vermicular path through the earth.",
  vexillology: "Vexillology is the scholarly study of flags.",
  vicarious: "She experienced vicarious joy watching her daughter graduate.",
  vicissitude: "The vicissitude of fortune turned his life upside down.",
  vilify: "It is wrong to vilify someone without knowing the facts.",
  vim: "She tackled every project with remarkable vim and vigor.",
  virago: "The fearless virago led the resistance movement.",
  virulent: "The virulent strain of the virus spread rapidly.",
  vitiate: "A single error could vitiate the entire experiment.",
  vitriolic: "The vitriolic editorial attacked the politician's record.",
  vituperate: "She refused to vituperate her opponents during the debate.",
  vivify: "The new mural was designed to vivify the dull concrete wall.",
  vociferous: "The vociferous crowd demanded an encore after the concert.",
  voluble: "The voluble tour guide never ran out of things to say.",
  vouchsafe: "The elder would vouchsafe wisdom only to those who asked.",
  wanton: "The wanton destruction of the forest was deeply troubling.",
  weltanschauung: "Her weltanschauung was shaped by years of travel and study.",
  winsome: "The child's winsome smile charmed everyone she met.",
  wunderkind: "The young wunderkind composed his first symphony at age twelve.",
  xenophobia: "Education and cultural exchange can help combat xenophobia.",
  xeric: "The xeric landscape was home to cacti and other desert plants.",
  zabaglione: "The chef prepared a creamy zabaglione for dessert.",
  zeitgeist: "The novel captured the zeitgeist of the turbulent decade.",
  zenith: "Her career reached its zenith when she won the Nobel Prize.",
  zephyr: "A gentle zephyr rustled the leaves on the summer afternoon.",
  zoetrope: "The spinning zoetrope created the illusion of a running horse.",
  zugzwang: "The chess player was caught in zugzwang, forced to make a losing move.",
};

export default RARE_SENTENCES;
