/**
 * Curated sentences for Level 3 (School) words not already covered.
 */
const SCHOOL_SENTENCES: Record<string, string> = {
  abacus: "She learned to count using an abacus in math class.",
  abandon: "They had to abandon the campsite due to the storm.",
  abbreviate: "Please abbreviate the state name on the form.",
  abdomen: "The doctor examined the patient's abdomen carefully.",
  aberrant: "The aberrant weather pattern surprised the forecasters.",
  abeyance: "The project was held in abeyance until funding arrived.",
  abject: "The refugees lived in abject poverty.",
  ablaze: "The forest was ablaze after the lightning strike.",
  ablution: "The morning ablution left him feeling refreshed.",
  abnormality: "The test revealed no abnormality in her blood work.",
  abode: "The cozy cabin served as their abode for the weekend.",
  abolition: "The abolition of slavery changed the nation forever.",
  aboriginal: "The aboriginal people have lived on this land for thousands of years.",
  abrasive: "The abrasive sandpaper smoothed the rough surface.",
  abridge: "The teacher asked students to abridge the long article.",
  abrogate: "The new law will abrogate the previous regulation.",
  abscission: "Abscission is the natural process by which leaves fall from trees.",
  absolution: "He sought absolution for his past mistakes.",
  absorptive: "The sponge has a highly absorptive surface.",
  abstain: "She chose to abstain from voting on the issue.",
  abstinent: "He remained abstinent from sugary drinks for a month.",
  abstraction: "The painting was an abstraction of a natural landscape.",
  abundant: "The valley has abundant wildlife and vegetation.",
  abysmal: "The team's performance this season was abysmal.",
  abyss: "The divers peered into the dark abyss below.",
  academy: "She was accepted into the prestigious science academy.",
  accede: "The king was expected to accede to the throne.",
  accelerate: "Press the pedal to accelerate the car.",
  acceleration: "The sports car's acceleration was impressive.",
  accessibility: "The new ramp improved accessibility to the building.",
  accessory: "She chose a matching accessory for her outfit.",
  acclaim: "The novel received great acclaim from critics.",
  acclimate: "It took time to acclimate to the high altitude.",
  acclimatize: "The hikers needed to acclimatize before climbing higher.",
  accommodate: "The hotel can accommodate up to two hundred guests.",
  accommodation: "They found comfortable accommodation near the beach.",
  accompaniment: "The piano provided a beautiful accompaniment to the singer.",
  accomplice: "The police arrested the accomplice in the robbery.",
  accomplishment: "Graduating from college was a major accomplishment.",
  accord: "The two nations signed a peace accord.",
  accordance: "All rules must be followed in accordance with the policy.",
  accordion: "He played a lively tune on the accordion.",
  accost: "A stranger tried to accost them on the street.",
  accountability: "Accountability is essential in any leadership role.",
  accountant: "The accountant prepared the tax returns.",
  accreditation: "The school earned its accreditation after a thorough review.",
  accretion: "The island grew over centuries through accretion of sand.",
  accrual: "The accrual of interest increased her savings balance.",
  accurate: "Her measurements were consistently accurate.",
  accuse: "Don't accuse someone without evidence.",
  ace: "She scored an ace on her first serve in tennis.",
  acerbity: "He spoke with an acerbity that stung his listeners.",
  acoustic: "The acoustic guitar sounded beautiful in the quiet room.",
  acquiesce: "She had to acquiesce to the committee's decision.",
  acquire: "She worked hard to acquire new language skills.",
  acquisition: "The museum celebrated its latest art acquisition.",
  acquittal: "The jury's verdict was an acquittal of all charges.",
  acreage: "The ranch covers a large acreage of open land.",
  acrobat: "The acrobat performed a daring flip on the high wire.",
  acronym: "NASA is an acronym for the space agency.",
  activate: "Press the button to activate the alarm system.",
  actuate: "A small motor can actuate the mechanical arm.",
  acuity: "Her visual acuity was excellent after the surgery.",
  adage: "There is an old adage that says haste makes waste.",
  adamantine: "Her adamantine resolve could not be shaken.",
  adapt: "Animals must adapt to survive in changing environments.",
  adaptation: "The movie was an adaptation of the famous novel.",
  addendum: "An addendum was attached to the original contract.",
  addictive: "Some video games can be quite addictive.",
  adhesive: "Use adhesive tape to seal the package.",
  adjective: "The word beautiful is an adjective that describes nouns.",
  adjoin: "The two rooms adjoin each other through a connecting door.",
  adjust: "She had to adjust the mirror before driving.",
  administer: "The nurse will administer the medication.",
  administration: "The school administration approved the new program.",
  administrative: "She handles all the administrative duties in the office.",
  admiration: "She looked at the painting with great admiration.",
  admissible: "The judge ruled the evidence admissible in court.",
  admonition: "His teacher's admonition was a gentle warning to study harder.",
  adobe: "The house was built from traditional adobe bricks.",
  adolescent: "The adolescent years are a time of great change.",
  advantageous: "A strong education is advantageous in any career.",
  advent: "The advent of the internet changed communication forever.",
  adversarial: "The debate took an adversarial tone.",
  advertisement: "She saw an advertisement for the sale in the newspaper.",
  aegis: "The project was completed under the aegis of the university.",
  aerate: "You should aerate the lawn to help the grass grow.",
  aerobics: "She attends an aerobics class three times a week.",
  aerodynamic: "The car's aerodynamic design improved fuel efficiency.",
  aerospace: "She works in the aerospace industry designing rockets.",
  affable: "The affable host made every guest feel welcome.",
  affection: "The mother showed great affection toward her children.",
  affiliate: "The local station is an affiliate of the national network.",
  affiliation: "Her affiliation with the organization lasted many years.",
  affinity: "She has a natural affinity for learning languages.",
  affirm: "The court voted to affirm the lower court's decision.",
  affirmative: "She gave an affirmative nod when asked if she agreed.",
  affix: "Please affix a stamp to the top corner of the envelope.",
  afflict: "The disease can afflict people of all ages.",
  affluence: "The town grew in affluence over the past decade.",
  affront: "The rude comment was an affront to her dignity.",
  aftermath: "The aftermath of the hurricane left many homes damaged.",
  agape: "She stood with her mouth agape at the surprise.",
  agate: "The child found a smooth agate stone by the river.",
  agenda: "The first item on the agenda is the budget review.",
  aggravation: "The constant noise was a source of great aggravation.",
  aggression: "The dog showed no signs of aggression toward visitors.",
  aghast: "She was aghast when she heard the shocking news.",
  agility: "The gymnast demonstrated incredible agility on the beam.",
  agitation: "The crowd's agitation grew as the delay continued.",
  agnostic: "He described himself as agnostic on the matter.",
  agonize: "Don't agonize over small decisions.",
  agrarian: "The agrarian community relied on farming for its livelihood.",
  agriculture: "Agriculture is the backbone of many rural economies.",
  ailment: "The doctor treated the patient's common ailment.",
  aimless: "She wandered in an aimless direction through the park.",
  airborne: "The paratroopers became airborne at dawn.",
  airtight: "The airtight container kept the cookies fresh.",
  alcove: "She set up a reading nook in the small alcove.",
  alderman: "The alderman represented his district at the city council.",
  alfalfa: "The farmer planted alfalfa to feed the livestock.",
  algorithmic: "The algorithmic approach solved the problem efficiently.",
  allegiance: "Citizens pledged their allegiance to the flag.",
  allocate: "The school will allocate funds for new computers.",
  alternate: "They decided to alternate between the two routes.",
  altitude: "The airplane reached an altitude of thirty thousand feet.",
  amateur: "The amateur photographer took a stunning picture.",
  ambiguity: "The ambiguity of the instructions caused confusion.",
  ambitious: "The ambitious student aimed for the highest grades.",
  amphibian: "A frog is a common amphibian found near ponds.",
  analysis: "The scientist completed a detailed analysis of the data.",
  analyze: "The lab will analyze the water sample for purity.",
  anatomy: "She studied human anatomy in her biology class.",
  anthropology: "Anthropology explores human cultures and societies.",
  appendix: "The appendix at the back of the book listed additional sources.",
  appreciation: "She expressed her appreciation with a heartfelt letter.",
  appropriation: "The appropriation of funds was approved by the board.",
  archaeological: "The archaeological dig uncovered ancient pottery.",
  architecture: "The city is famous for its beautiful architecture.",
  argumentative: "The argumentative essay required strong evidence.",
  arithmetic: "Basic arithmetic includes addition and subtraction.",
  articulation: "Her articulation of the complex idea was remarkably clear.",
  aspiration: "Her aspiration is to become a professional musician.",
  assert: "She did not hesitate to assert her opinion.",
  assess: "The teacher will assess the students' progress.",
  assign: "The teacher will assign homework every Monday.",
  assist: "The teaching assistant helped the students with the activity.",
  astronaut: "The astronaut traveled to the International Space Station.",
  athlete: "The young athlete trained every day for the competition.",
  authentication: "Two-factor authentication improves account security.",
  authority: "The police officer had the authority to close the road.",
  authorization: "You need authorization to access the secure area.",
  autobiography: "She wrote an autobiography about her life story.",
  available: "The tickets are available at the front desk.",
  aviation: "She pursued a career in aviation and became a pilot.",
  bacteria: "Washing hands helps remove harmful bacteria.",
  ballot: "Each citizen cast a ballot in the election.",
  bankrupt: "The company went bankrupt after years of losses.",
  bankruptcy: "Filing for bankruptcy was a last resort.",
  barricade: "The police set up a barricade to block the road.",
  battery: "Replace the battery when the flashlight gets dim.",
  behavior: "Good behavior is expected in the classroom.",
  betray: "A true friend would never betray your trust.",
  bibliography: "Include a bibliography at the end of your research paper.",
  biennial: "The biennial festival takes place every two years.",
  bilateral: "The two countries signed a bilateral trade agreement.",
  biodegradable: "Use biodegradable bags to help protect the environment.",
  biodiversity: "The rainforest is known for its incredible biodiversity.",
  biology: "She dissected a frog in biology class.",
  biotechnology: "Biotechnology has led to breakthroughs in medicine.",
  bizarre: "The magician's trick was truly bizarre and unexpected.",
  blizzard: "The blizzard dumped three feet of snow overnight.",
  boundary: "The fence marks the boundary of the property.",
  brigadier: "The brigadier commanded the troops with confidence.",
  brilliant: "The student's essay was absolutely brilliant.",
  brittle: "The old paper was dry and brittle.",
  broadband: "Broadband internet is available throughout the building.",
  bronze: "She won a bronze medal at the swimming competition.",
  bureaucracy: "The lengthy bureaucracy slowed down the approval process.",
  bureaucrat: "The bureaucrat processed the application forms.",
  cabinet: "The medicine cabinet is in the bathroom.",
  cafeteria: "The students eat lunch in the school cafeteria.",
  campaign: "She ran a successful campaign for class president.",
  candidate: "The candidate gave a compelling speech.",
  capitalism: "Capitalism is an economic system based on free markets.",
  cardiovascular: "Running is excellent cardiovascular exercise.",
  catastrophic: "The catastrophic earthquake destroyed many buildings.",
  cemetery: "Flowers were placed on the graves in the cemetery.",
  choreography: "The dance performance featured stunning choreography.",
  chronological: "Please list the events in chronological order.",
  circumference: "The circumference of the circle was measured carefully.",
  citizenship: "She earned her citizenship after living here for five years.",
  clarification: "The student asked for clarification on the assignment.",
  classification: "Scientists use classification to organize living things.",
  coefficient: "The coefficient in the equation was equal to three.",
  collaboration: "The project was a collaboration between two schools.",
  combination: "The combination of flavors created a delicious dish.",
  commemorative: "The commemorative stamp honored a famous scientist.",
  commence: "The ceremony will commence at ten o'clock.",
  commercial: "The funny commercial made everyone laugh.",
  commission: "She earned a commission on every sale she made.",
  committee: "The committee met to discuss the upcoming event.",
  communism: "They studied communism as a political ideology in class.",
  competition: "The spelling competition attracted students from every school.",
  complementary: "The two colors are complementary and look great together.",
  comprehension: "Reading comprehension is an essential skill.",
  computation: "The computation required a powerful computer.",
  conclusion: "The essay ended with a strong conclusion.",
  confederation: "The confederation of states worked together on trade.",
  confidentiality: "Patient confidentiality is a core medical principle.",
  configuration: "The software configuration was set up correctly.",
  confrontation: "They resolved the confrontation peacefully.",
  congregation: "The congregation sang together during the service.",
  congressional: "The congressional hearing was broadcast on television.",
  conscientious: "She is a conscientious worker who never cuts corners.",
  corporation: "The corporation announced record profits this quarter.",
  correspondence: "She maintained a long correspondence with her pen pal.",
  creative: "The creative student designed an original poster.",
  criteria: "The criteria for the award include academic excellence.",
  crucial: "It is crucial to study before the final exam.",
  customization: "The app offers extensive customization options.",
  demonstrate: "The teacher will demonstrate the experiment in class.",
  denomination: "The coins were sorted by denomination.",
  deteriorate: "The old building began to deteriorate over time.",
  determine: "Scientists will determine the cause of the problem.",
  devote: "She decided to devote her summer to volunteering.",
  diagram: "The diagram showed how the machine works.",
  dialogue: "The characters had an interesting dialogue in the play.",
  dictate: "The boss will dictate a memo to his assistant.",
  dilemma: "She faced a dilemma between two great options.",
  dimension: "The room's dimensions were measured for new furniture.",
  diplomat: "The diplomat negotiated a trade agreement.",
  disability: "The school provides support for every student with a disability.",
  disappoint: "She didn't want to disappoint her parents.",
  discipline: "Good discipline helps students succeed in school.",
  discourse: "The professor encouraged thoughtful discourse in class.",
  discrimination: "Discrimination based on race is against the law.",
  disguise: "The spy wore a clever disguise to avoid detection.",
  displacement: "The flood caused the displacement of many families.",
  dispute: "The neighbors resolved their property dispute amicably.",
  dissolve: "Stir the powder until it dissolves in the water.",
  distinction: "She graduated with distinction from the university.",
  distinguish: "It is hard to distinguish the twins from each other.",
  distribute: "Volunteers helped distribute food to the community.",
  diverse: "The school celebrates its diverse student body.",
  division: "She learned long division in math class.",
  document: "Please sign the document at the bottom of the page.",
  documentation: "Proper documentation is required for the project.",
  domestic: "Domestic flights are usually shorter than international ones.",
  dominant: "The dominant color in the painting was blue.",
  dominate: "The tall player dominated the basketball game.",
  dormitory: "The college dormitory housed over two hundred students.",
  drought: "The severe drought dried up the river completely.",
  duplicate: "Please make a duplicate copy of the report.",
  duration: "The movie has a duration of two hours.",
  dynamic: "The dynamic speaker kept the audience engaged.",
  ecology: "She studied ecology to learn about ecosystems.",
  economy: "A strong economy creates more job opportunities.",
  elaborate: "She gave an elaborate description of her vacation.",
  election: "Citizens vote in the election every four years.",
  electromagnetic: "Electromagnetic waves carry energy through space.",
  elegant: "The bride wore an elegant white gown.",
  element: "Oxygen is a chemical element essential for life.",
  elevate: "The crane was used to elevate the heavy steel beam.",
  eliminate: "We need to eliminate errors in the final report.",
  eloquent: "Her eloquent speech moved the entire audience.",
  emancipation: "The emancipation of enslaved people was a turning point in history.",
  embrace: "She gave her grandmother a warm embrace.",
  emergency: "Call the emergency number if you need help right away.",
  emission: "The factory reduced its carbon emission by half.",
  emotion: "She could not hide the emotion in her voice.",
  emphasize: "The teacher wanted to emphasize the importance of reading.",
  empire: "The Roman Empire lasted for centuries.",
  encounter: "We had an unexpected encounter with a deer on the trail.",
  encourage: "Parents should encourage their children to read.",
  encouragement: "Her words of encouragement helped him keep going.",
  endure: "The marathon runner had to endure extreme heat.",
  enforce: "The school will enforce the dress code strictly.",
  enhance: "New lighting will enhance the appearance of the room.",
  enormous: "The enormous whale surfaced beside the small boat.",
  enterprise: "Starting a small enterprise requires determination.",
  enthusiasm: "She approached every project with great enthusiasm.",
  environment: "Protecting the environment is everyone's responsibility.",
  epidemic: "The health department worked to contain the epidemic.",
  equation: "She solved the algebra equation correctly.",
  equipment: "The gym was filled with modern exercise equipment.",
  equivalent: "One kilometer is approximately equivalent to half a mile.",
  erosion: "Wind and water cause erosion of the rocky coastline.",
  essential: "Water is essential for all living things.",
  establish: "They plan to establish a new library in town.",
  establishment: "The restaurant is a popular local establishment.",
  estimate: "Can you estimate how long the trip will take?",
  evaluate: "The teacher will evaluate each student's progress.",
  eventually: "If you keep practicing, you will eventually master it.",
  evidence: "The detective gathered evidence at the crime scene.",
  evolution: "The theory of evolution explains how species change.",
  exaggerate: "Don't exaggerate the size of the fish you caught.",
  excel: "She continued to excel in all her subjects.",
  exception: "Every student passed the test without exception.",
  exchange: "They agreed to exchange phone numbers.",
  exclusive: "The club has exclusive membership requirements.",
  executive: "The executive made decisions for the whole company.",
  exempt: "Students under five are exempt from the fee.",
  exhibit: "The museum opened a new dinosaur exhibit.",
  existence: "The existence of life on other planets is still debated.",
  expand: "The company plans to expand into new markets.",
  expedition: "The expedition to the Arctic lasted three months.",
  experiment: "The science experiment produced surprising results.",
  expertise: "Her expertise in mathematics was widely recognized.",
  exploit: "The inventor found a way to exploit solar energy.",
  exploration: "Space exploration continues to make new discoveries.",
  explosion: "The loud explosion shook the entire neighborhood.",
  export: "The country's main export is coffee beans.",
  exposure: "Prolonged exposure to the sun can harm your skin.",
  extension: "She requested a one-week extension on her paper.",
  extensive: "The library has an extensive collection of rare books.",
  external: "The external walls of the building were brick.",
  extinct: "Dinosaurs became extinct millions of years ago.",
  extraordinary: "She has an extraordinary talent for painting.",
  extreme: "The extreme cold made it dangerous to go outside.",
  facilitate: "The new software will facilitate communication.",
  faculty: "The university faculty includes world-renowned professors.",
  familiar: "The song sounded very familiar to her.",
  fascinate: "Outer space continues to fascinate scientists.",
  federal: "The federal government passed a new education law.",
  fiction: "She enjoys reading science fiction novels.",
  flexible: "Yoga helps make your body more flexible.",
  fluctuate: "Gas prices tend to fluctuate throughout the year.",
  fluent: "She is fluent in both Spanish and English.",
  forecast: "The weather forecast predicted rain for the weekend.",
  formula: "The scientist tested the new chemical formula.",
  fossil: "They found a dinosaur fossil buried in the rock.",
  foundation: "A strong foundation is essential for any building.",
  fraction: "She divided the pie into an equal fraction for each person.",
  fragment: "A small fragment of the ancient pot was found.",
  framework: "The teacher provided a framework for the essay.",
  frequency: "The frequency of the bus service is every fifteen minutes.",
  frontier: "The pioneers pushed westward across the frontier.",
  frustrate: "Difficult puzzles can sometimes frustrate young learners.",
  fulfill: "She worked hard to fulfill her dream of becoming a doctor.",
  function: "The function of the heart is to pump blood.",
  fundamental: "Reading is a fundamental skill for all students.",
  gallery: "The art gallery displayed paintings by local artists.",
  generate: "Solar panels generate electricity from sunlight.",
  generous: "The generous donor funded the new playground.",
  genuine: "Her apology seemed completely genuine.",
  geography: "In geography class, they learned about world rivers.",
  geometry: "She used geometry to calculate the area of the triangle.",
  gesture: "A simple gesture of kindness can brighten someone's day.",
  glacier: "The massive glacier slowly moved down the mountain.",
  glimpse: "She caught a glimpse of the deer before it disappeared.",
  globalization: "Globalization has connected economies around the world.",
  graduate: "She was the first in her family to graduate from college.",
  grammar: "Good grammar is important for clear writing.",
  guarantee: "The appliance comes with a five-year guarantee.",
  guidance: "The school counselor provided guidance on college choices.",
  gymnasium: "The basketball game was held in the school gymnasium.",
  habitat: "The wetland is a natural habitat for many bird species.",
  handicap: "The golfer played with a low handicap.",
  hazard: "Icy roads are a serious hazard for drivers.",
  hemisphere: "The Northern Hemisphere experiences summer in July.",
  heritage: "The festival celebrates the cultural heritage of the region.",
  hesitate: "Don't hesitate to ask for help when you need it.",
  hierarchy: "The company has a clear hierarchy of management.",
  horizon: "The sun dipped below the horizon at dusk.",
  hostile: "The hostile weather conditions forced them to turn back.",
  household: "Every household received a notice about the meeting.",
  humidity: "The high humidity made the summer day feel even hotter.",
  hurricane: "The hurricane brought powerful winds and heavy rain.",
  hygiene: "Good hygiene habits help prevent the spread of illness.",
  hypothesis: "The scientist formed a hypothesis before the experiment.",
  hypothesize: "Students were asked to hypothesize about the outcome.",
  identical: "The identical twins looked exactly alike.",
  identify: "Can you identify the different types of clouds?",
  ignorant: "Being ignorant of the rules is not an excuse.",
  illustrate: "She used drawings to illustrate her point.",
  immediate: "The fire required an immediate response from the crew.",
  immigrant: "The immigrant family built a new life in the country.",
  impact: "The new law had a positive impact on the community.",
  implement: "The school plans to implement a new reading program.",
  implication: "The study's findings have a significant implication for health.",
  import: "The country decided to import more grain this year.",
  impose: "The city will impose a fine for littering.",
  impression: "Her first impression of the school was very positive.",
  impulse: "She bought the necklace on impulse.",
  incident: "The incident was reported to the school principal.",
  incorporate: "The chef will incorporate fresh herbs into the dish.",
  independent: "She is a very independent and self-reliant person.",
  indicate: "The test results indicate improvement in all areas.",
  individual: "Every individual has unique strengths and talents.",
  inevitable: "Mistakes are an inevitable part of learning.",
  inferior: "The cheap paint proved to be inferior in quality.",
  infinite: "The universe appears to be infinite in size.",
  inflation: "Inflation caused the price of groceries to rise.",
  influence: "A good teacher can have a lasting influence on students.",
  infrastructure: "The city invested in improving its infrastructure.",
  inhabit: "Many species of birds inhabit the tropical forest.",
  initial: "Her initial reaction was one of surprise.",
  initiative: "She took the initiative to organize the cleanup event.",
  innocent: "The jury found the defendant innocent of all charges.",
  innovation: "Innovation drives progress in technology.",
  inspect: "The mechanic will inspect the car before the road trip.",
  inspiration: "Her grandmother was her greatest source of inspiration.",
  install: "The technician will install the new software today.",
  instance: "This is one instance where patience is truly important.",
  institution: "The university is a respected educational institution.",
  instruct: "The coach will instruct the team on the new play.",
  instrument: "She plays the violin, her favorite musical instrument.",
  insurance: "Health insurance helps cover medical expenses.",
  integrate: "The school worked to integrate technology into every class.",
  intellectual: "The intellectual discussion covered many fascinating topics.",
  intense: "The intense heat wave lasted for over a week.",
  intention: "Her intention was to help as many people as possible.",
  interact: "Children learn social skills when they interact with peers.",
  interior: "The interior of the house was warm and inviting.",
  interpret: "The guide helped interpret the ancient symbols.",
  interpretation: "Her interpretation of the poem was insightful.",
  interval: "There was a ten-minute interval between the two acts.",
  intervene: "The teacher had to intervene to stop the argument.",
  intimate: "They shared an intimate conversation over dinner.",
  investigate: "The police will investigate the cause of the accident.",
  investigation: "The investigation revealed important new facts.",
  investment: "Education is the best investment you can make.",
  invisible: "The tiny insects were almost invisible to the naked eye.",
  involve: "The project will involve students from every grade.",
  isolate: "Scientists had to isolate the virus in the laboratory.",
  journal: "She wrote her thoughts in a daily journal.",
  judgment: "The judge delivered a fair and thoughtful judgment.",
  junction: "Turn left at the junction to reach the highway.",
  junior: "The junior class organized the school dance.",
  jurisdiction: "The case fell under the jurisdiction of the local court.",
  justify: "She was asked to justify her answer with evidence.",
  kindergarten: "Her daughter just started kindergarten this fall.",
  label: "Read the label on the bottle before taking the medicine.",
  laboratory: "The students conducted experiments in the laboratory.",
  landscape: "The landscape was covered in wildflowers every spring.",
  latitude: "The city is located at a latitude of forty degrees north.",
  launch: "The rocket will launch into orbit tomorrow morning.",
  lecture: "The professor gave an engaging lecture on history.",
  legacy: "The scientist left behind a remarkable legacy.",
  legend: "According to legend, a dragon once lived in that cave.",
  legislation: "New legislation was passed to protect the environment.",
  legitimate: "She had a legitimate reason for missing class.",
  leisure: "She spends her leisure time reading and gardening.",
  liberal: "The college offers a liberal arts education.",
  liberty: "The statue represents liberty and freedom for all.",
  lieutenant: "The lieutenant led the patrol through the forest.",
  likewise: "She greeted everyone warmly, and they responded likewise.",
  limousine: "A long black limousine arrived at the hotel entrance.",
  literature: "She studied American literature in her English class.",
  longitude: "The ship's position was marked by its longitude and latitude.",
  luxury: "A vacation on a tropical island is a true luxury.",
  magnificent: "The view from the mountaintop was absolutely magnificent.",
  magnitude: "The earthquake measured seven on the magnitude scale.",
  maintain: "It is important to maintain a balanced diet.",
  majority: "The majority of students passed the final exam.",
  manufacture: "The factory will manufacture five hundred cars this month.",
  manuscript: "The author submitted her manuscript to the publisher.",
  margin: "She wrote notes in the margin of her textbook.",
  marine: "The marine biologist studied coral reefs underwater.",
  massive: "A massive boulder blocked the mountain road.",
  mathematics: "She earned top marks in mathematics every semester.",
  mature: "The grapes need more time to mature on the vine.",
  maximum: "The maximum speed limit on this highway is sixty-five.",
  mechanic: "The mechanic fixed the engine in under an hour.",
  mechanism: "The clock's mechanism was intricate and precise.",
  medieval: "The medieval castle had thick stone walls.",
  medium: "She ordered a medium coffee with cream.",
  membrane: "The thin membrane protected the delicate tissue.",
  memorial: "They visited the war memorial to honor the veterans.",
  mental: "Regular exercise benefits both physical and mental health.",
  merchant: "The merchant sold spices from distant lands.",
  mercy: "The judge showed mercy in the sentencing.",
  metropolitan: "The metropolitan area has a population of two million.",
  microscope: "She examined the cell under a powerful microscope.",
  migrate: "Many birds migrate south during the winter months.",
  military: "He served in the military for twenty years.",
  mineral: "Iron is an important mineral found in many foods.",
  minimum: "The minimum age to drive is sixteen in most states.",
  ministry: "The ministry of education oversees all public schools.",
  minority: "The proposal was supported by only a minority of voters.",
  miracle: "It was considered a miracle that everyone survived.",
  moderate: "The moderate climate made it a pleasant place to live.",
  modify: "She decided to modify the recipe by adding more spice.",
  moisture: "The plants need moisture to grow properly.",
  molecule: "A water molecule consists of two hydrogen and one oxygen atom.",
  momentum: "The team gained momentum after scoring the first goal.",
  monarch: "The monarch ruled the kingdom for fifty years.",
  monitor: "The nurse will monitor the patient's heart rate.",
  monopoly: "The company had a monopoly on the local market.",
  moral: "The story has an important moral about honesty.",
  mortgage: "They took out a mortgage to buy their first house.",
  motivate: "A good coach knows how to motivate the team.",
  municipal: "The municipal park is open to all residents.",
  mutual: "They shared a mutual interest in photography.",
  narrative: "The narrative in the novel was captivating from start to finish.",
  negotiate: "The two sides agreed to negotiate a fair deal.",
  neutral: "Switzerland remained neutral during the conflict.",
  nitrogen: "Nitrogen makes up most of the earth's atmosphere.",
  nominate: "The students decided to nominate her for class president.",
  notorious: "The highway was notorious for heavy traffic.",
  nuclear: "Nuclear energy can generate large amounts of electricity.",
  nutrition: "Good nutrition is essential for growing children.",
  objective: "The main objective of the lesson is to learn fractions.",
  obligation: "Paying taxes is an obligation for all citizens.",
  obscure: "The meaning of the ancient text remained obscure.",
  obstacle: "The fallen tree was an obstacle on the hiking trail.",
  obtain: "She was able to obtain a scholarship for college.",
  occasion: "Graduation day was a joyful occasion for the whole family.",
  occupation: "Teaching is a rewarding occupation.",
  occupy: "The new family will occupy the house next month.",
  occur: "Earthquakes can occur without any warning.",
  offend: "She didn't mean to offend anyone with her comment.",
  offense: "No offense was intended by the remark.",
  official: "The official announcement was made at noon.",
  omit: "Please don't omit any details from your report.",
  opponent: "She shook hands with her opponent after the match.",
  opportunity: "This internship is a wonderful opportunity to learn.",
  oppose: "Several members voted to oppose the new rule.",
  orchestra: "The school orchestra performed a beautiful symphony.",
  ordinary: "It started as an ordinary day but turned extraordinary.",
  organism: "Every living organism needs water to survive.",
  organize: "She helped organize the books on the library shelf.",
  orientation: "New students attended an orientation session.",
  origin: "The origin of the word comes from ancient Greek.",
  outline: "She wrote an outline before starting the essay.",
  overcome: "She worked hard to overcome her fear of speaking.",
  overlook: "Don't overlook the small details in your work.",
  oxygen: "Humans need oxygen to breathe and survive.",
  parallel: "The two roads run parallel to each other.",
  parliament: "The parliament debated the new trade law.",
  participate: "All students are encouraged to participate in the event.",
  passion: "She has a deep passion for marine biology.",
  passive: "The passive voice should be avoided in strong writing.",
  patrol: "The security guard made a patrol of the grounds.",
  patron: "The patron donated generously to the arts center.",
  peculiar: "The animal had a peculiar marking on its back.",
  penalty: "The penalty for speeding is a fifty dollar fine.",
  perceive: "People sometimes perceive things differently.",
  percentage: "A large percentage of students scored above average.",
  permanent: "The tattoo is a permanent mark on the skin.",
  permission: "You need permission from your parents to go.",
  persist: "She continued to persist despite the challenges.",
  personnel: "All personnel must attend the safety training session.",
  perspective: "Traveling gave her a new perspective on life.",
  persuade: "She tried to persuade her friend to join the team.",
  petition: "The students signed a petition for a longer lunch break.",
  pharmaceutical: "The pharmaceutical company developed a new vaccine.",
  phenomenon: "The northern lights are a natural phenomenon.",
  philosophy: "She studied philosophy at the university.",
  physical: "Physical exercise is important for a healthy lifestyle.",
  pioneer: "She was a pioneer in the field of computer science.",
  plaintiff: "The plaintiff presented evidence to the jury.",
  plateau: "The hikers rested on the flat mountain plateau.",
  plausible: "The explanation sounded plausible to the investigators.",
  pledge: "The students recited the pledge of allegiance.",
  plunge: "She took a plunge into the cold mountain lake.",
  policy: "The new school policy requires uniforms.",
  pollution: "Air pollution is a major environmental concern.",
  portion: "She served a generous portion of pasta to each guest.",
  possess: "She seemed to possess an endless supply of energy.",
  postpone: "They had to postpone the game due to rain.",
  potential: "Every student has the potential to succeed.",
  poverty: "The organization works to fight poverty worldwide.",
  precede: "Thunder often seems to precede lightning.",
  precise: "Her measurements were always precise and accurate.",
  predict: "Scientists try to predict the path of hurricanes.",
  prejudice: "Prejudice against others should never be tolerated.",
  preliminary: "The preliminary results looked very promising.",
  premature: "It would be premature to announce the results now.",
  premier: "The premier gave a speech at the conference.",
  premise: "The argument was built on a solid premise.",
  premium: "The premium quality fabric was soft and durable.",
  prescription: "The doctor wrote a prescription for the medication.",
  preserve: "The park was created to preserve the natural habitat.",
  prestige: "The award carries great prestige in the scientific community.",
  prevail: "Justice will prevail in the end.",
  previous: "The previous owner had maintained the house beautifully.",
  primary: "Her primary goal was to finish the marathon.",
  primitive: "The primitive tools were made from stone and bone.",
  priority: "Safety should always be the top priority.",
  privilege: "It is a privilege to attend this fine school.",
  procedure: "Follow the correct procedure when using the equipment.",
  proceed: "After the break, we will proceed with the lesson.",
  process: "The manufacturing process takes about three days.",
  profession: "Medicine is a highly respected profession.",
  profile: "She updated her profile with a new photo.",
  profound: "The book had a profound impact on her thinking.",
  progress: "She made steady progress in learning the piano.",
  prohibit: "The rules prohibit running in the hallways.",
  project: "The science project won first place at the fair.",
  prominent: "The prominent scientist gave a keynote speech.",
  promote: "The campaign aims to promote healthy eating habits.",
  proportion: "Mix the ingredients in the correct proportion.",
  proposal: "She submitted a proposal for the new community garden.",
  prosecute: "The state decided to prosecute the case.",
  prospect: "The prospect of a snow day excited the students.",
  protein: "Eggs are a good source of protein.",
  protest: "The citizens gathered to protest the new law peacefully.",
  province: "She grew up in a rural province in the south.",
  provoke: "Please don't provoke the dog; it might bite.",
  psychology: "She studied psychology to understand human behavior.",
  publication: "The publication of her first novel was a milestone.",
  pursue: "She decided to pursue a degree in engineering.",
  qualification: "A teaching degree is the basic qualification for the job.",
  qualify: "She trained hard to qualify for the national team.",
  quantity: "Order a large quantity of paper for the printer.",
  quarantine: "The sick patients were placed in quarantine.",
  quota: "The factory met its production quota for the month.",
  radical: "The scientist proposed a radical new theory.",
  random: "The teacher selected a random student to answer.",
  ratio: "The ratio of boys to girls in the class is equal.",
  reaction: "Her reaction to the surprise was pure joy.",
  realistic: "The painting looked so realistic it seemed like a photo.",
  rebellion: "The rebellion against the tyrant was led by the farmers.",
  recession: "The economic recession affected businesses worldwide.",
  recognize: "She was the first to recognize the problem.",
  recommend: "I would highly recommend that book to anyone.",
  recommendation: "The teacher wrote a strong recommendation letter.",
  reconcile: "The siblings were able to reconcile their differences.",
  recover: "She took time to recover from the flu.",
  recruit: "The coach went to recruit talented young athletes.",
  reference: "She used the encyclopedia as a reference for her report.",
  reform: "The reform of the education system improved schools.",
  refuge: "The animals found refuge from the storm in a cave.",
  regime: "The new regime promised democratic elections.",
  register: "Please register for the class before Friday.",
  regulate: "Laws help regulate the safety of food products.",
  reinforce: "The teacher used examples to reinforce the lesson.",
  relevant: "Please include only relevant information in the report.",
  reluctant: "She was reluctant to speak in front of the large crowd.",
  remedy: "The doctor suggested a natural remedy for the cold.",
  render: "The new software can render images in three dimensions.",
  renew: "She went to the library to renew her borrowed books.",
  represent: "The flag represents the unity of the nation.",
  representation: "The mural is a beautiful representation of local history.",
  reproduce: "The printer can reproduce the image in full color.",
  republic: "The country is governed as a democratic republic.",
  reputation: "She earned a reputation for being extremely reliable.",
  resemble: "The child began to resemble her mother as she grew.",
  reside: "Many birds reside in the wetlands during winter.",
  resign: "The coach decided to resign at the end of the season.",
  resolution: "She made a resolution to exercise more this year.",
  resolve: "They worked together to resolve the disagreement.",
  resource: "Water is a precious natural resource.",
  respond: "She was quick to respond to the email.",
  restore: "Volunteers helped restore the old historic building.",
  restrict: "The diet plan will restrict sugar intake.",
  retain: "She managed to retain most of what she studied.",
  retire: "He plans to retire after thirty years of teaching.",
  retrieve: "The dog was trained to retrieve the ball.",
  revenue: "The company's revenue increased by ten percent.",
  reverse: "She put the car in reverse to back out of the driveway.",
  revise: "Please revise your essay before submitting it.",
  revolution: "The industrial revolution transformed manufacturing.",
  rhetoric: "Her powerful rhetoric inspired the audience.",
  rhythm: "The drummer kept a steady rhythm throughout the song.",
  ritual: "Lighting candles is a traditional holiday ritual.",
  rival: "The two teams have been fierce rivals for years.",
  routine: "Her morning routine includes a jog in the park.",
  rural: "The rural countryside is peaceful and quiet.",
  sacrifice: "The team made a sacrifice to help the community.",
  satellite: "The satellite orbits the earth once every ninety minutes.",
  schedule: "Please check the schedule for your next class.",
  scholar: "The scholar spent years researching ancient civilizations.",
  scripture: "The passage from scripture was read during the ceremony.",
  sculpture: "The marble sculpture was displayed in the museum.",
  secure: "Make sure to secure all doors before leaving.",
  segment: "The orange was divided into ten segments.",
  seminar: "She attended a seminar on climate change.",
  senator: "The senator voted in favor of the new bill.",
  sensation: "The cold water caused a tingling sensation on her skin.",
  sequence: "Arrange the numbers in the correct sequence.",
  session: "The tutoring session lasted for one hour.",
  significance: "The discovery has great significance for medical research.",
  simulate: "The software can simulate real-world weather conditions.",
  simultaneous: "The two events occurred at a simultaneous moment.",
  skeleton: "The museum displayed a complete dinosaur skeleton.",
  solar: "Solar energy is a clean and renewable resource.",
  solemn: "The ceremony was a solemn and respectful event.",
  solution: "She found a creative solution to the difficult problem.",
  sophisticated: "The sophisticated technology impressed the engineers.",
  sovereign: "The sovereign nation declared its independence.",
  specialist: "She consulted a specialist about her knee injury.",
  species: "The biologist discovered a new species of butterfly.",
  specimen: "The lab collected a specimen for further testing.",
  spectrum: "The rainbow displays the full spectrum of visible light.",
  spiritual: "The retreat offered a time for spiritual reflection.",
  sponsor: "A local business agreed to sponsor the school team.",
  spontaneous: "The crowd broke into a spontaneous round of applause.",
  stability: "The bridge was tested for structural stability.",
  statistic: "The statistic showed a ten percent improvement.",
  status: "The status of the project was reported at the meeting.",
  stereotype: "It is wrong to judge people based on a stereotype.",
  stimulate: "The teacher used games to stimulate learning.",
  strategy: "The coach outlined a new strategy for the game.",
  structure: "The structure of the building is made of steel.",
  subordinate: "The manager met with her subordinate to review progress.",
  subsequent: "The subsequent chapters explained the theory in detail.",
  substance: "The unknown substance was analyzed in the laboratory.",
  substitute: "The substitute teacher led the class for the day.",
  subtle: "There was a subtle change in the color of the sky.",
  sufficient: "Make sure you have sufficient time to finish the test.",
  supplement: "She takes a vitamin supplement every morning.",
  supreme: "The supreme court issued its ruling today.",
  surplus: "The farm had a surplus of apples this fall.",
  survey: "The students conducted a survey about school lunches.",
  survival: "Clean water is essential for survival.",
  suspend: "The school may suspend students who break the rules.",
  sustain: "The runners needed food to sustain their energy.",
  symptom: "A sore throat is a common symptom of a cold.",
  syndrome: "The doctor diagnosed the patient with the rare syndrome.",
  technique: "She perfected her painting technique over many years.",
  technology: "New technology has transformed how we communicate.",
  temporary: "The detour is only a temporary inconvenience.",
  tendency: "She has a tendency to arrive a few minutes early.",
  terminal: "We waited at the airport terminal for our flight.",
  territory: "The wolf defended its territory from intruders.",
  testimony: "The witness gave her testimony in court.",
  texture: "The fabric had a soft and smooth texture.",
  theology: "He studied theology at the seminary.",
  theory: "Einstein's theory of relativity changed physics forever.",
  therapy: "Physical therapy helped her recover from the injury.",
  thorough: "The detective conducted a thorough investigation.",
  threshold: "She stood at the threshold of the front door.",
  tolerance: "Tolerance for others is the foundation of a peaceful society.",
  toxic: "The chemical spill released toxic fumes into the air.",
  tragedy: "The shipwreck was a terrible tragedy.",
  transform: "The renovation will transform the old building.",
  transformation: "The caterpillar's transformation into a butterfly is amazing.",
  transition: "The transition from elementary to middle school can be exciting.",
  transmit: "Radio towers transmit signals over long distances.",
  transparent: "The glass was completely transparent and crystal clear.",
  transport: "Trucks transport goods across the country.",
  tremendous: "She made tremendous progress in her studies.",
  triumph: "Winning the championship was a moment of great triumph.",
  tropical: "The tropical island had white sand beaches.",
  turbulent: "The airplane encountered turbulent air over the mountains.",
  ultimate: "The ultimate goal is to improve education for all.",
  undergo: "The patient will undergo surgery tomorrow morning.",
  uniform: "All students must wear the school uniform.",
  unique: "Every snowflake has a unique pattern.",
  universal: "Music is often called a universal language.",
  unprecedented: "The flooding was of unprecedented severity.",
  urban: "The urban neighborhood was full of restaurants and shops.",
  utility: "The utility company supplies electricity to the region.",
  utilize: "She learned to utilize every minute of study time.",
  vacant: "The vacant lot will be turned into a community garden.",
  valid: "A valid passport is required for international travel.",
  variable: "The weather is the most variable factor in the plan.",
  venture: "Starting a business is an exciting venture.",
  verdict: "The jury reached a verdict after three days.",
  version: "The latest version of the software has new features.",
  vertical: "The rock climber scaled the vertical cliff face.",
  veteran: "The veteran served his country for over twenty years.",
  vibrant: "The vibrant colors of the mural brightened the street.",
  vigorous: "A vigorous workout leaves you feeling energized.",
  violate: "Anyone who violates the rules will face consequences.",
  virtual: "The virtual tour let us explore the museum from home.",
  visible: "The lighthouse was visible from several miles away.",
  vision: "Her vision for the project inspired the whole team.",
  vital: "Vitamins are vital for maintaining good health.",
  vocabulary: "Reading regularly helps expand your vocabulary.",
  volcano: "The active volcano erupted with a huge cloud of ash.",
  volume: "Please turn down the volume on the television.",
  voluntary: "Helping at the shelter is completely voluntary.",
  vulnerable: "Young birds are vulnerable to predators.",
  warrant: "The police obtained a warrant to search the building.",
  welfare: "The government program supports the welfare of children.",
  widespread: "The disease became widespread across the region.",
  wilderness: "They hiked deep into the untouched wilderness.",
  withdraw: "She went to the bank to withdraw some cash.",
  witness: "The witness described exactly what she saw.",
  workshop: "The writing workshop helped students improve their essays.",
  yield: "The fertile soil will yield a bountiful harvest.",
};

export default SCHOOL_SENTENCES;
